### ISSUE TITLE
Deprecate `with` in Style selectors

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1005]
**Is your feature request related to a problem? Please describe.**
The original Style language allowed selectors with a list of predicates following both the `with` and `where` keywords.  There was a subtle stylistic difference between these two, but we realized they didn't do anything functionally and have generally gravitated toward all examples simply using `where`.  E.g.,

```
forall Triangle t
where IsEquilateral( t )
```

Currently, the Style compiler still allows you to write

```
forall Triangle t
with IsEquilateral( t )
```

This redundancy is especially confusing to new users of Penrose, who see both keywords in examples, with no clear explanation about what the difference might be.

**Describe the solution you'd like**
We should just deprecate `with`, and issue an error if it is used.

**Describe alternatives you've considered**
We could leave `with` as-is, but it will still be sort of a dangling appendix in our otherwise beautiful language. ;-)

**Additional context**
To implement this change, we'll have to update the examples.  This shouldn't be too hard, since it's a straightforward replacement: identify all uses of `with` and replace them with `where`; if this leads to selectors with multiple `where` clauses, join them into a single clause.

**Comment by samestep** [comment]
@ZiyaoWei Thanks for looking into this! Yep, it looks like you're right: I looked through the Style parser just now, and it seems that currently we only allow `with` for declarations and `where` for relations, respectively.

@keenancrane I'm closing this as resolved; feel free to comment here if this isn't what you were referring to.
