### ISSUE TITLE
Require Style rules to start with `forall`

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1006]
**Is your feature request related to a problem? Please describe.**
In the original Style language, rules do not start with any kind of keyword (as in CSS).  But prior to publishing the paper we realized it would be clearer from a human readability point of view to start rules with a `forall` statement.  For instance,

```
Node n {
   …
}
```

became

```
forall Node n {
   …
}
```

For backwards compatibility, the Style compiler still allows the former.

**Describe the solution you'd like**
The time has come to make the compiler more strict!  Let's issue an error if a Style rule does not start with `forall`.

This change would be a nice small step toward implementing the much larger list of changes to Style selectors in #290.

**Describe alternatives you've considered**
We could leave things the way they are, but users (including @jiriminarcik, ten minutes ago!) will be confused about what it means for a rule to start without a `forall` statement.

**Additional context**
We'll have to update the examples to be compatible with this feature.  Shouldn't be too hard: just grep for rules that don't start with `forall` and add it.

**Comment by liangyiliang** [comment]
I agree - this would be an easy edit to the parser.
