### ISSUE TITLE
Provide explicit random sampling in Style

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1020]
It would be really helpful in Style to be able to say something like

```
scalar x.val = random( minVal, maxVal )
```

and get a random value that stays fixed throughout optimization.  This value would change only if the `variation` changes.  In fact, we already get this behavior if we write

```
scalar x.val = ?
```

and `x.val` is not used in any constraints/objectives: it gets set to a random value that is unaffected by optimization, and does not change unless the `variation` changes.  Basically we’re just lacking the ability to sample values from a user-specified range rather than whatever heuristic the sampler uses by default.

#### Bonus points

In a graphical context, it's often useful to have other random samplers.  For instance, a method

`vec2 p = uniformRandomDisk()`

might be provided to sample a point in the unit disk D² := { x ∈ ℝ² : |x| ≤ 1 }.  This method can be implemented via the formula

> √u ( cos(v), sin(v) )

where `u` and `v` are both uniform random values from [0,1].  Note that you have to be careful when implementing these formulas—it's easy to write something that sounds good, but gives the wrong distribution.  E.g., for the disk it's tempting to just use the first number as the radius (without the square root) and the second number for the angle:

![image](https://user-images.githubusercontent.com/3604525/170298765-96885472-0b8d-4d6e-b044-44d017c83052.png)

Other formulas, as well as a recipe for deriving uniform sampling formulas for other shapes, can be found in the article,

Jim Arvo, "[Stratified Sampling of 2-Manifolds](https://cseweb.ucsd.edu/~viscomp/classes/cse274/wi18/readings/course29sig01.pdf)", SIGGRAPH Course Notes (2001)

**Comment by samestep** [comment]
#1199 refactors our `InputMeta` type to support this; then all that would remain is to expose whatever particular `random` sampler functions we want in `packages/core/src/contrib/Functions.ts`.

**Comment by keenancrane** [comment]
Thanks to the work of @wodeni and others on #1199, this issue has now been addressed in #1404.
