### ISSUE TITLE
Support typical SVG attributes (stroke-width) in Equations

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#1023]
as per @keenancrane's remark: https://github.com/penrose/penrose/blob/walk-on-spheres/packages/examples/src/walk-on-spheres/walk-on-spheres.sty#L336

MathJax labels are just ordinary `<path>`s so we can do some tree walking and apply attributes to all of them.

Just have to do `renderedLabel.getElementsByTagName("path").setAttribute("stroke-width", ...`.

But why are we setting stroke-width to 0 right now? https://github.com/penrose/penrose/blob/228746ee7544e4cf69c84f7bf871f0c9d95edcc5/packages/core/src/renderer/Equation.ts#L40

**Comment by cmumatt** [comment]
Thanks for submitting this issue!  IIRC, the code snippet above pre-dates the renderer refactor and is probably due to Equation's lack of stroke properties.  I'll take a look at this one, too.
