### ISSUE TITLE
Don't emit Penrose-specific attributes in SVG

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1024]
Earlier this year @cmumatt did an [awesome PR](https://github.com/penrose/penrose/pull/749) to pass through arbitrary attributes from Style to SVG.

One final little thing to resolve is that Penrose-specific attributes _also_ get passed through to the SVG.  For instance, here's the output for a circle:

```
<circle fill="none" cx="98.82251439462043" cy="116.59791200601026" stroke="#000000" stroke-opacity="1" stroke-width="1.5" stroke-linecap="butt" r="62.11043606853752" ensureOnCanvas="false">
```

Notice in particular the `ensureOnCanvas` attribute, which is part of Penrose but not SVG.  Fortunately the browser ignores this attribute, but it seems like a problem just waiting to happen.  It also adds unnecessary size/bulk to the output files.

### Proposed solution

To get the ball rolling, let's just have a list of attributes that are Penrose-specific, and filter these out when constructing the SVG.  This is way (way) easier than keeping a list of attributes that are SVG-specific, and keeping this list in synch with various SVG versions.  In fact, the only two that come to mind are:

- `ensureOnCanvas`
- `name`

The latter (`name`) is especially insidious, since it sounds like something that _could_ be an SVG attribute—but isn't.  Instead, we already write this name within an [SVG `<title>` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title), which is used for accessibility.  But the SVG attribute `name="..."` is meaningless.

**Comment by cmumatt** [comment]
@keenancrane, thanks for observing this in the SVG output and opening this issue!

Agreed: the renderer should _not_ pass through the known (and non-SVG) internal properties `ensureOnCanvas` and `name`.  The original development included a mechanism to prevent this.  I'll take a look at what's going on, fix it in a PR, and add a test case to prevent future regression.
