### ISSUE TITLE
Can't open official website https://penrose.cs.cmu.edu/

### ISSUE THREAD

**Issue by Nunatic02** [penrose/penrose#1028]
Opening `https://penrose.cs.cmu.edu/` and any sub URLs results in an error page displaying 
``` 
This site can’t provide a secure connection
penrose.cs.cmu.edu uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by cmumatt** [comment]
@nunatic02, thanks for opening this issue!  

We hope you are enjoying the site -- when it's working.  We are using CloudFlare Pages to host the site, but CloudFlare is presently having issues applying the penrose.cs.cmu.edu domain to our Pages project.  

The problem is clearly on CloudFlare's end; unfortunately, we are waiting for them to fix that problem.  In the meantime, we've re-activated the old https://penrose.ink/ domain.  Feel free to use https://penrose.ink/ until CloudFlare fixes the issue with the main domain.

Hope this helps.  Thanks and have a great day!

**Comment by Nunatic02** [comment]
> @Nunatic02 , thanks for opening this issue!
> 
> We hope you are enjoying the site -- when it's working. We are using CloudFlare Pages to host the site, but CloudFlare is presently having issues applying the penrose.cs.cmu.edu domain to our Pages project.
> 
> The problem is clearly on CloudFlare's end; unfortunately, we are waiting for them to fix that problem. In the meantime, we've re-activated the old [penrose.ink](https://penrose.ink/) domain. Feel free to use [penrose.ink](https://penrose.ink/) until CloudFlare fixes the issue with the main domain.
> 
> Hope this helps. Thanks and have a great day!

Ah, the old link works perfectly now! Thanks for the effort!
Btw, the Penrose project, the editor, the documentation, and all the tutorials are just amazing!! (I like how exercises are added to the tutorials 😝, like reading a textbook). 
Thank you all so much for making these possible!

**Comment by cmumatt** [comment]
@Nunatic02, thanks for sharing that!  I am super glad you are enjoying Penrose, the tutorials, and the documentation!  The team puts a lot of heart into Penrose and are glad it shows!

We have an expanded IDE we are about to release to the site that is pretty amazing.  Stay tuned -- as soon as CloudFlare gets this fixed, you'll see it live.  Or, feel free to clone the repo to run it locally.  

If you liked the old IDE, you'll love the new one even better!  Have a great day!

**Comment by Nunatic02** [comment]
> @Nunatic02 , thanks for sharing that! I am super glad you are enjoying Penrose, the tutorials, and the documentation! The team puts a lot of heart into Penrose and are glad it shows!
> 
> We have an expanded IDE we are about to release to the site that is pretty amazing. Stay tuned -- as soon as CloudFlare gets this fixed, you'll see it live. Or, feel free to clone the repo to run it locally.
> 
> If you liked the old IDE, you'll love the new one even better! Have a great day!

Ahhh! Can't wait to try that!!

**Comment by joshsunshine** [comment]
@Nunatic02 you can try it now using this link: https://penrose-72l.pages.dev/
That link isn't permanent, but it will work for the time being.

**Comment by Nunatic02** [comment]
Ahh! Thank you so much!! 🥰🤩🤩

**Comment by joshsunshine** [comment]
The official URL, [https://penrose.cs.cmu.edu/](https://penrose.cs.cmu.edu/), works again. Thanks for your patience @Nunatic02
