### ISSUE TITLE
Staged diagrams are untested

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1040]
@heleaf added support for staged diagram generation in #610. It is surfaced by `@penrose/automator`, but we currently don't test it either in our `@penrose/core` unit test suite or in our end-to-end `bench` job in CI. To prevent regressions, we should test staged diagram generation. In particular, I believe #984 modified the number of diagrams produced and the order of shapes included in each one, so they no longer correspond to the list of Substance statements as originally intended by #610.

**Comment by keenancrane** [comment]
@samestep I wouldn’t get too hung up on integrating this feature. There are a lot of discussions we’ve had (and yet need to have) about the design of the system around:

- staged diagrams 
- animation 
- optimization stages

These interact in tricky ways, and I don’t think the feature PR described above adequately captures everything yet. Let’s all discuss before moving forward any further.
