### ISSUE TITLE
In IDE vim mode, recompile on :w

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1046]
When doing local edits with `roger watch`, the old IDE would automatically recompile and re-layout when files changed (e.g., whenever they were written to).

It would be nice if the vim mode of the new IDE would automatically trigger a recompile/re-run when you type `:w` (followed by an `enter`), which in vim corresponds to writing a file.  Otherwise, you have to click the `compile` button every time.

**Comment by maxkrieger** [comment]
@keenancrane fixed in #1197!
