### ISSUE TITLE
First compile of example diagram in IDE does not always look right

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#1047]
**Describe the bug**
The first (automatic) compile of an example in the IDE does not always render the expected diagram.  In some cases, the labels might not be not visible.  A comparison of one set of outputs showed a slightly different SVG: the SVG without visible labels contained additional group elements with transforms.  The source of the difference hasn't been investigated, but this was also reported previously in the old IDE.  The workaround is currently to manually press the compile button, which resolves the problem.  But the automatically-compiled diagram should look the same as the manually-compiled diagram.

**To Reproduce**
Open the IDE.  Choose and load an example like tree-venn-3d.  Repeat the load if necessary to get one that doesn't look right.  Click compile and see the diagram is fine.

**Comment by wodeni** [comment]
Cannot repro this anymore. Possibly due to #1144. Closing for now.
