### ISSUE TITLE
Improve IDE error handling during prepareState

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#1055]
**Describe the bug**
Currently errors raised during prepareState are not reported to the IDE user.  They may only be reported to the console.  

**To Reproduce**
Load the IDE.  In the `tree-venn-3d example` change `width` on line 28 to `fontSize` and compile.  This will raise an error, but this error is not reported to the user in the UI.

**Expected behavior**
Catch and raise the error to the IDE user, similar to other errors.

**Comment by wodeni** [comment]
`prepareState` no long exists, but issues like #1446 still exist. The problem in the description is now caught by the IDE. Closing in favor of more concrete issues.
