### ISSUE TITLE
Multiple Matching Issue

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1062]
**Describe the bug**
Sometimes, the same things in substance can be matched multiple times by the same style rule, due to the style matcher accepting multiple different variable mappings.

**To Reproduce**
Here is the program trio to reproduce the issue, on the current newest version on the `main` branch: https://fake3dlinalg.penrose-72l.pages.dev/try/?gist=fd9cf13ae1b6faebedc2bab08bb23ba4.

For convenience, the code is as follows:
```
-- Substance
Hydrogen H1, H2
Oxygen O
Bond( O, H1 )
Bond( O, H2 )

-- Style
canvas {
    width = 50
    height = 40
}

forall Oxygen o; Hydrogen h1; Hydrogen h2
where Bond(o,h1); Bond(o,h2) {
    myText = Text {
        string: "Water!"
        fillColor: rgba(0, 0, 0, 255)
    }
}

-- Domain
type Atom
type Hydrogen <: Atom
type Oxygen <: Atom
predicate Bond( Atom a1, Atom a2 )
```

**Expected behavior**
The style program is supposed to detect water molecules with `forall Oxygen o; Hydrogen h1; Hydrogen h2 where Bond(o,h1); Bond(o,h2)`. Whenever it sees a water molecule, it should print, in giant fonts, "Water" on the canvas. The substance program only has one water molecule, but this style rule is invoked twice, and "Water" is printed twice on the canvas.

**Screenshots**
Here is what it currently shows on the canvas:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/16521252/178795583-804f3206-ed0f-44bf-870d-8206ae9d8832.png">

**Speculations about Bug**
Here are some speculations about what's happening. The style compiler generates two possible sets of variable mappings for `forall Oxygen o; Hydrogen h1; Hydrogen h2`:
```
Mapping 1:
  StyVar -> SubVar
  o      -> O
  h1     -> H1
  h2     -> H2

Mapping 2:
  StyVar -> SubVar
  o      -> O
  h1     -> H2
  h2     -> H1
```
It turns out that both mappings satisfy the relational declaration `where Bond(o,h1); Bond(o,h2)`, so the rule is invoked twice.

**Potential Solution**
Each block in the Style program maintains a set of Substance declarations that it matched upon, which we call `MatchedDeclarations`. For instance, for the example provided, we initially start with an empty set:
```
MatchedDeclarations = {}
```

Suppose we now match upon `Mapping 1`. This will add an element into the set. The new element is itself a set: `{Bond(O, H1), Bond(O, H2)}`. Then,
```
MatchedDeclarations = {
  {
    Bond(O, H1), 
    Bond(O, H2)
  }
}
```
This will trigger the rule and print one "Water" on the canvas.

Then, if we match upon `Mapping 2`, this will generate a set `{Bond(O, H2), Bond(O, H1)}`, which is already a member of `MatchedDeclarations`.  This utilizes the fact that
```
{Bond(O, H1), Bond(O, H2)} === {Bond(O, H2), Bond(O, H1)}
```
since sets are orderless. Since such a mapping will not trigger the rule, since the _same_ thing has already matched the rule in the previous step.

**Thoughts**
The most important question, however, is whether or not this really is a _bug_. Is it the expected behavior (according to our users) to print two "Water" on the canvas, or do the users expect only one?

**Comment by joshsunshine** [comment]
I think the key question is whether we want to support both matching semantics. For simplicity's sake, I prefer to support one "equivalent" match and not support the current mutli-match semantics. @samestep @wodeni is that okay with both of you?

**Comment by liangyiliang** [comment]
@keenancrane Do you know of any applications where matching the same rule on the same thing twice is actually expected? We are trying to determine whether or not we should make the single-match semantics the default - Thanks!
