### ISSUE TITLE
Better Matching Semantics

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1065]
# The Problem
The current mechanisms for matching Style programs to Substance programs are very rudimentary. By default, we perform "set-matching", but only very barely, with problems like #1062 and #1064 .

# The Solution
We need a clear set of semantics and new syntax for matching style to substance. Now, consider a substance program:
```
Atom A, B
```
## Set-Matching Semantics
Selectors
```
forall Atom a; Atom b
forall {Atom a; Atom b}
forall distinct Atom a; Atom b
forall distinct {Atom a; Atom b}
```
are equivalent, and admit either `a -> A, b -> B` or `a -> B, b -> A`, but not both. Set-matching semantics requires that all objects matched are distinct, since sets only store distinct elements. The potential keyword `distinct` is optional, and has no effect on the set-matching semantics.

Extending to more-than two objects, these four selectors all match _only one_ of the possible permutations of the objects (that satisfy the relational constraint).

## Tuple-Matching Semantics
We also allow for matching tuples, the non-default behavior. The selector
```
forall (Atom a; Atom b)
```
admits four possible mappings:
* `a -> A, b -> B`,
* `a -> B, b -> A`,
* `a -> A, b -> A`, and
* `a -> B, b -> B`.
Note that we do _not_ require the matched objects to be distinct, since tuples may have non-distinct elements. Extending to more-than-two objects, this selector matches _all_ of the possible permutations of the objects (that satisfy the relational constraint).

However, we also allow an optional `distinct` keyword that ensures the distinctness of the matched objects. Selector
```
forall distinct (Atom a; Atom b)
```
admits both
* `a -> A, b -> B`, and
* `a -> B, b -> A`.

## Combining Different Semantics
We are thinking of whether we need nested semantics. One example of such selectors is
```
forall Atom a; (Atom b; Atom c)
```
which, given Substance program `Atom A, B, C`, matches
* `A, (B, B)`
* `A, (B, C)`
* `A, (C, B)`
* `A, (C, C)`
* `B, (A, A)`
* `B, (A, C)`
* `B, (C, A)`
* `B, (C, C)`
* `C, (A, A)`
* `C, (A, B)`
* `C, (B, A)`
* `C, (B, B)`.

To require distinctiveness for `Atom b; Atom c`, we say
```
forall Atom a; distinct (Atom b; Atom c)
```
which gives us
* `A, (B, C)`
* `A, (C, B)`
* `B, (A, C)`
* `B, (C, A)`
* `C, (A, B)`
* `C, (B, A)`.

**Comment by joshsunshine** [comment]
I don't think we should support `forall distinct {Atom a; Atom b}`. If this feature is implemented `forall (Atom a; Atom b)` will mean something different than `forall distinct (Atom a; Atom b)`, but `forall distinct {Atom a; Atom b}` will be equivalent to `forall {Atom a; Atom b}`. I think that is confusing.

**Comment by joshsunshine** [comment]
I think we should postpone implementing "combined" set/tuple semantics. They are relatively complex and we don't have a good use case for them right now.

**Comment by liangyiliang** [comment]
For now I’ll require everything matched to be distinct, and introduce the special Style predicate Ordered(...)  (that takes a variable number of arguments). For instance,
```
forall Thing t1, t2, t3, t4, t5
where Ordered(t2, t3, t4) { ... }
```
will match all different orders of `(t2, t3, t4)` . In particular,
```
(t1, t2, t3, t4, t5) ==> (T1, T2, T3, T4, T5)
```
and
```
(t1, t2, t3, t4, t4) ==> (T1, T4, T3, T2, T5)
```
will be considered different, whereas
```
(t1, t2, t3, t4, t5) ==> (T1, T2, T3, T4, T5)
```
and
```
(t1, t2, t3, t4, t5) ==> (T5, T2, T3, T4, T1)
```
will be considered the same substitution and only matched once, since `t1, t5` are unordered. This should integrate quite well with the current methodology to deduplicate matches. This method also automatically (without doing any additional work) gives us very flexible matching, that involves allowing some things to be ordered and some others to be unordered. (edited)

**Comment by joshsunshine** [comment]
Is the long-term goal for the `forall (Atom a; Atom b)` to be syntactic sugar for:
```
forall Atom a; Atom b 
Ordered(a, b)
```

**Comment by liangyiliang** [comment]
Yup, I think so.

**Comment by liangyiliang** [comment]
It's just that the predicate form for Ordered(a, b) integrates well with how we prevent double-matching.

**Comment by liangyiliang** [comment]
Upon discussions from yesterday, we are _temporarily_ leaving this aside until we find specific examples where this would be useful.

**Comment by liangyiliang** [comment]
After attending the SPECS summer school and drawing diagrams corresponding to _Alloy_ models, we have discovered some real motivation to add in support for non-distinct matching.

For example, in an Alloy model, there might be this ternary relation $\mathsf{Rel}$ that relates three objects. For example, an instance of this model has $(A, B, C) \in \mathsf{Rel}$. Alloy's default visualizer draws this relation as follows:
<img width="400" src="https://github.com/penrose/penrose/assets/16521252/147d3a6a-8217-4099-bd9e-6c6b8e1a692e"/>

To replicate this, we can represent this instance in Substance:
```
Object A, B, C
Rel(A, B, C)
```
with a Style block:
```
forall Object a; Object b; Object c
where Rel(a, b, c) {
  ... draws the arrow...
}
```
Now, what if we want to draw `Rel(A, A, C)`, `Rel(A, B, B)`, `Rel(A, B, A)`, `Rel(A, A, A)`, and other similar instances under renaming? Since selectors do not allow for non-distinct objects, one must write,
```
forall Object a; Object b; Object c where Rel(a, b, c) { ... }
forall Object a; Object c where Rel(a, a, c) { ... }
forall Object a; Object b where Rel(a, b, b) { ... }
forall Object a; Object b where Rel(a, b, a) { ... }
forall Object a where Rel(a, a, a) { ... }
...
```
and this entails lots of code repetition which is extremely difficult to debug and maintain. In particular, our goal is for the Penrose-based Alloy visualizer to automatically generate the Substance, Domain, and Style files and give the users the flexibility to edit the Style files for customization. Code repetition like these make these customization process difficult.

Another case for visualizing Alloy models is that, for example, we want the arrows to not cross each other. This is done as follows:
```
forall Object a, b, c, d, e, f
where Rel(a, b, c); Rel(d, e, f) { ... }
```
This runs into the same problem. In fact, this problem is larger, since the number of selectors needed blows up exponentially.

**Comment by liangyiliang** [comment]
@wodeni and I have thought of two solutions to this issue, both of which require minimal changes to language.

Under both solutions, by default, `forall` does distinct matching.

_**Solution 1**_: special keyword after `forall`.

We can optionally write `forall nondistinct` to allow for non-distinct substitutions. The Alloy example can then be translated into:
```
forall nondistinct Object a; Object b; Object c
where Rel(a, b, c) { ... }
```

Notice that the `nondistinct` keyword is a part of the entire `forall` selector, and applies to everything in the selector. There is no way to specify exactly which objects we want to be nondistinct, and which others are to be distinct.

Implementing this keyword in the compiler is quite straightforward too. The compiler currently computes a list of all possible substitutions, before filtering out those that have duplicating values. For a `forall nondistinct` block we simply skip this filtering.


_**Solution 2**_: special keyword after object declarations.

Recall that each selector block comes with a list of object declarations. For each object declaration, we can specify whether or not they should be non-distinct by using the `nondistinct` keyword.

For example,
```
forall Object a, b, c nondistinct; Object d, e { ... }
```
This declares that `a, b, c` can be non-distinct, whereas `d, e` must be distinct by default.

**Comment by joshsunshine** [comment]
@liangyiliang, how will Solution 1 interact with subtyping?

**Comment by liangyiliang** [comment]
@joshsunshine I don't think Solution 1 would change how subtyping works. Right now, we already skip any substitutions that violate the type systems (e.g. subtyping) at the lowest level of the matching process. Solution 1 would reuse this low-level matching process. The "extra" stuff that solution 1 matches would still comply with the subtying constraints.

**Comment by liangyiliang** [comment]
See my [updated comment](https://github.com/penrose/penrose/issues/1065#issuecomment-1638770891).

Out of solutions 1 and 2, I think both will work, but I favor Solution 1. 

Solution 2 is more expressive than Solution 1 since it allows for a mix between distinct and nondistinct items. But, all of the problems I had with code duplication can be resolved using Solution 1, and I personally haven't seen an example where such a mix is needed. I'm not sure whether or not we want or need this added expressiveness of Solution 2.

## What about `collect`?

Another reason I prefer Solution 1 is that this can easily be extended to the `collect` blocks. For example, we want to collect all `Object` instances where such an object appears as the first argument to `Rel`, like this:
```
collect Object a into objs
where Rel(a, b, c)
with Object b, c{
  ...
}
```

Suppose the Substance program is as follows:
```
Rel(A, B, C)
Rel(A, A, C)
```
Running the `collect` block against this Substance program yields that `objs = [A]` (contains only one `A`), since `collect` uses the same underlying matching algorithm as `forall`. But this is certainly not what we wanted, since `A` appears twice as the first argument to `Rel`.

Using Solution 2, we have to find a way to write something like `Object a, b, c nondistinct`. This is simply not possible in `collect`, since `a` _must_ be declared separately.

Using Solution 1 simply entails,
```
collect nondistinct Object a into objs
where Rel(a, b, c)
with Object b, c{
  ...
}
```
and we will have `objs = [A, A]` as needed.

**Comment by liangyiliang** [comment]
Here are some alternative keywords @wodeni thought of that can be used in place of `nondistinct`: `repeating`, `canrepeat`, `mayrepeat`. 

I think we should emphasize the "_may_" part. That is, using this new keyword, the selector _can_ still match distinct objects as before - but it can also match more objects.

**Comment by wodeni** [comment]
One other similar keyword option would be `repeatable`

**Comment by joshsunshine** [comment]
@liangyiliang I think we should got with Solution 1. However, I'm worried there might be some small confusion when subtypes are matched. Consider the following selector:
`forall nondistinct Atom a; Hydrogen h; Object o`
Assuming that `Hydrogen` is a subtype of `Atom` in the domain program, both `h` and `a`  may map to the same Hydrogen value declared in substance. That may confuse the Style write who assumes that the type difference would yield different values. I don't think this is a dealbreaker for Solution 1, but I wanted to make a note about the issue.
