### ISSUE TITLE
Automator is slow

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1082]
Currently Automator's startup time (i.e. not counting the time it takes to actually do things) is several seconds. This is way too slow. There's probably a way to make it faster.

**Comment by wodeni** [comment]
Looks like `ts-node` is doing transpilation and typechecking in every single run without caching. A quick patch is to bump `ts-node` to v10 and use `transpileOnly`, deferring typechecking to CI. Tried [SWC](https://typestrong.org/ts-node/docs/swc/) but it's failing with a "`window` not found" error in MathJax.
