### ISSUE TITLE
Make shapes generic: create "books" for shapes

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#109]
The long-term motivation of this issue is to create "books" for user-defined shapes, e.g. `linear-algebra.shapes`.

The short-term motivation is that currently, our system has a lot of code duplication and polluted namespaces due to our use of records for each shape, which makes it hard to perform generic operations over a shape. I believe we can make most of the mechanisms more generic by **storing a shape datatype as data (specifically, as a dict)** rather than a record. This is essentially a manual way to let us reflect over records so that we can map over them, update values, look up names, etc. all generically.

For example, currently `Circ' a` looks like this:

```
data Circ' a = Circ' {
    xc'     :: a,
    yc'     :: a,
    r'      :: a,
    strokec':: a,
    namec'  :: String,
    stylec' :: String,
    colorc' :: Color
} deriving (Eq, Show)
```

In the new approach, it would look like this:

```
-- PropertyType is a new type that gives the type of a property (as a value)
-- for a given property type, we know default values for initializing it, and we know how to sample it 
-- note: we no longer have to care about clashing record namespaces!
circType :: (TypeStr, M.Map Property PropertyType)
circType = ("Circ", M.fromList [
    ("x", FloatT),
    ("y", FloatT),
    ("stroke", FloatT),
    ("name", StringT),
    ("style", StringT),
    ("color", ColorT)
])

exampleCirc :: (Autofloat a) => (TypeStr, M.Map Property (TypeIn a))
exampleCirc = ("Circ", M.fromList [
    ("x", TFloat 5.5),
    ("y", TFloat 100.2),
    ("name", TName "C1"),
    ("color", TColor "blue")
]) 

-- note that not all fields need to be initialized
-- the rest of the fields will be initialized with a default value or sampled

-- TODO: figure out how to let the user specify derived properties, initial constraints/objectives, etc.
-- TODO: how to deal with composite shapes?

```

With this approach, all shape-specific functions or cases (pack, unpack, initialization, sampling, get, set, adding/removing gradients, annotating, parsing etc.) would become generic, because now we can do casework on `TypeIn a`. We would need to write our own typechecking for values of a shape, but it would also be generic. We would also need to convert all existing objectives/constraints/computations to use the new shape API.

Additionally, since shapes are now data, the system can easily be extended to add user-defined shapes at runtime. We can come up with a nicer record syntax for declaring shapes (just like the DSLL books) and parse it at our compiler's runtime. 

We would still need to factor out the visual representation of a shape (as the renderer code that draws the shape) and make that part of the `.shapes` plugin, but shapes-as-data is a good first step toward graphical extensibility. (In general, doing this whole thing would greatly support our graphics extensibility story.)

See current actions needed to add a new shape: [wiki](https://github.com/penrose/penrose/wiki/Extending-the-system)

Note: NewStyle already pretty much does this with the FieldDict and PropertyDict, but Runtime doesn't.

I believe Keenan suggested that we do something like this as well.

**Comment by hypotext** [comment]
@wodeni Is this something you'd be interested in working on? I'm already reworking a lot of Runtime to fit with the new Style compiler, so now would be a good time to coordinate on making this change.

**Comment by wodeni** [comment]
Just to put all options on the table. Haskell Lenses can also be used in this situation, since all of our shapes are defined using product types (an intro article [here]( https://mmhaskell.com/blog/2017/6/12/taking-a-close-look-at-lenses). I personally like the dict solution a lot better, since we will have a cleaner namespace and possibly better ways to write the pack functions (?).

**Comment by hypotext** [comment]
Great! Let's talk more tomorrow.

Re lenses: thanks for the suggestion. Just from skimming the article, it looks like lenses don't provide all the functionality I'm looking for, like the ability to map/fold over fields of a record or the ability to get the type of a record's field.

Also, I have three other reasons for preferring shapes as dicts:

* the new Style compiler already outputs a translation where shapes are stored as dicts
* if we want to allow users to add shape definitions (just like users can already write "books"), then shapes really *are* data
* it's better to keep the system easy to port by minimizing use of advanced Haskell where possible. e.g. this approach maps closely to Javascript's model of "every object's a dict that you can reflect on"

**Comment by wodeni** [comment]
Agreed. Thanks for writing out these reasons. Let's talk about the implementation plan later then!

**Comment by wodeni** [comment]
Ideal `.shapes` file:
```

renderer Snap = -- some specification about the renderer such that Runtime knows
                -- How to load it and use it
renderer POVRAY = -- 3D rendering

-- Definition of a shape:
--   property names with types and default values
shape Circle =
    Float  x      (default 0.0)
    Float  y      (default 0.0)
    Float  stroke (default 0.0)
    Style  style  (default "filled")
    String name   (default "defaultCircle")
    Color  color  (default black)

-- Render function of a shape using one of the renderers
-- "<>" enclose code in another language
render Circle Snap = <
    function _renderCircle(s, obj) {
        [x, y] = Utils.scr([obj.x, obj.y])
        var circ = s.circle(x, y, obj.r);
        circ.data("name", obj.name)
        var color = obj.color
        circ.attr({
            fill: Utils.hex(color.r, color.g, color.b),
            "fill-opacity": color.a,
            "stroke-width": obj.stroke,
            "stroke": "black",
        });
        if(obj.style == "dashed") {
            circ.attr({
                strokeDasharray: "7, 5" // "10"
            })
        }
        circ.drag(move, start, stop)
    }
>

```

**Comment by maxkrieger** [comment]
Partially complete, continuing discussion in #195
