### ISSUE TITLE
`checkSymmetricArgs` checks empty type graphs

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#1110]
**Describe the bug**

When checking `symmetric`, the checker attempts to use `typeGraph` by calling `isSubtype` for both arguments to make sure they are identical. When they are actually identical types, this is okay. However, when one is a subtype of another, `isSubtype` returns `false` for both `isSubtype(MyType, MySubType)` and `isSubtype(MySubType, MyType)`. 

```
type MyType
type MySubType <: MyType
symmetric predicate MyBadPredicate(MyType a, MySubType b)
```

**To Reproduce**

Print out `console.log(isSubtype(type1, type2, env), isSubtype(type2, type1, env));` in `areSameTypes` when running the Domain tests and observe that only `true true` and `false false` show up. In one of the cases, it should print out `true false` or `false true`. 

**Expected behavior**
`isSubtype` cannot be called within the Domain checker, especially while the checker is going through the program. This is because `computeTypeGraph` is not called until the checking is done. 

Because `checkSymmetricArgs` doesn't want subtypes at all. It could check the names of predicate arguments instead. 

Alternatively, run the symmetry check _after_ the Domain checker finishes its pass through the Domain program.

Or, construct the type graph as the checker runs, but one will need to pay attention to where `<:` statements show up in the program, because a naive implementation will need them to appear before any symmetric predicates.

**Comment by liangyiliang** [comment]
> It could check the names of predicate arguments instead.

One issue is that our types might be `TypeFunctions` which are present in the language ... I guess it's some type polymorphism feature which we haven't thoroughly tested?

**Comment by wodeni** [comment]
> One issue is that our types might be `TypeFunctions` which are present in the language ... I guess it's some type polymorphism feature which we haven't thoroughly tested?

Fun fact: Penrose used to have dependent types! But now it's basically generics that have some tests in Domain and Substance test suites. No end-to-end examples nor Style tests for sure.

**Comment by liangyiliang** [comment]
> > One issue is that our types might be `TypeFunctions` which are present in the language ... I guess it's some type polymorphism feature which we haven't thoroughly tested?
> 
> Fun fact: Penrose used to have dependent types! But now it's basically generics that have some tests in Domain and Substance test suites. No end-to-end examples nor Style tests for sure.

Hmmm ... if so, shouldn't we remove type polymorphism completely?

**Comment by samestep** [comment]
My impression is that the generics just don't work at all currently, so I'm down to remove them. @wodeni @joshsunshine thoughts?

**Comment by liangyiliang** [comment]
For now I will just use the approach of doing another pass after generating the type graph ...
