### ISSUE TITLE
Uncaught error in the Style compiler when selector relations refer to nonexistent variables

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#1123]
**Describe the bug**

When a Style relation (e.g. a binding) refers to variable not defined in the header but defined in the Substance file, an error occurs in the Style compiler. 

```
Uncaught (in promise) TypeError: e.name is undefined
```

**To Reproduce**

https://penrose.cs.cmu.edu/try/?gist=a7a33751a606a5688cb7c7cdf7aea9e7

1. go to the link above
2. press compile
3. observe error in the console

**Expected behavior**

A `varNotFound` error in the selector checker and surfaced to the UI.

This behavior is really caused by the Style compiler, specially the selector checking code, incorrectly merging the `varEnv` coming from the Substance checker and the `selEnv` in the Style compiler. Specially, while merging the two is necessary to match on both Style and Substance variables, the compiler needs to distinguish variables coming from (1) the Substance program itself (for checking against Substance names) and (2) the head of the current selector. 

A TODO item in the source code also described this: https://github.com/penrose/penrose/blob/ce4cb51cdb22b67d01766bd744073f191cc0a262/packages/core/src/compiler/Style.ts#L569

**Comment by liangyiliang** [comment]
That's something that I think I can work on
