### ISSUE TITLE
Inline comparison operators for constraints and objectives

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#1168]
**Is your feature request related to a problem? Please describe.**

Currently, only calls to the constraint library is allowed in `ensure` and `encourage` statements. The syntax can be a bit restrictive and counter-intuitive. For instance, to express `norm(c.vec) > 200`, one can only write `ensure lessThan(200, norm(c.vec))`. 

**Describe the solution you'd like**

Support boolean expressions such as `==`, `>`, `<`, `<=`, `>=` in constraint/objective statements as a starter. To improve the expressiveness, we may also support chained expressions such as `10 <= norm(c.vec) < 200`.

**Comment by wodeni** [comment]
Related issue: #815. Although the implementation may be different for inline expressions vs. constraints. A unified support for these operators might be nice.

**Comment by liangyiliang** [comment]
^ oops touched the wrong button.

But yup it sounds like a quick change to the compiler and parser!

**Comment by wodeni** [comment]
Another thought: constraints are implicitly ANDed together so `&&` is probably not a problem. How does `||` map to constraints numerically?

**Comment by liangyiliang** [comment]
> How does || map to constraints numerically?

Optimizing on `constraintA || constraintB` means minimizing `min(energy(constraintA), energy(constraintB))`?
