### ISSUE TITLE
dragUpdate doesn't work for shapes with no "x" and "y"

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#117]
`dragUpdate` in Server uses `setX` and `setY` to update a shape's coordinates with a drag location. This will fail at runtime if the user drags a shape that doesn't have `x` or `y` attributes, like an arrow in `continuousmap`:

```
penrose: get: Property "x" does not exist in shape "Arrow"
CallStack (from HasCallStack):
  error, called at src/ShapeDef.hs:561:5 in main:ShapeDef
```

I would suggest setting the center of the arrow to be the drag point.

**Comment by wodeni** [comment]
Concretely, `dragUpdate` function in the server just calls `setX` and `setY` on the object dragged in the frontend. Right now, the issue can be hackily resolved by overloading get/set functions, just like before:
```
setX v shape@("Arrow", _) = set shape "startX" v
setX v shape = set shape "x" v

getX arrow@("Arrow", _) = getNum arrow "startX"
getX shape = getNum shape "x"
```

**Comment by wodeni** [comment]
`dragUtils.ts` has been refactored to consider other properties. See #1143
