### ISSUE TITLE
Design more flexible/high-level property specifications for GPIs

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#119]
# Higher order properties for GPIs

## Types of higher order properties

- Type 1: aggregate properties
    - A collection of base properties grouped in lists or tuples
- Type 2: derived properties
    - properties that can be computed/derived by a mathematical expression involving just base properties
    - _This is probably the most interesting one_
    - Let's break this down into different cases here
        - When you have a __collection of derived properties that can fully specify a GPI, i.e. generate correct values for all base properties__: we can ask the Style writers to fully specify the derived properties. No partial specification is allowed.
            - If we allow partial specification of them, we may need to __generate some objectives for the unspecified shapes__. Maybe even automatically if the functions to compute base properties from derived ones are provided
        - If not, they should just be written as objectives or constraints (TODO: good reasons?)
- Type 3: GPI properties
    - _I personally think these should be written as optimization functions_
    - properties of types of GPIs. The values of these properties depend on the base properties of those GPIs, NOT on their own base properties

## RA Style Examples

After going through the RA Style in design paper, I think there is only one general case of derived properties here: the expansion of `start` into `startX` and `startY`.

```
R.xaxis = DoubleArrow {
    start = global.origin - (100, 100)
    end = global.right
}
```

```
p.line_x = Line {
    start = (x.val, R.xaxis.endY)
    end = p.val
}
```

If we don't want to build another layer of indirection (translating from `start` to `startX` and `startY`), we can also just do

```
p.line_x = Line {
    (startX, startY) = (x.val, R.xaxis.endY)
    (endX, endY)     = p.val
}
```

## LA Style examples

- `dim`: aggregate
```
U.shape = Rectangle {
    dim = bbox(U.x_axis, U.y_axis)
}
```
- `angle`, `length`, and `pos`: derived
```
U.y_axis = Arrow {
    angle = 90               -- angle with postive X axis
    length = len(U.x_axis)   -- normal of vector
    pos = midpoint(U.x_axis) -- midpoint of vector
}
```
- `location`: aggregate
```
U.origin = AnchorPoint {
    location = intersection(U.x_axis, U.y_axis)
}
```
- `from` and `to`: GPI
```
U.angle = Arc {
    from = U.x_axis
    to = U.y_axis
}
```
- `tail` and `head`: aggregate
```
v.shape = Arrow {
    tail = V.origin
    head = v.val
}
```
- `along`: GPI, too vague that it should be an obj/constr
```
c.shape = CurlyBrace {
    along = v.shape
}
```

- `side*`: derived, partially specified
```
c.shape = Parallelogram {
    side1 = v.shape
    side2 = w.shape
}
```

## Possible solutions

- Type 1 - aggregate: Have destructive binds to lists or tuples to set multiple values in one computation. (e.g. `path` is just a list of four floats)
- Type 2 - derived: Since in the long run, a lot of queries will be written as distance queries, maybe it’s a better idea to avoid things like angles in our shape definition. Moreover, maybe one criteria of our shapedef should be that all shapes are defined purely by position values.
  - If we choose to do so, one problem will be to maintain the shape of an object. If a parallelogram is defined as four points, we might need a constraint to make sure it has the properties of a parallelogram at the end of the optimization.
- **Random thought about maintaining shapes of complex but stable GPI**: If we want to minimize the burden on the optimizer, maybe it’s a better idea to have all shapes define x, y, rotation and scale and we apply a transformation matrix on the object before doing anything in our objectives and constraints
- Type 3: in general, I think they should be objectives

**Comment by hypotext** [comment]
TODO from raytracing domain
* Rectangle representation and angle. Are rectangles axis-aligned by default? Specify the top right and bottom left points, and the angle (as an internal representation in the system)?
* Arrow: `from` and `to`
* Arrow: `from`, `angle`, and `length`
* Arc: `from` and `to`
