### ISSUE TITLE
`components` type declarations get overwritten by Vite build

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1194]
In `packages/components/`, running `yarn build-decls` generates a bunch of `dist/**.d.ts` and `dist/**.d.ts.map` files, which are then deleted by `yarn build`. We should fix this, either by generating type declarations into a different directory from Vite's build directory, or by generating the `dist/**.js` files via `tsc` instead of `vite build`. The latter may be preferable, as it could possibly allow us to improve our downstream build times by not repeatedly bundling dependencies such as Monaco.

**Comment by wodeni** [comment]
Closing because in #1225 we stopped bundling `components` as well.
