### ISSUE TITLE
Rethink trios/registries

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#1198]
We currently store a list of trios in a registry file, which is parsed by both the editor and the test suite, with trio-specific omissions for either.

Instead, we could store trios as separate `.json` files, and the editor gallery and test suite have separate registries that point to these files. A local and web-based loader can hydrate these registries with the trio contents.

The trios should contain a human-readable name, the file names, the variation, and optionally the file name of a preview SVG.

- [ ] should we continuously generate the preview svgs? should they still be build artifacts?

**Comment by samestep** [comment]
Does this supersede #1034?

**Comment by samestep** [comment]
> * [ ]  should we continuously generate the preview svgs? should they still be build artifacts?

Yes, isn't this what we already do? https://github.com/penrose/penrose/tree/ci/refs/heads/main

**Comment by maxkrieger** [comment]
@samestep oh yeah I forget why we dont put em in main anymore - im actually in favor of main now bc you can locally situate the preview and the source in the same place

**Comment by joshsunshine** [comment]
I think we should add human readable names to the trios in the registry so we can display those to the gallery viewers. I think we can also remove the human readable names from domain, style, and substance.

**Comment by maxkrieger** [comment]
@joshsunshine what is a human readable trio name if not a concatenation of human readable names of its constituents? 😄  - yes the trio names in the editor right now are not very readable

**Comment by joshsunshine** [comment]
@maxkrieger I think that "concatenation of human readable names of its constituents" will in practice not work. I think people will find it much easier to just name the diagram. One common problem in our current registry is that the domain and style frequently have the same name. I also don't think there is a concatenation scheme that will always be clear. I'd prefer creative freedom so I can't write "Nested sets in simple venn style" and "Caffeine molecule" for those two diagrams, evene though those names don't "match" in terms of their relationship to the constituent parts.

**Comment by joshsunshine** [comment]
@maxkrieger When you say "preview SVGs" do you mean the output of running Penrose on the trio with the selected seed?

**Comment by wodeni** [comment]
On previews: #1261, #1510 (and probably a few others)
On Registry: #1204

**Comment by samestep** [comment]
Also #1393 and #1418.
