### ISSUE TITLE
Better syntax for `Path` construction in Style

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#1218]
Currently `Path` can either be created via the `*FromPoints` functions. These functions take in a list of points (`ad.Pt2`) and return `PathDataV` and are not composable. Ideally, we should have a Style-native syntax for defining `Path`s and hopefully better syntax than SVG for curves.

**Comment by samestep** [comment]
Related: #716

**Comment by wodeni** [comment]
Merging with #716
