### ISSUE TITLE
Remove type polymorphism

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1251]
Many of the parser and compiler code are designed to work with type polymorphism (i.e. with type constructors, type arguments, etc.), but as discussed in #1110 , type polymorphism only has unit tests but no overall tests or end-to-end examples, and the @samestep suggests that "generics just don't work at all currently."

If there is no reasonable use case for type polymorphism, should we just remove it?

**Comment by samestep** [comment]
To clarify, I did say "My impression is ...", since I don't know for sure; can someone confirm?

**Comment by liangyiliang** [comment]
Oops yeah

**Comment by wodeni** [comment]
There were some early attempt at adding collections to Substance (eg https://github.com/penrose/penrose/pull/175). And the compilers have code ported from Haskell in those days. Tangentially related are proposals to add collections in Style selectors: https://github.com/penrose/penrose/issues/769.

Removing unused features is great. Perhaps we should discuss if collections are in our roadmap, and if this old code for generics will be potentially useful.
