### ISSUE TITLE
Style program for Timelines

### ISSUE THREAD

**Issue by joshsunshine** [penrose/penrose#1263]
I think we should build `Domain` and `Style` programs for timelines. These diagrams appear in almost all grant proposals, which allows us to make further inroads into our core academic audience. In addition, these proposals are common in business presentations, white papers, etc. 
Writing a Substance should be as simple as specifying tasks, giving tasks tags, and specifying the begin and end time of each task. 

An example timeline from one of our recent proposals looks like this:
![PenroseSloanTimeline](https://user-images.githubusercontent.com/8795153/214439628-6c388419-0701-4d5b-a4c3-ae7eebfb282e.png)

I think this could be specified in `Substance` as so:
```
TODO: Will fill in later.
```

TODO: Compare to [Mermaid Gantt diagrams](https://mermaid.js.org/syntax/gantt.html)

**Comment by wodeni** [comment]
Tried to make the diagram in mermaid:
```mermaid
gantt
    title Schedule of Penrose Features
    dateFormat  YYYY-MM
    axisFormat %Y-Q%q
    section Project Outputs
    Web IDE           :a1, 2023-01, 2023-07
    Integration with Powerpoint, Canvas, LaTeX, Google Docs, etc.  :2023-07, 2024-12
    Animation and Progressively-built diagrams :2023-08, 2024-08
    Standard Library  :2023-01, 2024-04
    Tutorial Videos   :2024-07, 2025-01
    section Accessibility
    Spatially localize alt text :2023-07, 2024-01
    Language localization: 2023-04, 2023-10
    Color acuity optimization: 2023-10, 2024-10
    Semantics-preserving, layout-optimized zoom: 2024-01, 2025-01
    section Milestones
    Improve compilation :2023-01, 2023-10
    Interactivity :2023-10, 2025-01
    Temporal specification: 2023-07, 2024-01
    Enhanced graphical feature: 2023-01, 2025-01
    Staged optimization: 2023-10, 2025-01
    todayMarker off
```
