### ISSUE TITLE
Name collisions in SVG `Image` import

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#1288]
**Describe the bug**

When there are more than one diagram on the page, imported images might not show up. This is usually caused by name collisions among the imported SVGs. If an imported SVG defines a `<linearGradient id="foo">` and refer to `foo` by `url(#foo)` somewhere else, there must be only one such reference in the entire DOM tree. 

**To Reproduce**

1. Go to https://361060b0.penrose-72l.pages.dev/try/
2. Click on the "Walk on Spheres" example
3. Select `Grid`
4. See the following output

![image](https://user-images.githubusercontent.com/11740102/216257784-d03da57f-9675-4374-9287-a408a0677d38.png)

**Expected behavior**

Spheres should be shaded by the imported image:

![Walk on Spheres - Laplace Estimator](https://user-images.githubusercontent.com/11740102/216257960-910934b9-8d6c-4093-bb62-5ae578389937.png)

**Additional context**
This is a known problem with SVG (e.g. https://github.com/gregberge/svgr/issues/150) and there are some SVG cleaning tools like [svgr](https://github.com/gregberge/svgr). It would be great to experiment with some of them.

**Comment by wodeni** [comment]
#1444 revealed another likely case of this issue, which I bumped into again in #1464. Reopen to investigate.

**Comment by keenancrane** [comment]
> It would be great to experiment with some of them.

Beyond being "great" to experiment with, I've flagged this as a high-priority issue.  Let's fix it now.

In general our SVG support has really suffered regression with some recent PRs.  Correct SVG import is a central feature of our system.  Let's please not sacrifice it merely for the sake of "nice to have" features like the gallery, preview icons, build system niceties, etc.
