### ISSUE TITLE
Check if the system performs differently with `Double` instead of `Float`

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#130]
* Is the change possible?
* Is numerical accuracy/convergence better?
* Are floating-point ops notably faster/slower?

**Comment by hypotext** [comment]
Example: `runpenrose sub/tree.sub sty/venn.sty dsll/setTheory.dsl`

With all Floats, it converges, but with Doubles, it gets to a visually similar-looking state, then blows up at the end (sets get really big and go offscreen or NaN). Not sure why.

**Comment by dormaayan** [comment]
@hypotext Because Haskell

**Comment by hypotext** [comment]
@dormaayan What does that mean??

**Comment by hypotext** [comment]
Resolved with web port
