### ISSUE TITLE
Determinism is broken

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1312]
#1287 broke determinism, as mentioned in https://github.com/penrose/penrose/pull/1294#issuecomment-1424859484.

**Comment by samestep** [comment]
See https://github.com/penrose/penrose/pull/1311#issuecomment-1429046012 for an example of a registry diff that should be empty but isn't.

**Comment by wodeni** [comment]
Re-opening since some of our PRs still have noisy diffs: https://github.com/penrose/penrose/pull/1321
