### ISSUE TITLE
Syntax/semantics doc pages are missing content from wiki

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1314]
Historically we've had a few wiki page documenting syntax/semantics for our three DSLs, and our standard library:

- https://github.com/penrose/penrose/wiki/Language-Specification
- https://github.com/penrose/penrose/wiki/Style-function-library
- https://github.com/penrose/penrose/wiki/Style-shape-library

This documentation was supposed to be brought over to the website in #1116; now we have the following three pages:

- https://penrose.cs.cmu.edu/docs/ref/domain/syntax
- https://penrose.cs.cmu.edu/docs/ref/substance/syntax
- https://penrose.cs.cmu.edu/docs/ref/style/syntax

However, those pages are missing many items from the aforementioned wiki pages, as noted by @keenancrane:

> - strings
> - matrix/vector
> - type annotations
> - custom initialization value
> - math vs. text labels (`has math label` and `has text label`)
> - delete keyword
> - color
> - math functions
> - richer information about a couple shapes (e.g., `Path` and `Circle`)

> Also it’s weird that the page explaining the basic usage of Style is called “Syntax and Semantics” and is listed at the very bottom of the menu:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/8246041/218780249-1506e26d-f34e-428d-8a46-3793bfde67a5.png">

We need to move all this content from the wiki into the website. (Also, note that the above list is not necessarily exhaustive.)

**Comment by liangyiliang** [comment]
Apparently custom initialization values don't exist anymore ...
