### ISSUE TITLE
Line-wrapping in error panes

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1356]
Here is an example error message.
![image](https://user-images.githubusercontent.com/16521252/235779491-6ff8fe6b-eef6-4b33-9515-a9c811eef292.png)

The message is too long that we need to scroll horizontally.

We should have line-wrapping.

**Comment by samestep** [comment]
Could you split this into two issues so that #1357 can close this one?

**Comment by liangyiliang** [comment]
> Could you split this into two issues so that #1357 can close this one?

Done
