### ISSUE TITLE
Figure out what fraction of papers on arXiv have figures

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#138]
Right now, we are motivating Penrose using an old, informally-gathered statistic: 

> For example, only a third of the newest fifty papers on arXiv have figures.

It would be very helpful if we properly calculated this statistic. Keenan comments:

> I’ve always found this statement about the arXiv stats misleading: one-third actually sounds like an awful lot.  But I would guess that (i) most of these figures are not the kind of interesting/deep/illuminating figures you’re really gunning for, and (ii) if you look at different stats like number of figures per page, the situation is more grim. But now that I’m thinking about this: why don’t we scrape some more thorough stats on images in arXiv?  I suspect we’d discover some very interesting things, and the dataset is large. 

See 9/26 email thread for more.

**Comment by dormaayan** [comment]
Yes, this is really interesting to explore this as well, especially now when we get some indications from the interviews that people feel they can do better while visualizing. We can send a survey to the authors of the newest 50 papers on Arxiv and ask them

**Comment by vsoch** [comment]
+1! @dormaayan and I talked about this today and I think we are talking about it in more detail for our meeting next week.

**Comment by maxkrieger** [comment]
I assume this is resolved?

**Comment by wodeni** [comment]
I think so. Closing now.
