### ISSUE TITLE
Would penrose be able to create venn diagrams with overlaps between larger numbers of sets? 

### ISSUE THREAD

**Issue by zfrenchee** [penrose/penrose#139]
I'm interested in visualizing the overlaps between 4+ sets with a venn diagram. Supposing every set overlaps every other set, how far would penrose's constraint solver take me? 4 sets? 5 sets? More?

Many thanks!

**Comment by hypotext** [comment]
Thanks for your interest! We currently don't have a set theory style that supports n-ary set intersections but would like to do so in the future.
