### ISSUE TITLE
Support sequences in Substance

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1407]
We have quite a few examples of Substance programs that create long lists of indexed variables by hand.  For instance, in the `random-sampling` example we have programs of the form
```
Interval I
Point p1 = sampleInterval( I )
Point p2 = sampleInterval( I )
Point p3 = sampleInterval( I )
Point p4 = sampleInterval( I )
Point p5 = sampleInterval( I )
...
```

Although it's tempting to introduce an "array" or "list" construct (a la most programming languages), the more natural choice for a language that is meant to resemble mathematical prose is a [sequence](https://en.wikipedia.org/wiki/Sequence).  Notation for sequences, which is remarkably standard across different areas of mathematics, is both flexible and concise:

<img width="512" alt="image" src="https://github.com/penrose/penrose/assets/3604525/d4af207f-5614-4edc-9d35-00c55e282c45">

## Sequence declarations

In Substance, we might declare a sequence like this:

```
Point p_1, ..., p_10
```

This declaration would be equivalent to declaring ten variables of type `Point`, indexed from 1 to 10 (inclusive).  Internally (i.e., in our implementation), this declaration can simply be expanded to a list of `Point` variables (as in the original example above).

In general, we would adopt the following conventions:

- The character `_` cannot be used in an identifier (which seems uncommon anyway).
- A sequence declaration takes the form `Type id_i0, ..., id_iN`, where `id` is a valid identifier and both `i0`, `iN` are integers such that `i0 < iN` (not necessarily positive, or even signed).
- Any element of a sequence can be referenced as `id_k`, where `k` is an index between `i0` and `iN` (inclusive).
- Referencing an element outside the sequence is no different from referencing any other undeclared variable.

For instance, one can now write

```
p_4 = sampleInterval( I )
```

even though the identifier `p_4` was never explicitly declared (only the sequence it comes from).

One feature of sequences that is quite different from arrays is that the indexing scheme is more flexible.  For instance, in most programming languages indices are universally fixed to either a 0-based or 1-based convention.  But it's not at all uncommon in mathematics to start indexing at other numbers, e.g., -1.  The proposed scheme naturally allows this kind of indexing, e.g., a declaration

```
SimplicialSet K_-1, ..., K_3 -- elements of a tetrahedral mesh
```

would allow one to address `K_-1`.

## Sequence iteration

In order for sequences to be useful, we also need some way to iterate over them.  Again, though it's tempting to use conventions from programming languages, we should push ourselves to think about syntax that resembles mathematics.  Here, the notation `...` continues to be ubiquitous:

<img width="727" alt="image" src="https://github.com/penrose/penrose/assets/3604525/cbb537d8-dbae-4f4a-9125-a9bfd2fcb290">

Likewise, a reasonable approach in Substance would be something like

```
p_k = sampleInterval( I ), for k = 1, ..., 10
```

Like the sequence declaration, this expression ultimately just expands into a list of ordinary Substance statements

```
p_1 = sampleInterval( I )
p_2 = sampleInterval( I )
p_3 = sampleInterval( I )
...
```

Note that unlike a map/reduce paradigm, we are not required to iterate over the entire sequence.  For instance, even if the declaration is `Point p_1, ..., p_100`, it's perfectly fine to write `p_k = sampleInterval( I ), for i = 1, ..., 10` (and then perhaps `p_k = sampleDisk( D ), for k = 11, ..., 20`, etc.).

## Implementation

A basic implementation of sequences shouldn't be too difficult, as long as we stick with constructions that basically amount to list expansion.  Of course, there may be other features we want to support down the line.  But as usual, I would advocate for: get a basic version, don't sweat the design too much, see how we like using it, and iterate.

**Comment by keenancrane** [comment]
@wodeni notes that we don't actually need to forbid `_` from identifiers—the underscore need only have a special meaning in the context of sequence declarations and applications.

In other words, the parser will try to match the pattern

```
Type identifier_n, ..., identifier_m
```

where `n` and `m` are integers, and both prefixes have the same `identifier`, which is itself allowed to include underscores.  For instance,

`Element g_0_1, ..., g_0_10`

is a valid declaration of a sequence.

**Comment by keenancrane** [comment]
Also as discussed with @liangyiliang, sequences in Substance would have a nice interaction with the new `collect` mechanism in Style.  For instance, the curve examples @jiriminarcik has been writing recently could instead be done by (i) declaring a sequence of points in Substance, and (ii) collecting these points in a Style rule to define the objective (e.g., total length, total curvature, etc.).

**Comment by keenancrane** [comment]
In fleshing out this design, we may also want to consider that natural mathematical notation often also calls for superscripts—or even mixes of superscripts/subscripts:

<img width="653" alt="image" src="https://github.com/penrose/penrose/assets/3604525/03396f71-0c98-4daa-83df-1d39fd454e2a">

We of course don't have to support everything, everywhere, all at once, but may want to at least support some additional options (e.g., a sequence indexed by subscripts only, _or_ a sequence indexed by superscripts only).

A common plain-text way of denoting superscripts is using the carat, e.g.,

> x^1, …, x^k

**Comment by keenancrane** [comment]
A common use case for multi-indices is any kind of diagram modeled around a grid.  Would certainly be nice to just say something like

```
Type t_0^0, ..., t_n^m
```

to get an `n` by `m` array of variables.  As with a linear sequence, one would still retain the ability to use 0- or 1-based indexing at will, e.g.,

```
Type t_1^1, ..., t_n^m
```

or even

```
Type t_0^1, ..., t_n^m
```

**Comment by keenancrane** [comment]
From an implementation perspective, one important question is whether we should allow underscores in identifier names.  Allowing arbitrary use of underscores seems quite challenging to support, since it effectively means the grammar is no longer context-free.

One reasonable argument for _disallowing_ underscores in identifiers—independent of the sequence discussion—is that **underscores are not used in variable names in standard mathematical prose**.  You do very occasionally find, e.g., computer science papers where snake-case variables are mixed with mathematical expressions (typically in pseudocode listings).  But such use cases are by far in the minority.

**Comment by keenancrane** [comment]
Another thing worth mulling over before we pull the trigger on a design for sequences is whether we're really reaching for the concept of an _index set_: https://en.m.wikipedia.org/wiki/Indexed_family

An index set is exactly what it sounds like: a set I of indices. Formally, the indexing operator is a map from I into a value set X, i.e., an indexed variable f is just a map from I to X.

More concretely, your index set might be:

- a contiguous set of integers, like I = {1,2,3,4,5} or I = {-1,0,1}
- a non-contiguous set like even integers I = {0,2,4,6,8,10} or even, say, Fibonacci numbers I = {1,2,3,5,8,13,21}
- a Cartesian product like I = {1,2} x {1,2} = {(1,1),(1,2),(2,1),(2,2)}, or {-1,0,1} x {a,b}
- A triangular set like I = { (i,j) | 0 < i < 10, j < i }
- etc.

For each of the examples above you can find mathematical contexts where this index set shows up naturally. Moreover, in many cases you _need_ to talk about index sets in this generality. E.g., to assign a unique index to each edge in an undirected complete graph, you really need a triangular set rather than a Cartesian product.

So, a forward-looking and future-proof design for sequences might be built with the index set perspective in mind.

Generally, an indexed variable declaration could look like

```
Point x_{i}, i in I
```

where I is some kind of index set supported by the language. For instance, an ordinary linear sequence would be

```
Point x_{i}, i in [1,3]
```

whereas a variable indexed by odd numbers might be

```
Point x_{i}, i in Odd(1,9)
```

or similarly for Fibonacci, etc. The former can still be expanded to

```
Point x_1, x_2, x_3
```

and the latter to

```
Point x_1, x_3, x_5, x_7, x_9
```

For multiple indices, like a Cartesian product, we would need some kind of syntax like

```
Point x_{i,j} for i,j in [0,1]x[0,1]
```

which expands to

```
Point x_0_0, x_0_1, x_1_0, x_1_1
```

(or something similar; I'm not trying to propose a precise syntax here).

Similarly,

```
Point x_{i,j} for i,j in Triangular(a,b,c) 
```

would expand to indices i between a and b, and indices j between c and i. Etc.

From an implementation perspective, this would seem to fall fairly easily into the same "expansion" paradigm as the current sequence proposal/prototype: the compiler has some fixed menu of index sets it knows about; when one of those sets is identified it's (i) expanded into an explicit list of indices and then (ii) one variable per index is declared, by appending the index to the variable name.

Additional index sets can be added to the language first by the developers, and maybe (in some distant future) by programmers, in the Domain schema.

Again, maybe not needed in the immediate term, but it feels good to start from a design & implementation that at least allows the semantic scope to expand as Penrose matures.

**Comment by wodeni** [comment]
Still need to learn Lean, but can probably start here https://leanprover-community.github.io/mathlib_docs/data/list/range.html?

**Comment by keenancrane** [comment]
> Still need to learn Lean, but can probably start here https://leanprover-community.github.io/mathlib_docs/data/list/range.html?

Cool. If I'm reading this right, seems this page discusses only support for linear sequences, with some limited flexibility about how those sequences are defined (e.g., 1 up to n versus n down to 1).

**Comment by keenancrane** [comment]
A related issue, which expands on this one, is #1591.
