### ISSUE TITLE
React Frontend

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#141]
Implementation of end-user frontend in React.js.

- [x] Rendering of shapes
  - [x] Circle
  - [x] Rectangle (?)
  - [x] BezierCurves (tricky)
  - [x] Document how to add shapes
  - [x] TODO: add all other shapes
- [x] Entity Interactions
  - [x] Layering/ordering modification (#77)
  - [x] drag update
    - [x] Friendlier bounding box for labels (0 opacity bounding box?)
      - [x] fix wrong bboxes for the first frame
    - [x] HOC for draggability
  - [x] button `onclick` events: 
    - [x] resample
    - [x] step
    - [x] autostep on/off
- [x] Rendering of labels (with `tex2svg` or equiv.)
- [x] SVG Animations
   - [x] Test on a large enough (10+ shapes) scene and see if rendering is still smooth
- [x] [Debug logging](https://levelup.gitconnected.com/step-up-your-console-messaging-game-in-your-react-app-42eee17659ec)
- [x] Code Editing
   - [x] basic textarea
   - [x] embeded renderer in IDE
   - [x] ace integration
- [x] WebSocket routing: find a scalable way to manage multiple concurrent ws connections and distribute ports
- [x] Debug rendering: bounding boxes, bounding circles, and centers (and #25)
- [x] Static typing of the rendering model (matches the backend's)?
- [ ] Nimo: write a wiki page on server finite state machine, packet formats, and logger API
- [ ] Component-based tests?

**Comment by wodeni** [comment]
Related issue #109. Specifically, [this comment](https://github.com/penrose/penrose/issues/109#issuecomment-404592946) is the most relevant, where I proposed to have shape definition and rendering code in one place. We should revisit this issue and keep this vision in mind when designing the front-end types for shapes. Possible topics:

- Should we rewrite the type again if it's already written in the backend?
- Is there an automatic way to generate the front-end types given info from the backend?
- How do programmatically generated shapes fit into our framework (related issue: #136)?

@maxkrieger feel free to take a look at #109 and #136 and add to the list!

**Comment by wodeni** [comment]
We were able to recreate the following scene today with `autostep` enabled
`runpenrose sub/twosets.sub sty/venn_comp.sty dsll/setTheory.dsl`
![image 1](https://user-images.githubusercontent.com/11740102/47375064-6f57fb00-d6bd-11e8-9411-10927f86bf0a.png)

**Comment by maxkrieger** [comment]
We started working on the IDE and sent a substance program to the server. Some bugs still present.

![image](https://user-images.githubusercontent.com/2660634/47727969-d2084400-dc33-11e8-8fc9-2b628f13620b.png)

**Comment by maxkrieger** [comment]
Some additional remaining issues:
**Negative radii**: when you send updated shapes back to the server for a second time and then optimize, the server sends negative radii. To reproduce, recompile a substance program in the IDE and then optimize it, then check js console.

**Removing labels in the same session**: If you remove a set (like `Set B`) and then press recompile in the IDE, the server crashes because of some kind of state issue.

**Comment by maxkrieger** [comment]
For some reason in the IDE view, the initial render is different than the standalone react-renderer version. Might be conflicting stylesheets?

**Comment by wodeni** [comment]
> For some reason in the IDE view, the initial render is different than the standalone react-renderer version. Might be conflicting stylesheets?

[ ] The server might have taken an extra step at the beginning.

**Comment by maxkrieger** [comment]
Bug: when you autostep and then resample, the server keeps receiving the update packet.

**Comment by maxkrieger** [comment]
BUG: [ ] The drag events are not "responsive" - they are not proportional to the scaling of the svg. Need to divide by true svg element width or something.

**Comment by wodeni** [comment]
First editor experience:

![penrose-ide](https://user-images.githubusercontent.com/11740102/48238496-35634600-e399-11e8-8fff-56027011f5b3.gif)

**Comment by hypotext** [comment]
Feature requests (will update comment over time)

- [ ] Server catches Sub/Sty errors and recovers instead of halting
- [ ] Substance program persists across refreshes
- [ ] IDE starts with "AutoLabel All" typed in
- [ ] "Build" button becomes "build and autostep" (I almost never want to build without seeing the results)
- [ ] Keybindings for IDE, mostly for "build and autostep." cmd+enter would work, as Max suggested
- [ ] Debug mode in IDE including "step" button, graph of various optimization quantities over time
