### ISSUE TITLE
Extend Style parser to accept newlines in selectors

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#142]
This would improve readability of selectors, especially ones with long `where` and `with` clauses. 

For example, if I add a newline [here](https://github.com/penrose/penrose/blob/real-analysis/src/real-analysis-domain/parallel-reals2.sty#L173), in this long selector:

```
Function h; Function g; Function f
where h := compose(g, f); h := CreateFunction(A, R); g := CreateFunction(B, R); f := CreateFunction(A, R)
with Interval A, B; Reals R { ... }
```

I get the following error:

```
penrose: real-analysis-domain/parallel-reals2.sty:174:7:
unexpected 'h'
expecting "as", "with", or '{'

CallStack (from HasCallStack):
  error, called at src/Style.hs:190:17 in main:Style
CallStack (from -prof):
  Style.parseStyle (src/Style.hs:(188,1)-(191,35))
  ShadowMain.shadowMain (src/ShadowMain.hs:(31,1)-(134,45))
```

**Comment by wodeni** [comment]
@hypotext  Which files do I have to run to repro this?

**Comment by hypotext** [comment]
@wodeni `runpenrose real-analysis-domain/interval-par.sub real-analysis-domain/parallel-reals2.sty real-analysis-domain/real-analysis.dsl` on branch `real-analysis`

I didn't test very extensively, so I'm not sure if it's a problem with this particular selector or with selectors in general.

**Comment by wodeni** [comment]
I implemented this and tried running the above command. Here is the output:

![image](https://user-images.githubusercontent.com/11740102/48157803-aa9e2080-e29e-11e8-8c27-e123de0b1bb0.png)

Style warnings:
```
Warning: Sub obj 'R''s field 'yval2' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2_text' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2_labelFn' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'yval2' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2_text' is overridden, but was not declared an override
Warning: Sub obj 'R''s field 'shape2_labelFn' is overridden, but was not declared an override

```

**Comment by hypotext** [comment]
Looks great, thanks for the quick fix @wodeni. The Style warnings are not a problem.

**Comment by wodeni** [comment]
:D fastest record made for closing an issue
