### ISSUE TITLE
SVG renderer should explicitly write "none" fields

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1421]
For paths where `fillStyle` is set to `none()` in Style (which is the default for several shapes), the renderer currently omits an explicit `fill` tag.  This leaves the default fill open to interpretation by other programs.  For instance, a diagram that shows up like this in Chrome:

<img width="644" alt="image" src="https://github.com/penrose/penrose/assets/3604525/cd70cf1a-76a9-4748-8043-a39d4fdd9940">

Shows up instead like this in Illustrator, which assumes a default fill color of black (and draws a hairline fill for any stroke):

<img width="573" alt="image" src="https://github.com/penrose/penrose/assets/3604525/4f652857-1419-4078-9ad6-8eace596ee8e">

The solution is simply to render such shapes with an explicit `fill="none"` attribute.

**Comment by wodeni** [comment]
Did you mean `fillColor` instead of `fillStyle`? `fillColor: none()` should be translated to `fill="none"` in SVG. Which property is illustrator looking at to set the default black color?

**Comment by wodeni** [comment]
Did some refactoring in https://github.com/penrose/penrose/pull/1423 to reuse our existing functions for handling fill and stroke. The diffs didn't show any actual difference: `fill="none"` is always included in `Path`s. @keenancrane let me know if you know what broke illustrator.

**Comment by keenancrane** [comment]
I tracked this issue down in more detail and it seems to happen only when the shape is `Line` (not `Path` or `Polyline`).  In this case the `Line` shape gets rendered by Penrose as a `<path>` SVG tag.  But unlike the `<path>` tag rendered for the `Path` shape, the tag for a `Line` doesn't specify a fill.  Hence, a client has to decide what the fill should be—in the case of Illustrator it decides that an unspecified fill should be **black** rather than **none.**

Here's a minimal example reproducing the issue.

**.domain, .substance**: empty

**.style**
```
canvas {
    width = 640
    height = 480
}

global {
    shape testPath = Path {
        d: pathFromPoints("open", [ 200*diskRandom(), 200*diskRandom(), 200*diskRandom() ])
        strokeWidth: 5
        strokeColor: #77b8
        ensureOnCanvas: false
    }

    shape testLine = Line {
        start: 200*diskRandom()
        end: 200*diskRandom()
        strokeWidth: 5
        strokeColor: #f608
        ensureOnCanvas: false
    }

    shape testPolyline = Polyline {
        points:  [ 200*diskRandom(), 200*diskRandom(), 200*diskRandom() ]
        strokeWidth: 5
        strokeColor: #0a08
        ensureOnCanvas: false
    }
}
```

<img width="742" alt="image" src="https://github.com/penrose/penrose/assets/3604525/a8d6c4a3-8157-4194-b25a-d0a3eac0dfef">
