### ISSUE TITLE
`Equation` font size is wrong / canvas size dependent

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1438]
![image](https://github.com/penrose/penrose/assets/3604525/00b2f4e3-165b-4733-a584-5f42b0a5a079)

`Equation` shapes (rendered via MathJax) do not yield the size requested in the `fontSize` field—the rendered size depends on the `canvas` size in the Style program.  In contrast, `Text` shapes always get rendered at the proper size, independent of canvas dimensions.

Here's a complete example showing the issue (the Domain schema and Substance program are empty):
```
canvas {
    width = 10
    height = 8
}

global {
    shape plainText = Text {
        string: "A"
        fillColor: #0a0
        fontSize: "3px"
        fontFamily: "MathJax_Math"
    }
    shape plainTextLabel = Text {
        string: "Text"
        center: plainText.center - (0,1.75)
        fontSize: "1px"
        fillColor: plainText.fillColor
        fontFamily: "monospace"
    }

    shape mathText = Equation {
        string: "A"
        fillColor: #00a
        fontSize: "3px"
    }
    shape mathTextLabel = Text {
        string: "Equation"
        center: mathText.center - (0,3)
        fontSize: "1px"
        fillColor: mathText.fillColor
        fontFamily: "monospace"
    }

    ensure disjoint( mathText, plainText )
}
```

**Comment by wodeni** [comment]
To repro this, I also need to download the `MathJax_Math` font and install it locally:
https://imathas.valenciacollege.edu/mathjax/fonts/HTML-CSS/TeX/otf/
