### ISSUE TITLE
Problem Generation: Penrose-Based Exercises

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#144]
For education contexts, it could be practical to synthesize substance programs that function as an exercise for a student to interpret or "reverse engineer".

There are several problem types, the first of interest being a "free-response":

![free response 1](https://user-images.githubusercontent.com/2660634/48975467-cb0c0000-f03e-11e8-996d-dbe5289c91ca.png)

![free response 2](https://user-images.githubusercontent.com/2660634/48975471-e1b25700-f03e-11e8-8fd5-2632a1830720.png)

Measuring the correctness of the response is itself a research question, and we hypothesize that the best way will be to compare the response substance program's energy function with the "canonical" one's.

There are other "Duolingo-like" response types, for instance, a multiple selection:

![image](https://user-images.githubusercontent.com/2660634/48975488-3229b480-f03f-11e8-90c1-cded6674e6c5.png)

And a "chip bar":

![image](https://user-images.githubusercontent.com/2660634/48975491-453c8480-f03f-11e8-8609-875dd989cc68.png)

There are several components to the system:

- [ ] Constraint-based synthesis of problems (Related: #107)
- [ ] Measuring the correctness of a substance response
- [ ] UIs for all problem types

**Comment by maxkrieger** [comment]
should this remain an issue @wodeni? :P

**Comment by wodeni** [comment]
Yes please 👀

**Comment by wodeni** [comment]
I made some progress on this project over the summer with @hsharriman. This is too high-level for an issue, though. Refer to #640 #551 for some examples of the most recent additions!
