### ISSUE TITLE
Compilation ultra-slow even when code is commented out (!)

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1454]
Here's a really messed up example:

A program (attached below) that compiles ultra slow, but if a block of **commented-out code** is deleted, it suddenly compiles really fast.

My guess is that there's some uncaught error in the compilation process.  But it's strange that the commented code has _any_ effect at all on the compilation process.  (Shouldn't it just be preprocessed out of existence?)

This process hints at something possibly deeper broken in the compiler.  The reason I even found this bug is that compilation suddenly became suuuuuupper slow without any major change being made.  Then I tried to comment things out to simplify the code—and noticed it wasn't until I _deleted_ the commented-out code that things became fast again…

[slow-compile-comments.domain.txt](https://github.com/penrose/penrose/files/11652926/slow-compile-comments.domain.txt)
[slow-compile-comments.style.txt](https://github.com/penrose/penrose/files/11652927/slow-compile-comments.style.txt)
[slow-compile-comments.substance.txt](https://github.com/penrose/penrose/files/11652928/slow-compile-comments.substance.txt)

**Comment by samestep** [comment]
It's hard to view these files on mobile; could you put them directly in the issue as code blocks instead? If you're worried that they're too big and would cause people to scroll, you can use HTML `<details>` like this:

````
<details>
<summary><code>foo.txt</code></summary>

```
Hello, world!
I am a long file.
```
</details>
````

<details>
<summary><code>foo.txt</code></summary>

```
Hello, world!
I am a long file.
```
</details>
