### ISSUE TITLE
SVG load fails after edit in web IDE

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1463]
On the IDE deployed at https://penrose.cs.cmu.edu/try/, SVGs are initially properly loaded for examples.  E.g., the lightbulb in this example:

<img width="893" alt="image" src="https://github.com/penrose/penrose/assets/3604525/5605d0b7-04d0-4cf9-8062-9e095a33cb4d">

However, if the code is edited and recompiled, the image reference breaks.  E.g., here I just change one of the labels in the Substance program:

<img width="903" alt="image" src="https://github.com/penrose/penrose/assets/3604525/055e2dba-2344-4591-99c2-723bb0f1e76f">

(Note that the camera is drawn directly in the Style program, rather than imported from SVG, hence doesn't break).

IIRC we had this behavior in the past (and fixed it), but I can't find the associated issue or PR.

My best guess is that it has to do with #1444, since this PR also added back in preview icons.  However, imported SVGs also don't show up properly in these icons—e.g., the green balls here should be shaded:

<img width="303" alt="image" src="https://github.com/penrose/penrose/assets/3604525/558b885b-7f87-4603-9d0a-e2982773f670">

**Comment by samestep** [comment]
This is probably a regression caused by #1393.
