### ISSUE TITLE
bug: Clipping renders wrong for imported images and/or gradients

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1494]
![image](https://github.com/penrose/penrose/assets/3604525/a3ae8f3d-36ee-44c4-a96b-1ad77fc16a28)

An example is shown above, where the gray shaded balls (which come from an imported SVG) are supposed to be clipped by the grey polygon, but get clipped at the wrong location.  The green balls (which are just `Circle` shapes) are properly clipped, within the same group.

It looks like what may be happening is just that there's a transform that's not properly accounted for, i.e., the clipping path is for some reason translated by some amount before clipping.

Here's the relevant snippet, from `walk-on-spheres.style` (in `examples/`):
```
   shape St.ball = Circle {
      center: p.location
      r: R
      fillColor: rgba( f[0], f[1], f[2], 1 )
      strokeColor: rgba( s[0], s[1], s[2], 1 )
      strokeWidth: Global.sphereStrokeWidth
      ensureOnCanvas: false
      opacity: .35
   }

   shape St.shading = Image {
      href: "ball-shading.svg"
      center: St.ball.center
      width: 2*St.ball.r
      height: 2*St.ball.r
      ensureOnCanvas: false
   }

   layer St.shading above D.geometry
   layer St.ball above St.shading

   shape St.domainGeometry = Polygon {
      points: D.geometry.points
      fillColor: none()
      ensureOnCanvas: false
   }
   -- this group should ideally also include St.shading, but
   -- there appears to be a bug with clipping imported images
   -- (or perhaps gradients)
   shape St.G = Group {
      shapes: [St.ball] -- [St.ball,St.shading]
      clipPath: clip(St.domainGeometry)
      ensureOnCanvas: false
   }
```

The corresponding Substance program is `WalkOnStars.substance`.

**Comment by liangyiliang** [comment]
Weird, looking at this now

**Comment by liangyiliang** [comment]
I think I know what's going on here.

The `Image` shape is rendered as follows:
```svg
<g
    transform="  ... transformation necessary to make sure this image has the right center, width, height ... " 
    clip-path="...">

  <svg> ... imported svg ...</svg>

</g>
```

I think what's going on is that `clipPath` is performed on the pre-transformed coordinate, not the post-transformed coordinate.

The solution I can think of is to wrap this in another level of `<g>` and have the `clipPath` be applied on the outer-most level.
```svg
<g clip-path = "...">
  <g transform=" ... transformation necessary to make sure this image has the right center, width, height ...">
    <svg> ... imported svg ... </svg>
  </g>
</g>
```

This forces the clipPath to be applied at the post-transformed coordinates.

I will patch this.
