### ISSUE TITLE
Language Server (Syntax and Autocompletion) for Substance, Style, and Element programs

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#151]
Extending #19, a [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) implementation for the three languages would make editing a much more ergonomic experience.

**Comment by wodeni** [comment]
#210 adds support for semantic syntax highlighting and basic autocompletion of Substance to the IDE. Closing the issue for now. Consider reopening if we decide to enable Style and Element editing in the IDE.
