### ISSUE TITLE
Question: How do I know what domain files go together?

### ISSUE THREAD

**Issue by vsoch** [penrose/penrose#153]
Given a folder of style (*.sty) domain specific language (*.dsl) and substance (*.sub) files, how do I know which ones can go together without triggering an error? For example, this folder of files:

```bash
$ ls ../../penrose/src/domains/real-analysis/
deconstructors-example.sub  functions-intervals.sub  parallel-reals.sty  real-analysis.sty  test-new-sub.sty
function-interval-comp.sub  interval.sub             real-analysis.dsl   reals.sub
``` 
I only found a working set via trial and error. Is there documentation, a naming convention, or something else? I'm designing a single domain repo, and I would want to represent this. Thanks!

**Comment by hypotext** [comment]
That's something we should document for sure (either in the files or elsewhere). So far, the working paths are documented on the wiki pages for the various domains (under "Domains" in the sidebar). https://github.com/penrose/penrose/wiki

**Comment by vsoch** [comment]
ah perfect! That's all the information that I need. I'll make a spot in a plugin repository for files under development (that aren't served by the plugin repository but might be actively worked on.) Thanks for the speedy response, closing issue.
