### ISSUE TITLE
Autostepping after resampling seems to break server

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#154]
Repro: 
* on branch `end-user-real-analysis`
* commit 66c498e
* command `runpenrose real-analysis-domain/point-perp.sub real-analysis-domain/real-analysis.sty real-analysis-domain/real-analysis.dsl`
* in IDE, turn on autostep until it converges. (You can leave autostep on or turn it off before hitting "resample"; it doesn't seem to make a difference)
* then hit "resample"
* it should resample and step to convergence on the new sample. Instead, it seems to freeze, and I get this error on the Haskell server: "Invalid command. Returning to wait for label update."

**Comment by maxkrieger** [comment]
@wodeni this is several bugs in action, I'm pretty sure. We didn't resolve the fact that the server "forgets" the label dimensions on resample. There's also weird resample behavior that is documented here https://github.com/penrose/penrose/issues/141#issuecomment-438462415

**Comment by wodeni** [comment]
We pushed a fix to this in 9ea002a and tested with `runpenrose real-analysis-domain/point-perp.sub real-analysis-domain/real-analysis.sty real-analysis-domain/real-analysis.dsl`. Closing this issue now
