### ISSUE TITLE
bug: two <penrose> tags in Penrose-exported SVGs

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1586]
**Describe the bug**

Here is the SVG code of a Penrose-exported diagram:

![image](https://github.com/penrose/penrose/assets/16521252/6cbc52af-ba42-42d1-b041-71060f92e906)

As seen, the code contains two `<penrose>` blocks. The first one only contains the cropped view box. The second one contains the same cropped view box, as well as the source code information.

**Comment by wodeni** [comment]
> Oh that's not great haha; how hard is this to fix?

It's a one-liner :P
