### ISSUE TITLE
Reduce user burden and boilerplate

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#16]
* Reduce number of changes needed to add a new object: replace Floats with polymorphism and automatically derive all the typeclasses (Located, etc.).
* Reduce number of changes needed to add a new objective function or computation (e.g. registering its type, adding the function name to the dictionary). This can be done by pre-generating the registration code before the Penrose system is compiled.
* Reduce number of changes needed to add a new computation: generate or remove `computeOn` so people don't have to implement typechecking.

Give examples of how to add/modify new objects, functions, computations.

A lot of these can be done using Template Haskell's quoting and reification features: https://wiki.haskell.org/A_practical_Template_Haskell_Tutorial#Reification

**Comment by wodeni** [comment]
For everyone's convenience, pasting the necessary steps to add an geometry here:

You can roughly see how much work it takes to add one primitive to the system:
- Boilerplate code in `Shape.hs`
  - Normal type definition for Gloss 
  - Polymorphic type definition for autodiff
- `zeroGrad` and `addGrad`
- Front-end rendering code
- Add syntax and type in `Style.hs`
- `init[geometry]` functions
- If needed, `default[geometry]` functions
- `[geometry]pack/unpack` functions

**Comment by wodeni** [comment]
Related PR: #110 #99 
All items in the original list are solved in a reasonably general manner now.
