### ISSUE TITLE
WebAssembly could not allocate memory

### ISSUE THREAD

**Issue by Johnicholas** [penrose/penrose#1613]
When I press "Compile" (I get no feedback and) the JS console says:

index-2e8f712a.js:247 Uncaught (in promise) RangeError: WebAssembly.Memory(): could not allocate memory
    at JU (index-2e8f712a.js:247:22151)
    at ZOe (index-2e8f712a.js:247:23682)
    at lce (index-2e8f712a.js:308:3980)
    at index-2e8f712a.js:488:3114
    at index-2e8f712a.js:488:3288
    at Nz (index-2e8f712a.js:8:24422)
    at hy (index-2e8f712a.js:8:42718)
    at dct (index-2e8f712a.js:8:41536)
    at o9 (index-2e8f712a.js:8:40566)
    at e9e (index-2e8f712a.js:8:37133)

Domain:

type Node
type Edge

constructor MakeEdge(Node a, Node b) -> Edge

Substance:

Node b010
Node b032
Node b131
Node b031
Node b130
Node b012
Node b111
Node b133
Node a120
Node b011
Node b033
Node b110
Node b132
Node a121
Node b030
Node b113
Node a122
Node a100
Node b013
Node b112
Node a123
Node a101
Node a102
Node a103
Node b021
Node b120
Node b020
Node a130
Node b023
Node b122
Node a131
Node b001
Node b100
Node b022
Node b121
Node a110
Node a132
Node b000
Node a111
Node a133
Node b003
Node b102
Node b123
Node a112
Node b002
Node b101
Node a113
Node b103
Edge e0 := MakeEdge(b010, b000)
Edge e1 := MakeEdge(b032, b022)
Edge e2 := MakeEdge(b131, b121)
Edge e3 := MakeEdge(b031, b021)
Edge e4 := MakeEdge(b130, b120)
Edge e5 := MakeEdge(b012, b002)
Edge e6 := MakeEdge(b111, b101)
Edge e7 := MakeEdge(b133, b123)
Edge e8 := MakeEdge(a120, a110)
Edge e9 := MakeEdge(b011, b001)
Edge e10 := MakeEdge(b033, b023)
Edge e11 := MakeEdge(b110, b100)
Edge e12 := MakeEdge(b132, b122)
Edge e13 := MakeEdge(a121, a111)
Edge e14 := MakeEdge(b030, b020)
Edge e15 := MakeEdge(b113, b103)
Edge e16 := MakeEdge(a122, a112)
Edge e17 := MakeEdge(b013, b003)
Edge e18 := MakeEdge(b112, b102)
Edge e19 := MakeEdge(a123, a113)
Edge e20 := MakeEdge(b021, b011)
Edge e21 := MakeEdge(b120, b110)
Edge e22 := MakeEdge(b020, b010)
Edge e23 := MakeEdge(a130, a120)
Edge e24 := MakeEdge(b023, b013)
Edge e25 := MakeEdge(b122, b112)
Edge e26 := MakeEdge(a131, a121)
Edge e27 := MakeEdge(b001, b131)
Edge e28 := MakeEdge(b100, a130)
Edge e29 := MakeEdge(b022, b012)
Edge e30 := MakeEdge(b121, b111)
Edge e31 := MakeEdge(a110, a100)
Edge e32 := MakeEdge(a132, a122)
Edge e33 := MakeEdge(b000, b130)
Edge e34 := MakeEdge(a111, a101)
Edge e35 := MakeEdge(a133, a123)
Edge e36 := MakeEdge(b003, b133)
Edge e37 := MakeEdge(b102, a132)
Edge e38 := MakeEdge(b123, b113)
Edge e39 := MakeEdge(a112, a102)
Edge e40 := MakeEdge(b002, b132)
Edge e41 := MakeEdge(b101, a131)
Edge e42 := MakeEdge(a113, a103)
Edge e43 := MakeEdge(b103, a133)
Edge e44 := MakeEdge(b131, b130)
Edge e46 := MakeEdge(b032, b031)
Edge e47 := MakeEdge(b130, b033)
Edge e48 := MakeEdge(b031, b030)
Edge e49 := MakeEdge(b111, b110)
Edge e50 := MakeEdge(b133, b132)
Edge e51 := MakeEdge(a120, b123)
Edge e52 := MakeEdge(b012, b011)
Edge e53 := MakeEdge(a121, a120)
Edge e54 := MakeEdge(b132, b131)
Edge e55 := MakeEdge(b110, b013)
Edge e56 := MakeEdge(b011, b010)
Edge e57 := MakeEdge(b033, b032)
Edge e59 := MakeEdge(a122, a121)
Edge e60 := MakeEdge(b113, b112)
Edge e61 := MakeEdge(a100, b103)
Edge e62 := MakeEdge(a101, a100)
Edge e63 := MakeEdge(a123, a122)
Edge e64 := MakeEdge(b112, b111)
Edge e65 := MakeEdge(b013, b012)
Edge e66 := MakeEdge(a102, a101)
Edge e67 := MakeEdge(a103, a102)
Edge e68 := MakeEdge(b120, b023)
Edge e69 := MakeEdge(b021, b020)
Edge e70 := MakeEdge(a130, b133)
Edge e72 := MakeEdge(a131, a130)
Edge e73 := MakeEdge(b122, b121)
Edge e74 := MakeEdge(b100, b003)
Edge e75 := MakeEdge(b001, b000)
Edge e76 := MakeEdge(b023, b022)
Edge e77 := MakeEdge(a132, a131)
Edge e78 := MakeEdge(b121, b120)
Edge e79 := MakeEdge(a110, b113)
Edge e81 := MakeEdge(b022, b021)
Edge e82 := MakeEdge(a111, a110)
Edge e83 := MakeEdge(a133, a132)
Edge e84 := MakeEdge(b102, b101)
Edge e85 := MakeEdge(b003, b002)
Edge e86 := MakeEdge(a112, a111)
Edge e87 := MakeEdge(b101, b100)
Edge e88 := MakeEdge(b123, b122)
Edge e89 := MakeEdge(b002, b001)
Edge e90 := MakeEdge(a113, a112)
Edge e91 := MakeEdge(b103, b102)

Style:

canvas {
  width = 400
  height = 400
}

global {
    nearTopLeft = (-1 * canvas.width / 2, canvas.height / 2)
    nearBottomRight = (canvas.width / 2, -1 * canvas.height / 2)
}

forall Node n {
    n.unitInterval = unitRandom()
    n.unitCircle = circleRandom()
    -- ensure inRange(n.unitInterval, 0, 1)
    -- ensure equal(vdistsq(n.unitCircle, (0, 0)), 1)
    -- n.linearDimension = global.a * n.unitInterval
    -- n.circleDimension = global.b * n.unitCircle
    -- n.x = n.linearDimension
    n.debugDot = Circle {
        center: n.unitCircle * 10
        r: 2
        fillColor: rgba(1, 0, 0, 1)
    }

    n.center = n.unitInterval * global.nearBottomRight - (1 - n.unitInterval) * global.nearTopLeft
    
    n.icon = Circle {
        center: n.center
        r: 6
        fillColor: rgba(0, 1, 0, 1)
        ensureOnCanvas: false
    }
}

forall Edge e; Node a; Node b
where e := MakeEdge(a, b) {
    e.distsq = vdistsq(a.center, b.center)
    e.dist = vdist(a.center, b.center)
    -- e.icon = Line {
    --     start: a.icon.center
    --     end: b.icon.center
    -- }
}

forall Node n; Edge e {
    -- e.icon below n.icon
}

collect Node n into nodes {
    -- normsqs = listof normsq from nodes
    -- centers = listof center from nodes
    -- scalar scale = (canvas.width / 4) * (canvas.height / 4)
    -- ensure sum(normsqs) / count(normsqs) == scale
    -- ensure norm(sumVectors(centers)) == 0
    -- projectedCenters = listof projectedCenter from nodes
    -- encourage tsneEnergy(centers, projectedCenters) == 0 in later
}

collect Edge e into edges
where e := MakeEdge(a, b)
foreach Node a; Node b {
    -- dists = listof dist from edges
    -- encourage minimal(maxList(dists))
    distsqs = listof distsq from edges
    encourage sum(distsqs) == 0
}

- Windows 10
- Chrome 115.0.5790.171 (Official Build) (64-bit) (cohort: Stable) 

I am not certain, but I think this might be "after fiddling with it for a while" rather than immediately replicatable by re-pasting the Domain / Substance / Style in.

**Comment by Johnicholas** [comment]
It's not specific to that triple, it's just fiddling with Penrose for a while:

![image](https://github.com/penrose/penrose/assets/461830/483a006d-9f41-4b62-86bf-03ed9229093a)

```
.domain:
type Circle
type Rectangle

.substance:
Rectangle r
Circle c_i for i in [0, 30]

.style:
canvas {
    height = 1300
    width = 800
}
global {
    ASPECT_RATIO = 1.6
}
forall Circle c; Rectangle r {
    ensure contains(r.icon, c.icon)
}
forall Circle c {
    c.icon = Circle {
        r: 80
    }
}
forall Circle c1; Circle c2 {
    ensure disjoint(c1.icon, c2.icon)
}
forall Rectangle r {
    r.icon = Rectangle {}
    ensure equal(r.icon.width * global.ASPECT_RATIO, r.icon.height)

    -- encourage minimal(r.side) -- doesn't work
    -- encourage minimal(abs(r.side)) -- doesn't work
    -- encourage minimal(sqr(r.side)) -- works
    encourage minimal(r.icon.width * r.icon.height) -- works
    -- encourage minimal(r.side * r.side * r.side * r.side) in shrinkSquare -- works
}
```

**Comment by wodeni** [comment]
> It's not specific to that triple, it's just fiddling with Penrose for a while:

Fun example! Tried this on my end and no memory errors yet: https://penrose.cs.cmu.edu/try/?gist=775298b73c54eaa4c9544b5d98f1052e. Looks like the WASM memory issue pops up every once in a while (cc @samestep thoughts on why?).

**Comment by samestep** [comment]
I haven't seen this error before; not really sure what's causing it. 🤔
