### ISSUE TITLE
Tutorial 3 : uses an outdated argument (`arrowheadSize`) for `Line`

### ISSUE THREAD

**Issue by Doublonmousse** [penrose/penrose#1614]
**Describe the bug**

In the tutorial 3, (see `packages/examples/src/tutorials/solutions/tutorial3.md`) the `arrowheadSize` is used for a `Line` object. However, this argument does not exist anymore, only `endArrowheadSize`and `startArrowheadSize`.

This means that the arrow size is not affected by `arrowheadSize`, and the compiler does not gives any error or warning that this argument does not exist anymore and one should use the updated  `endArrowheadSize`and `startArrowheadSize`.

**To Reproduce**

Use the tutorial 3 file : `packages/examples/src/tutorials/solutions/tutorial3.md` task 1.

Lines : all lines using the `arrowheadSize` argument

1. Open the tutorial 3 task 1 file
2. Change the arrow head size
3. See nothing happen to the arrow head size

**Expected behavior**
The arrow head size should change. This is due to an outdated argument used to set the arrow head size.

**Screenshots**

Using the mentionned file (tutorial 3, task 1), the arrow head size of all lines are supposed to be set to the same size with the erroneous `arrowheadSize` argument :

![Tutorial 3 - Vector](https://github.com/penrose/penrose/assets/115779707/2761ae81-6b6c-4e8d-85dc-4baf4cca7e24)

**Desktop:**

Happening both on the web ide and locally (latest commit, firefox on mac mini m2)

**Comment by samestep** [comment]
Thanks!
