### ISSUE TITLE
Error: Style internal error: expected to be either a constructor or function, but was not found

### ISSUE THREAD

**Issue by Johnicholas** [penrose/penrose#1623]
If after writing your .style file, you decide something that was a constructor or a function should be a predicate instead, and change it in your .domain, but leave the syntax in the .style file alone, then the compile error:
1. doesn't show up visibly
2. doesn't point to a line in your .style file

![image](https://github.com/penrose/penrose/assets/461830/a807588c-fb46-4a09-9d4d-6b6024741771)

**Comment by wodeni** [comment]
This type of changes should produce a Substance error if the constructor was used in Substance. For instance, I switched `Segment` in one of the geometry diagrams and the IDE correctly showed Substance errors:
![image](https://github.com/penrose/penrose/assets/11740102/910d1afe-f72c-4317-ba3b-14f213e8c8ec)

https://penrose.cs.cmu.edu/try/?gist=b7be4705acda3fdee7c2062336f3e59c

It's a bit strange that Style errors even showed up in @Johnicholas's example. Perhaps the nature of their change is different here?

Anyhow, it'd be good to focus to the origin of error in the IDE with a combination of (1) flexlayout pane switch and (2) monaco scroll to (aka [`revealLine`](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditor.html#revealLine)).

**Comment by Johnicholas** [comment]
Possibly a different / smaller example of this bug:

https://penrose.cs.cmu.edu/try/?gist=7c28c2c570d00630c14d0a185343311b

![image](https://github.com/penrose/penrose/assets/461830/f25a8d4c-a003-4a0b-8385-bdf32c7d06c2)

**Comment by liangyiliang** [comment]
Fixed, see #1635
