### ISSUE TITLE
make it faster

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#166]
with `initWeight = 0`: Converges very fast w/ constraints removed (function-composition.sub) 

with `initWeight = 1`: Steps very slowly with a higher weight; does not seem to converge but looks visually OK (function-composition.sub)

Near the end of the optimization, the line search suddenly takes 101 or 35 steps when previously it took 0-5 steps, causing the frontend to visibly slow down

Full log: https://gist.github.com/hypotext/10798be4bd25a5caee2e7a9810d66a1a

**But just one step takes a lot of time still. Could it be that it's really expensive to evaluate the function?**

Do we know about the performance of `ad`?

Keenan suggestion: solve smaller parts of the opt problem first and put the solutions together?

Could one of the issues from the last issue (see last comment [here](https://github.com/penrose/penrose/issues/116)) be the underlying cause?

**Comment by hypotext** [comment]
Minimal example doesn't print twice, so we still haven't figured out if it has to do with the translation being polymorphic (i.e. things happening under a typeclass) or being stored in a record.

**Comment by wodeni** [comment]
Minimal example that reproduces multiple evaluation of `Translation`

```
{-# LANGUAGE RankNTypes #-}
import Debug.Trace

-- Prints out two "hello"s
data Translation = Trans { m :: forall a . Floating a => a }

g :: Floating a => a -> a
g x = x + 1

f :: Floating a => a -> a
f x = trace "hello" $ x - 2.0

-- Only one "hello"
-- data Translation = Trans { m :: Float }
--
-- f :: Float -> Float
-- f x = trace "hello" $ x - 2.0

main :: IO ()
main = do
    let trans = Trans { m = f 1.5 }
    putStrLn $ show $ m trans
    putStrLn $ show $ m trans
```

**Comment by hypotext** [comment]
[StackOverflow question](https://stackoverflow.com/questions/54297226/unexpected-caching-behavior-using-polymorphic-records-in-haskell/54298270#54298270)

Questions
* Can we monomorphize/specialize the translation?
* Are the shapes also also being computed every time we take them out of the state? What about overallObjFn?
* Can we monomorphize everything else everywhere? (Except for autodiff?)
* Can we compile with type defaults and see if that helps?

The problem is not that the translation is being _recomputed_ every time we take it out of the state. Actually, the problem is the translation _hasn't been computed at all_ (i.e. it's a thunk) because it's actually a function `Floating a => Translation a` that's waiting for a dictionary argument (and GHC doesn't/can't memoize that function). The translation is not a value of a datatype (?). So, every time we take the translation _function_ out of the state and (eventually) use/force it, GHC finds the dictionary instance for it (because the behavior of the computations around it depend on the typeclass implementation) and then applies the translation _function_, which computes the translation, which requires... re-running the whole Style compiler.

As the SO answer puts it:

> `f 1.5 :: Floating a => a`
> 
> looks like a plain old value; but in fact it is a _function_ which takes a `Floating a` dictionary and produces a value of type `a`. So any computations that go into computing the value `a` are _redone_ afresh each time this function is applied (read: used at a specific monomorphic type) because, after all, the precise value chosen depends critically on how the typeclass' methods behave.

**Comment by hypotext** [comment]
Resolved in last commit.
