### ISSUE TITLE
Style match strategy does not scale well; generates too many substitutions

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#167]
With these Substance and Style programs, it becomes clear that we are generating too many substitutions (up to 2 million) and taking too long to analyze them. It's written simply and declaratively (and slowly).

`function-composition.sub`, `parallel-reals2.sty` with this selector

```
Function h
where h := compose(g, f);
      f := compose(e, d);
      h := CreateFunction(A, D);
      g := CreateFunction(C, D);
      f := CreateFunction(A, C);
      e := CreateFunction(B, C);
      d := CreateFunction(A, B)
with Function g, f, e, d;
     Interval A, B, C, D;
     Reals `R` { ... }
```

Temporary fix is to abridge the match like this:

```
Function h
where h := compose(g, f);
      f := compose(e, d);
      h := CreateFunction(A, D)
      -- g := CreateFunction(C, D);
      -- f := CreateFunction(A, C);
      -- e := CreateFunction(B, C);
      -- d := CreateFunction(A, B)
with Function g, f, e, d;
     Interval A, D;
     Reals `R` {
```

**Comment by samestep** [comment]
@keenancrane ran into this today. @wodeni is thinking of a better way to implement this.

**Comment by joshsunshine** [comment]
@liangyiliang can you see whether your recent changes (i.e. https://github.com/penrose/penrose/pull/1072) have fixed this issue?

**Comment by liangyiliang** [comment]
The language has changed a lot, and I couldn't draw an entire diagram.

However, for the specific style selector @k-qy talked about, the current version matches it a lot faster. See [here](https://penrose.cs.cmu.edu/try/?gist=e38b5168bda4315fdb61db0455a364cc).

**Comment by joshsunshine** [comment]
Okay. I'm going to close this issue.
