### ISSUE TITLE
Element typechecking regression?

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#168]
(Note: DSLL was recently renamed to Element)

In commit c99510abc6311e8a822031f6e42dcd86a8057c54, when we merged `end-user-real-analysis` with `master`, we ran into the following strange error with these programs: `penrose sub/tree.sub  sty/venn.sty  dsll/setTheory.dsl`

* before the merge, on the branch, Element typechecking did NOT throw an error comparing `tconstructor Map : Type` with `Map('A, 'B)`, but it should have thrown an error
* after the merge, Element typechecking DOES throw an error there, but it still doesn't throw an error on the predicates like `Surjection` that incorrectly use `m : Map('A, 'B)`.

We (@wodeni and I) temporarily solved the problem by removing all type parameters from `dsll/setTheory.dsl`, but we're not sure why this problem happened as a regression (?) or how it might arise in the future.

**Comment by maxkrieger** [comment]
@wodeni is still a thing in the port

**Comment by wodeni** [comment]
Not sure about this exact case. But since the checkers are completely rewritten and we aren’t using type vars for now, I’ll close this one.
