### ISSUE TITLE
Frontend doesn't render arc, brace, parallelogram GPIs

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#170]
As in title. Arcs are used in the linear algebra style and the raytracing style, so would be nice to have it soon.

**Comment by hypotext** [comment]
It also doesn't render brace or parallelogram GPIs (used in the linear algebra style).

**Comment by maxkrieger** [comment]
@wodeni should we split this?

**Comment by maxkrieger** [comment]
Is this done?

**Comment by hypotext** [comment]
Resolved: Arc is added to frontend; parallelogram is added to frontend; brace is removed because it shouldn't be a GPI. (The "straight brace" is implemented as 3 lines, e.g. to illustrate the norm; the curly brace is implemented as an SVG import, e.g. in the real analysis domain.)
