### ISSUE TITLE
Improve Substance parsing to distinguish between value constructors and functions

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#171]
Currently, the Substance parser requires that operators be declared in lowercase and value constructors should start with capital letters. However, we adopted the convention that Substance names should start with capital letters, so this means that operators are now *mis-parsed* as value constructors.

As a consequence, part of the Style typechecking is incorrect, since it relies on distinguishing between operators and value constructors.

**Comment by wodeni** [comment]
This was an explicit design decision we made. Otherwise, the parser will not be able to distinguish the two. See below: 
```haskell
        -- TODO: document that value constructors should start w/ a capital letter and functions w/ lowercase
        SEAppValCons <$> upperId <*> parens (selectorExpr `sepBy1` comma),
        SEAppFunc    <$> lowerId <*> parens (selectorExpr `sepBy1` comma),
```

**Comment by hypotext** [comment]
Resolved by @wodeni in https://github.com/penrose/penrose/commit/27748e8d860a65345a15cbc5513f26f153fbaedc. Thanks!
