### ISSUE TITLE
feat: Warn user if they're about to close a browser tab with unsaved Penrose code

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1733]
Would we want some kind of warning if a user is about to close a Penrose tab they've typed a bunch of code into?

E.g., https://stackoverflow.com/questions/2858057/ask-for-confirm-when-closing-a-tab

**Comment by wodeni** [comment]
Mega-issue on this: #1683

> there's no confirmation that you're abandoning work if you navigate to someone else's gist while in draft mode
> there's no confirmation that you're abandoning work if you navigate to new webpage while in draft mode
