### ISSUE TITLE
deleting a workspace then saving another one overrides other saved workspaces

### ISSUE THREAD

**Issue by KyleleeSea** [penrose/penrose#1740]
**Describe the bug**
When you delete a locally saved workspace it highlights a previously saved workspace while putting the user in a separate unsaved workspace. If the user saves this workspace, it overrides the saved content in that highlighted workspace. 

**To Reproduce**
Create two saved workspaces. Give them different content and titles to differentiate.
Delete the second workspace.
Observe the first workspace is highlighted, but the top bar says "Untitled Diagram"
Click "save" and observe the content of the first workspace gets overrided

**Comment by KyleleeSea** [comment]
Update: Additional bug, deleting a workspace does not update the diagram panel. If the deleted workspace had a diagram, the diagram remains shown in the diagram panel after deletion.

**Comment by samestep** [comment]
OK! Nah, if they're both just one-line fixes then don't worry about it. Thanks for catching this!
