### ISSUE TITLE
feat: Add functionality to join paths

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1767]
### Issue

There are many situations in which it is necessary to concatenate multiple paths into a single path.  A common case is connecting several open paths into a single closed path that can be filled.  Consider for instance this figure, where each of the circular arcs is drawn as a `Path` shape using the `circularArc` function:

<img width="264" alt="image" src="https://github.com/penrose/penrose/assets/3604525/51c325e2-eeba-4ca2-83a4-9bfcfb2d78ff">

Suppose we now want to fill the region bounded by the three arcs with a solid color.  Currently there is no way to do this in Style.

### Proposal

A straightforward solution is to implement Style functions that can join path data into a new path.  There are several possibilities for how such a function might work.  For instance:

* `joinPaths( [ p1, p2, … ] )` — takes a list of path data instances $p_1$, $p_2$, … and produce a single path where the final point in each path $p_i$ has been replaced with the first point in path $p_{i+1}$.  This function should perhaps also take an `"open"/"closed"` flag which determines whether the final vertex is included in the path description (since a closed SVG path will automatically connect back to the initial point).
* `connectPaths( [ p1, p2, … ] )` — takes a list of path data instances $p_1$, $p_2$, … and produce a single path where the final point in each path $p_i$ is connected to the first point in path $p_{i+1}$ by some connecting geometry (by default, a straight line segment).
* `concatenatePaths( [ p1, p2, … ] )` — takes a list of path data instances $p_1$, $p_2$, … and produce a single path by just concatenating the raw path commands.

Alternatively, we could just have a single function `joinPaths` that automatically determines whether endpoints need to be joined or not depending on whether or not they coincide (perhaps within some user-specified floating point error tolerance).

**Example usage.**

Here's a mockup of usage for the diagram above:

```
shape arc1 = Path {
   d: circularArc( "open", c1, r1, alpha1, beta1 )
}
shape arc2 = Path {
   d: circularArc( "open", c2, r2, alpha2, beta2 )
}
shape arc3 = Path {
   d: circularArc( "open", c3, r3, alpha3, beta3 )
}
shape region = Path {
   d: joinPaths( "closed", [ arc1, arc2, arc3 ] )
   fillColor: blue;
}
```

**Comment by griffinteller** [comment]
Honestly, all three would be nice. Just opened a PR (#1770) for the `connectPaths` and `concatenatePaths` variants; the `joinPath` version may be slightly more difficult if we want visually correct results when the start and end points _aren't_ the same, since somehow we'd need to translate the coordinates while working with autodiff types. But maybe its ok to just delete the `M` command?
