### ISSUE TITLE
Compile Error Not Displaying

### ISSUE THREAD

**Issue by apalliyil** [penrose/penrose#1768]
**Describe the bug**
A clear and concise description of what the bug is. If there is an error in the inspector pane, please paste that string in.

When trying to compile this erroneous code, no error panel/message displays. The actual error is that o.text is not previously assigned. 

https://penrose.cs.cmu.edu/try/?gist=6d095c6bb1d5c3527b82b092c12b1668

**Comment by griffinteller** [comment]
Thanks, on it.
