### ISSUE TITLE
Porting Surjection/Bijection/Injection examples with the new alloy plugin

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#180]
Now that we have the new plugin mechanism, we can port the old examples back into the new system.

- [x] Surjection
- [x] Injection
- [x] Bijection

Note that we do not aim to perfectly replicate the old examples, but rather porting them as a way to test the plugins.

**Comment by wodeni** [comment]
# Examples
## Injection
`penrose sub/injection.sub sty/discrete.sty set-theory-domain/setTheory.dsl`
![image](https://user-images.githubusercontent.com/11740102/53225334-afb48f00-3645-11e9-830f-caf24b79adbf.png)
## Surjection
`penrose sub/surjection.sub sty/discrete.sty set-theory-domain/setTheory.dsl`
![image](https://user-images.githubusercontent.com/11740102/53225421-facea200-3645-11e9-946e-b4c7ee1f729d.png)
## Bijection
`penrose sub/bijection.sub sty/discrete.sty set-theory-domain/setTheory.dsl`
![image](https://user-images.githubusercontent.com/11740102/53225553-7597bd00-3646-11e9-9756-d88e2a553ad9.png)

**Comment by wodeni** [comment]
No further polishing is required at this stage. Closing the issue now.

**Comment by hypotext** [comment]
@joshsunshine: It would be more beautiful with rounded rectangles.
