### ISSUE TITLE
Deal with plugin accessors on Substance edit

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#188]
In bf64f3c, `compileStyle` is changed to take the Style values returned by the plugin. However, the server does not know about these Style values yet, so in context of `substanceEdit` in `Server`, the use of `compileStyle` (currently line 375) needs to be extended to have access to these Style values.

**Comment by wodeni** [comment]
Should be an easy fix, but let's discuss whether the Style-val-reading logic should be included into `compileStyle` or not. Also, let me know if you have an example that I can test with in mind.
