### ISSUE TITLE
Make Element language revisions for TOG paper

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#192]
Changes from a discussion with Keenan:

- [x] Simplify type constructor notation to `type Scalar`
- [x] Simplify function notation to `function scale : Scalar c * Vector v -> Vector cv`
- [x] Simplify predicate notation to `predicate In : Vector * VectorSpace`
- [x] Change `StmtNotation` to `notation`
- [x] Change notation delimiter from `:=` to `~`
- [x] Maybe make it optional to name parameters in types, so someone could write, say, `function scale : Scalar c * Vector -> Vector`
- [ ] Add appropriate syntax highlighting

The most recent iteration on the Element syntax can be found in the [paper draft](https://github.com/penrose/TOG-2019/blob/master/Paper/penrose-system.tex). Here is an example program:

![image](https://user-images.githubusercontent.com/2762356/55754833-8c8a4700-5a1b-11e9-90ea-1e125c8ccab3.png)

We will also need to port the existing Element programs. 

- A note on dependent types: Keenan thinks they make sense mathematically. e.g. two vectors are from same vector space, or `f : X -> Y, g : Y -> Z`. This is an opportunity to specify the basic semantics of math objects and check correctness of Substance programs. It's fine if we don't add dependent types for this paper, though.

**Comment by dormaayan** [comment]
Since I worked on that I'll be happy to do the changes if needed.

**Comment by hypotext** [comment]
Thanks @dormaayan! I'll definitely take you up on the offer after Keenan and I do some more writing, so we're set on the exact changes that we'd like to have.

**Comment by hypotext** [comment]
JS/JA: Consider `scale (Scalar, Vector v) -> Vector` so the notation for functions is consistent with the notation for predicates. 
Should we put a colon in the function notation? Or make the predicate notation similar to the function type?
JS/JA: We are somewhat concerned that the style of C/Java style notation for types will be an issue with higher-order functions. How to give a structural type to a higher-order function in this notation? Would need to name it.
Double arrow: JA doesn't have a strong opinion, but it's not symmetric. Don't use `->` because it's not the same semantics as the function arrow. Maybe `~`?

**Comment by hypotext** [comment]
Hey @dormaayan, after discussing with Jonathan and Josh, we settled on a final revision of the Element syntax. I updated the body of the issue to reflect the changes and the most recent example program. Do you think you would be able to make these revisions? 

The only thing that seems possibly tricky is having optional parameters in types. Maybe @wodeni can comment on the difficulty of parsing that.

**Comment by dormaayan** [comment]
Hey @hypotext , sure, I'll do that!
Should I branch-off from master?

**Comment by hypotext** [comment]
Thanks @dormaayan! Branching off from master sounds good. 

For syntax highlighting: don't worry about that for now, since the IDE doesn't display Element programs yet (cc @maxkrieger).

**Comment by dormaayan** [comment]
@hypotext : Is there a good reason to allow people to name parameters in types? We can let them do that but we don't use these names anyway and it might be confusing...

**Comment by hypotext** [comment]
Yeah, naming parameters in types is useful for two reasons: first, we need those names for value constructor arguments (otherwise we can't deconstruct them). Second, often elements in math have canonical names (like `c` for Scalar) and it's useful to be able to refer to them like that.

This reminds me that I forgot to discuss two other syntactic forms in Element:

Value constructors change:

`vconstructor CreateRightClopenInterval (left : Real, right : Real) : RightClopenInterval`

to

`constructor CreateRightClopenInterval : Real left * Real right -> RightClopenInterval`

and subtyping probably doesn't change:

`Reals <: Interval`

I do always forget which way to write the `<:`. But I'm not sure if something like `Reals isSubtypeOf Interval` looks better.

**Comment by dormaayan** [comment]
Merged with #202
