### ISSUE TITLE
Make shapes generic (electric boogaloo)

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#195]
Adapted from #109 and @wodeni's ideal `.shapes` file. We create a schema for constructing and rendering generic shapes via macros. We embed our DSL in JSON and a safe templating language like Mustache.

```json
{
"params": [
 {
    "name": "x",
    "type": "float"
  },
  {
     "name": "y",
      "type": "float"
  },
  {
    "name": "fill",
    "type": "color",
    "default": "black"
  }
],
 "compute": {
     "xComputed": {"call": "toScreenX", "args": [{"x":, "x"}]},
      "yComputed": {"call": "toScreenY", "args": [{"y":, "y"}]}
  },
"targets": {
    "svg": {
         "tag": "rect",
         "attrs": {
            "x": "xComputed",
            "y": "yComputed"
         }
    }
}
}
```

Open questions:

How does scope work? There may be computed dimensions like `toScreen`. Should we have "mixins" that compose with params like:
```json
{
"params": [
  {
    "name": "x",
    "type": "float",
    "default": "0.0"
  },
  {
    "name": "y",
    "type": "float",
    "default": "0.0"
  }
],
"mixins": ["toScreen(x, y)"],
}
```

How can we effectively generate paths and other highly dynamic/mapped pieces of data? Does Style have to express this kind of rich information either way? Should we use a templating language that supports iterators or inline JS?

Named parameters?

**Comment by wodeni** [comment]
![image](https://user-images.githubusercontent.com/11740102/54706570-9eac5000-4b15-11e9-964c-5f7ff97f747e.png)

**Comment by hypotext** [comment]
According to @miyehn we could look at Processing's object-oriented model for user-extensible shapes.

**Comment by miyehn** [comment]
> According to @miyehn we could look at Processing's object-oriented model for user-extensible shapes.

The code I showed you today is [here](https://github.com/miyehn/aurora_thingy).
![gif](https://github.com/miyehn/aurora_thingy/raw/master/gifs/01.gif)
Every time there's a click+drag, [an `Aurora` object is made](https://github.com/miyehn/aurora_thingy/blob/03b19bd1fb6d3a3793ec6a4b4e64242e99a5bed7/aurora_thingy.pde#L32). Can think of it as a custom shape that gets updated and rendered each frame.
Each `Aurora` object has property `dots`, which is [a list of `LaggedDot` objects](https://github.com/miyehn/aurora_thingy/blob/03b19bd1fb6d3a3793ec6a4b4e64242e99a5bed7/Aurora.pde#L4) (can think of it as another custom shape).
Each `LaggedDot` object has a list of points, etc...

The idea is that in Processing users can chain up simple shapes to make larger, more complicated ones.

**Comment by maxkrieger** [comment]
A compositional approach would definitely solve a lot of problems. Something in your processing code that I'm still not sure how to represent, though, is computations. Interested in @wodeni's thoughts when he has the chance.

**Comment by wodeni** [comment]
The OO way is certainly an option for organizing shapes that would allow more reusability. The "typeclass" idea of, say, `LineLike` and `Movable`, can probably be modeled as interfaces? Seems like a doable thing to me. In this case, we would need a more language-like specification format or write this in another language eventually, perhaps with a mechanism for defining functions that `Functions` module can use as well.
