### ISSUE TITLE
Add new syntax to Style

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#201]
It would be great if we could add the following desperately-needed syntax to Style:

* Constructing 2-tuples inline: `e ::= ... | (e1, e2)`
* Constructing lists of expressions: `e ::= ... | [e1, e2, ..., en]`
* Composing transforms: `e ::= ... | e1 then e2` (can be nested left-associatively without parens)
* Change `OPTIMIZED` to `?`
* Change `=` (in setting fields and properties) to `:`
* Maybe add type declarations for fields?

We should also add syntax for deconstructing lists and tuples, but that's less urgent, since Style programs don't often need to do that.

We also need to work out the semantics of these expressions:

* What types can these containers hold? 
* Are they strongly-typed and singly-typed?
* Do we allow nested expressions? 
* How are these expressions evaluated?

We also need to port old Style programs after this is done.

Related issue: #165

**Comment by hypotext** [comment]
@wodeni Do you think you'd be able to work on this soon? I'm happy to work out the semantics for types and evaluation.

**Comment by wodeni** [comment]
Sure. I can update the parser this week. Let me know if you need any help on typechecking (if any) and eval!

**Comment by hypotext** [comment]
Mostly done, and remaining features are tagged in `style-1.1`
