### ISSUE TITLE
Try to reduce compile times for the system

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#203]
Right now, compiling the system from scratch takes a couple of minutes. Is there an easy way to reduce compile times?

Maybe it's because we use Generics, Aeson, a lot of compiler flags, etc. and that makes the compiler do more work. 

Also, maybe there's some way to not have to recompile all the dependent modules when Utils or Transforms changes.

**Comment by wodeni** [comment]
Seems relevant: https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

**Comment by hypotext** [comment]
`stack build --fast` does actually make it faster. Thanks!
