### ISSUE TITLE
Polygonize labels

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#206]
It seems straightforward for me to polygonize the remaining shapes in the Penrose system, except for the text in LaTeXed labels: this could be tricky, and doing it is especially important for us so we can optimize labels. Perhaps this is a good project for @miyehn to work on? And maybe we can discuss with @wodeni the best way to do this in the frontend.

**Comment by hypotext** [comment]
@wodeni @maxkrieger Would you have time to pair on porting labels in our transforms + polygons branch tomorrow?

@miyehn and I would like to treat Text as a GPI in the frontend, according to the approach taken in (for example) [`CurveTransform.tsx`](https://github.com/penrose/penrose/blob/transforms/src/react-renderer/src/CurveTransform.tsx#L75).

Ideally, the frontend would:
* render labels
* send curves to the backend
* apply transform to labels in frontend
* render the polygon of text

The backend would:
* make a polygon from the curves (might just be bbox for now)
* send the transform and polygon to frontend (as properties of the text GPI)

**Comment by wodeni** [comment]
Yep. Concrete TODOs I can think of:
* Pull out the path data from MathJax
* Apply appropriate transforms to make sure they look right
  * TODO: see if there's something we can use from MathJax to get it without too much hacking
* Parse the path data and translate it to the backend types
  * Parsing: https://github.com/nfroidure/svg-pathdata looks promising

**Comment by hypotext** [comment]
After discussing this today with everyone, the right way to polygonize labels seems to be:
* in collectLabels, access the `body` returned by tex2svg, which is the DOM element for the whole label
* walk the nested groups, accumulating the transform stack for each raw path
* polygonize the raw paths in the frontend using getPointAtLength (though this is apparently being [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement/getPointAtLength)???)
* apply the relevant overall transform to each raw path
* figure out what to do about viewboxes??
