### ISSUE TITLE
make it even faster

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#213]
The optimization is still much slower than it ought to be. With such a small problem size (10-100 DOF) and small polygons (10-100 vertices) it still takes seconds to minutes to converge, and sometimes almost a second per step. It should really be running 10-1000x faster per step, since other graphics/optimization code can handle meshes with millions of vertices much faster than we can.

It seems there are three main things to make faster:
* the speed of evaluating the objective function
* the speed of taking a gradient of the objective function
* the overall speed of the system (all other overhead like evaluating shapes and I/O)

We'd like to make two metrics faster:
* time per step (raw speed of evaluating the objective function and differentiating it)
* time to overall convergence (how long it takes to solve an optimization problem end-to-end)

Considering a variety of factors:
* scaling with size of optimization problem (# DOF)
* scaling with complexity of optimization problem (# objectives and constraints and their difficulty)
* polygon use vs. analytic calculations

Here are some major things to try:
* Squash polymorphism and genericity, inline functions, make everything strict https://wiki.haskell.org/Inlining_and_Specialisation https://wiki.haskell.org/Performance/Overloading
* Statically generate the objective function
  * The idea is to replace all the runtime lookups of paths, etc. with let-bindings in a Haskell function. That's like statically building the computational graph, instead of dynamically building it at runtime. If it's a Haskell function then it can be optimized etc. by the compiler. (Also, it ultimately needs to be a Haskell function anyway for the autodiff)
  * do we have to generate a new objective function for each diagram strategy? 
  * we need to generate it so it only differentiates through the stuff that adds to the energy. suggests that we should write our own analytic gradients for the leaf nodes of our objectives, computations, etc.
* Replace autodiff with some analytic gradients especially for Rain's code
  * Keenan's intuition is also that we are "abusing autodiff" by giving it a huge chunk of haskell code to differentiate, rather than compiling to just the bare math (which is what autodiff should be getting)
  * but then we have to figure out how to manage which variables are varying again 
  * https://github.com/ekmett/ad/issues/77 
  * understand reverse-mode AD better with jacobians

Here are some minor things to try:
* it's very strange that shapedefs comes up that often, given that we do not explicitly use it when applying opt fns. I suspect it's `findVarying` because it calls `propertiesOf`, which uses `shapeDefs`. Seems like the bang pattern is not working as expect, so the cached `varyingPaths` is evaluated at each step?
* Use `grad’` instead of `grad` (saves a function evaluation) and cache energies
* Pre-evaluate translation before putting in objective function, so we don't evaluate fixed computations on every step
* Make `getShape` and `getName` faster as currently they are linear-time lookups that use a derived `compare`

As a possible upper bound, profiling a version of the system with a small Style program inlined as an objective function yields 10x speedup and 10x less memory use. This is not as much of a speedup as I was expecting. There are still some questions around whether we might be able to see more speedup in practice (for larger Style programs) or less speedup (if our generated function is less efficient than this bound, or with frontend rendering overhead). See thread in slack [here](https://pen-rose.slack.com/messages/C2EV136RX/convo/C2EV136RX-1556751671.018000/).

![image](https://user-images.githubusercontent.com/2762356/57146076-7d848380-6d92-11e9-99d6-1855fca691d7.png)

Perf can be measured with a profile by setting `useFrontend = False` in ShadowMain. We should also benchmark using [Criterion](http://www.serpentine.com/criterion/tutorial.html).

relevant branches: `speed`, `transforms`

previously on "make it fast": #166 #116 

inspiration: https://www.youtube.com/watch?v=Tj9q4ADVrL4

**Comment by wodeni** [comment]
@hypotext needs to benchmark the web optimizer to make it **extra** faster

**Comment by wodeni** [comment]
Closing the issue for now as it's more related to the old optimizer.
