### ISSUE TITLE
Frontend throws undefined error when fields are looked up recursively

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#214]
On branch `speed`, with path `runpenrose real-analysis-domain/spec-RA.sub real-analysis-domain/parallel-RA.sty real-analysis-domain/real-analysis.dsl`:

If these lines are commented out in this commit:

https://github.com/penrose/penrose/commit/c7013cb2ee53078350fb30bea4c4038bf8c7ec5b#diff-0114fbd83c1cc3dd98fdfe4de0453b57R1512

the frontend throws an undefined error 

![image](https://user-images.githubusercontent.com/2762356/57169767-c0684a80-6dd6-11e9-9070-c4c0bb8048a7.png)

I think this has something to do with recursive field evaluation doing something that somehow leads to an object being created in the backend that results in `undefined` in the frontend (maybe can't serialize something) but I don't see why this is happening. Once this is fixed, the hack in `shapeType` should be removed.

**Comment by maxkrieger** [comment]
I'm curious if our new serialization approach #236 will change this behavior. I'm adding new frontend compatibility to it today.

**Comment by wodeni** [comment]
Can't repro this as the RA domain is deprecated now. Closing the issue.
