### ISSUE TITLE
Recreate all the relevant objectives and constraints with the polygon energies

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#216]
## Existing polygon energies

- [x] contains
- [x] disjoint
- [x] tangent (inside)
- [x] tangent (outside)
- [x] alignment WRT some axis
   - [x] vertical, horizontal, other axis given by angle
- [x] Order objects WRT this axis
- [x] padding range (min, max)
- [x] inside-outside padding
- [x] intersection (with some specified px)
- [x] at (takes two points and a polygon)
- [x] near a special point in shape
   - Could have many other definitions of "near" - implemented one for now
- [x] minSize (circle/box of fixed size fits inside)
- [x] maxSize (fits inside circle/box of fixed size)
  - [x] onCanvas
- [x] sameSize (e.g. bboxes of a shape have the same size?)
  - [x] smallerThan

(All with and without padding)

# Test cases where multiple different energies are used together w/ reasonably different shapes

- [ ] contains and disjoint
- [ ] contains with padding and disjoint with padding
- [ ] alignment + padding + disjoint
- [ ] min+max padding + disjoint (optionally)
- [ ] pairwise disjoint with 3-4 shapes

---

## Existing objectives

- [ ] near
- [ ] center
- [ ] centerX
- [ ] centerLabel
- [ ] repel
- [ ] nearHead
- [ ] topRightOf
- [ ] nearEndVert
- [ ] nearEndHoriz
- [ ] topLeftOf
- [ ] above
- [ ] equal
- [ ] distBetween

## Existing constraints

- [ ] at
- [ ] contains
- [ ] sameHeight
- [ ] nearHead
- [ ] smallerThan
- [ ] minSize
- [ ] maxSize
- [ ] outsideOf
- [ ] overlapping
- [ ] disjoint
- [ ] inRange
- [ ] lessThan
- [ ] onCanvas

**Comment by hypotext** [comment]
Hey @miyehn, just checking in on this. Looks like you're making great progress. How's it going? Would you be able to document the working objective functions and give examples so I can repro them?

I'd like to merge the `transforms` branch to master soon (yes, with all the transform + polygon + speed + opt stuff) so let's coordinate on testing and documenting this work before the REU students get here.

**Comment by miyehn** [comment]
@hypotext Here is the list of energies and the objectives functions that call them. I hope some function names are self-explanatory but let me know if anything is unclear. https://docs.google.com/document/d/1FALB-awPhRfpbX9Lw3xvTZDwHFF2OgqLCj_M_W736FY/edit?usp=sharing 
I also pushed a few tests, inside the `src/test-transforms` folder, named t1 to t5. All tests use `src/test-transforms/setTheory-test.dsl`, and each uses `sub.sub` and `sty.sty` in their own folders. They all take a while to run, and with different combinations of objectives they show varying degrees of success, as energy functions can have many local mins..
I'm going to be free in the evenings to coordinate. When are REU students arriving?

**Comment by wodeni** [comment]
The students will be here on Aug 27 @miyehn. I'll go through the doc and let you know if there's anything that I'll need some explanations.

**Comment by hypotext** [comment]
Hey @miyehn, thanks for the thorough writeup (and sorry for the delayed response)!

I ran your tests and they look great overall. I put my results in the end of your doc. I also put some action items from a discussion with @wodeni there.

Just one thing stood out to me: sometimes when the sets (circles) are supposed to be nonintersecting/disjoint, they collapse onto the same circle (eg test 3, result 1 and 3, and test 4, result 1). I suspect it's due to an edge case in how you're writing the energy. Perhaps having two polygons located in exactly the same place is unintentionally a local minimum. Do you think you could fix this soon?

@wodeni also requested that you add the documentation in the code for the relevant objectives/constraints.

We are aiming to merge the `transforms` and `geom` branches to master (with tests and documentation) by this Monday night, so if you could look into these two items by then, that would be great!
