### ISSUE TITLE
Error doesn't get handled properly when name collisions occur

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#218]
Minimal example for the Set Theory domain:

```
Set A
Set A
AutoLabel All
```

The server will not send the error to the client (which is expected), it'll just crash.

I encountered this by naively trying a substance program along the lines of:
```
Set A
Point A
AutoLabel All
```
...which also fails.

**Comment by wodeni** [comment]
This is not just unique to the `check` function in the Substance typechecker, but also all other parts of the system with `error` call. It seemed that `try` is not catching these exceptions. Related issue: #158

**Comment by wodeni** [comment]
Closing in favor of #654
