### ISSUE TITLE
Porting old examples

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#219]
After big changes to the system on `geometry` and `transforms`, we decided to go through the existing examples again and make sure they all work properly. I decided to keep the notes short and not take screenshots.

Related issues & PRs: #215  #198  #205 

__For merging purposes, we decided to do this port on `geometry`__

## Simpler examples

* One subset relationship: `runpenrose sub/twosets.sub sty/venn.sty set-theory-domain/setTheory.dsl`
    * OK
* Two points, one with computed location: `runpenrose sub/twopoints.sub sty/twopoints.sty set-theory-domain/setTheory.dsl`
    * Big pink circle, seems okay
    * Stroke-color random
* Point in set relationship: `runpenrose sub/venn_comp_pt.sub sty/venn_comp_simple.sty set-theory-domain/setTheory.dsl`
    * Again, off-screen circle, otherwise okay.
    * Stroke-color random
    * `PointIn` args flipped (why???)
* Sets with each pair linked: `runpenrose sub/threesets.sub sty/test-local.sty set-theory-domain/setTheory.dsl`
    * Off screen circles, big arrows. 
* Optimized fields and properties: (here the padding and radii are optimized to lie within ranges) `runpenrose sub/threesets.sub sty/test-optimized.sty set-theory-domain/setTheory.dsl `
    * works but circles are of equal size and smaller in general

## More complex examples

* Subset relationships in Venn diagram style: `runpenrose sub/tree.sub sty/venn.sty set-theory-domain/setTheory.dsl`
    * OK
* Subset relationships in tree diagram style: `runpenrose sub/tree.sub sty/tree.sty set-theory-domain/setTheory.dsl`
    * OK
* Continuous map in set theory style: `runpenrose sub/continuousmap.sub sty/continuousmap.sty set-theory-domain/setTheory.dsl`
    * Size funcs added and works beautifully
* Surjection in Cartesian style: `runpenrose sub/cart-test.sub sty/cart-test-pt.sty set-theory-domain/setTheory.dsl`
    * Nothing works, rewrite needed
* Surjection in Cartesian style with special point: `runpenrose sub/cart-test-pt.sub sty/cart-test-pt.sty set-theory-domain/setTheory.dsl`
    * Nothing works, rewrite needed
* Nicer computed surjection (using `Map` type only): `runpenrose sub/surjection_computed.sub sty/surjection_computed.sty set-theory-domain/setTheory.dsl`
    * Doesn't work without `interpolate`.

### 1. Simple

* `penrose linear-algebra-domain/twoVectors.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 2. Two VectorSpaces
`penrose linear-algebra-domain/twoVectorSpaces.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 3. Negation
`penrose linear-algebra-domain/vectorsNegation.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 4. Addition
`penrose linear-algebra-domain/vectorsAddition.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 5. Two VectorSpaces with Addition and Negation
`penrose linear-algebra-domain/twoVectorSpaces-2.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK, addition looks bad in the first sample

### 6. Linear Map
`penrose linear-algebra-domain/linearMap.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: Bad local minima of flipped `U` and `V` shapes. Dragging fixes it sometimes. Check `lessThan` implementation

### 7. Norm
`penrose linear-algebra-domain/norm.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 8. Complex Addition
`penrose linear-algebra-domain/vectorsAddition-3.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 9. Scale
`penrose linear-algebra-domain/scale.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 10. Determinant
`penrose linear-algebra-domain/determinants.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK

### 11. Advanced Norm & Scalar Addition
`penrose linear-algebra-domain/norm-2.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`: OK, but weird looking

## Real analysis

* `runpenrose real-analysis-domain/spec-RA.sub real-analysis-domain/perpendicular-RA.sty real-analysis-domain/real-analysis.dsl`: OK, some weird interval behaviors as expected by @hypotext

* `runpenrose real-analysis-domain/spec-RA.sub real-analysis-domain/parallel-RA.sty real-analysis-domain/real-analysis.dsl`: OK, some weird interval behaviors as expected by @hypotext

## Mesh

`runpenrose mesh-domain/Figure1.sub mesh-domain/SimplicialComplex.sty mesh-domain/mesh.dsl`: OK, but I did need to clone the git repo using HTTPS and install `lodash` and `delaunator`, which are unfortunately not documented (cc: @hypotext).

## Geometry

`runpenrose geometry-domain/teaser.sub geometry-domain/euclidean.sty geometry-domain/geometry.dsl`

`runpenrose geometry-domain/teaser.sub geometry-domain/spherical.sty geometry-domain/geometry.dsl`

**Comment by hypotext** [comment]
Tested all the big examples on master after https://github.com/penrose/penrose/commit/17a22cead2a87e4d787c6bd80dc06df40b41be5c and they work. 

Thanks for making the list; it made it really easy for me to test. Closing this issue for now, but I think we should keep updating the list with the big examples, so I put them on a [wiki page](https://github.com/penrose/penrose/wiki/Paths-for-testing).
