### ISSUE TITLE
Linear Algebra Style layering is backwards

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#222]
Run any linear algebra substance program and try to drag any shape besides the plane. We also determined back in March that this issue is unique to Linalg by inspecting the JSON that gets passed through.

Relevant JSON:
```json
{"contents": ... "ordering":["u2.shape","u1.shape","c.shape","c.text","U.yAxisUp","U.yAxisDown","U.xAxisRight","U.xAxisLeft","u2.text","u1.text","U.textY","U.textX","U.text","U.shape"]},"type":"shapes"}
```

Where `U.shape` is the plane

**Comment by wodeni** [comment]
Seems to be related with #433, which is already fixed. Closing for now
