### ISSUE TITLE
Strange layout for IDE

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#227]
When I visit `use.penrose.ink` with Chrome on macOS and select the linear algebra example with determinant, this is what it looks like:

![image](https://user-images.githubusercontent.com/2762356/59404383-2f807980-8d5b-11e9-8100-fdfc877aa702.png)

The extra padding looks like it's part of the editor:

![image](https://user-images.githubusercontent.com/2762356/59404429-5a6acd80-8d5b-11e9-90ac-2b146087c78a.png)

The padding stays there even if I run the example to convergence.

**Comment by maxkrieger** [comment]
Coincidentally (I hadn't seen this issue), I fixed this 10 minutes ago! It was Monaco's fault, I think you resized the window and before, it didn't adapt to the container.
