### ISSUE TITLE
Kill Travis

### ISSUE THREAD

**Issue by joshsunshine** [penrose/penrose#233]
Since we're now using CircleCI instead of Travis, let's get rid of the old, broken build process so we don't see X's everywhere..

**Comment by maxkrieger** [comment]
I removed `.travis.yml` but we might still need to remove the webhook. I don't have access to it.

**Comment by maxkrieger** [comment]
I disabled everything on https://travis-ci.org/penrose/penrose/settings but can't delete it altogether. Should be enough for now @wodeni
