### ISSUE TITLE
Sugarer gives inaccurate error line numbers

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#234]
Consider the following malformed substance program:
```
Set A, B



IsSubset(A, B
AutoLabel All
```
The syntax error thrown is:
```
2:1: unexpected 'I' expecting end of input CallStack (from HasCallStack): error, called at src/Substance.hs:724:21 in main:Substance
```
Which claims the error is on line 2, when it is actually on line 5. This is because the sugarer ignores newlines.

**Comment by wodeni** [comment]
@joshsunshine suggested storing the mappings between the sugared and desugared programs explicitly to infer error source positions for now. Will look into this and probably refactor the Sugarer module. Currently there are some minor formatting issues to be fixed at least.

**Comment by maxkrieger** [comment]
Dumb hack idea: accept `;` as a newline delimeter and have the sugarer never insert newlines, only `;` characters.
