### ISSUE TITLE
Visualize Style's computational graph

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#238]
After compiling the Element/Substance/Style trio, our system outputs an optimization problem that can be represented as a computational graph visually, which should be something that our system can create itself! Here are some examples of what these graphs look like:

![image](https://user-images.githubusercontent.com/11740102/59968856-e4aaf280-950e-11e9-9b5f-33b8c300c73b.png)
![image](https://user-images.githubusercontent.com/11740102/59968859-f55b6880-950e-11e9-8e61-d28e8c2fc892.png)

**Comment by hypotext** [comment]
Some references for doing this with the graph automatically created by the new computational graph compilation:

https://github.com/penrose/penrose/blob/master/penrose-web/src/types/types.d.ts#L623
https://github.com/penrose/penrose/blob/master/penrose-web/src/types/types.d.ts#L636
https://github.com/penrose/penrose/blob/master/penrose-web/src/types/types.d.ts#L688

**Comment by hypotext** [comment]
@maxkrieger I was thinking of working on this issue (visualizing the computational graph) for Thursday, and adding an inspector tab to do this. Maybe we can pair on doing this (as well as debugging the existing opt tab) during Wed's team meeting? Any recommendations for a graph library?

Design considerations:
* Graph should be zoomable as it may be very large
* Library needs to do layout and drawing
* cola-style node grouping is a plus

After poking around, I was considering using this library: https://js.cytoscape.org/

These are their closest examples to what I'm looking for for Style: (from the homepage)
* https://ivis-at-bilkent.github.io/cytoscape.js-fcose/demo/demo-constraint.html
* http://wineandcheesemap.com/

Let me know what you think!

**Comment by maxkrieger** [comment]
sounds good @hypotext
