### ISSUE TITLE
Better optimization debugging tools

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#25]
In frontend, show toolbar with some of the following:

* Value of state
* Energy over time
* Gradient norm over time
* Exterior point method weight and iteration
* Unconstrained optimization progress
* Line search progress
* Debug values for pre-NaN fixing
* The (projected) energy landscape of the optimization problem, sample diagrams in valleys and peaks, and paths along the energy landscape
* Line search parameters
* Are there other quantities we can visualize to help debug the opt? e.g. Tensorboard and [Edward](http://edwardlib.org/tutorials/tensorboard)

With adjustable parameters, e.g. `a` and `b` in line search.

Notes:
* Probably the constraints are what's making the opt problem hard, so focus on those
* Show energy or loss (or other metrics) on the diagrams themselves, as they change over time
* For example, highlight the areas on the diagrams where the constraints are the most violated, and highlight directions of steepest ascent/descent for various objective/constraint functions

(Could the design of optimization visualization/debugging UIs be a research question in itself??)

**Comment by hypotext** [comment]
(Related to #120.)

@maxkrieger I'd like to start working on this issue soon, since @nimoni and I are running into a lot of unexpected slowness when laying out diagrams with more shapes/parameters, and understanding the behavior of the optimizer better will help us debug this problem. 

How would you like to coordinate on this? I'm happy to start learning React and figure out how to write a component. Is there more I should know beyond this [wiki page](https://github.com/penrose/penrose/wiki/React-Rendering-Frontend)?

**Comment by maxkrieger** [comment]
@hypotext I believe the main roadblock of this is that it would be a lot of refactoring in the backend to pull out information about the optimizer (cc @nimoni). The wiki page should be a decent intro to the frontend workflow, I'm guessing you can put most of the graphs and widgets below the canvas component and we can use a localStorage key to toggle it. That said I'd be happy to help write these components in the meantime and I'll be free to pair after I get back on the 13th.

**Comment by hypotext** [comment]
@maxkrieger If you'd like to start working on this, it would be very welcome, as I'm also working on domain implementation in the meantime. I see two ways to move forward:

* Starting soon: I can describe in more detail the kinds of information I'd like to surface, then you can set up and plug in a skeleton component and hand it off to me, then I can figure out how to get the right data out of the system and into the component. 
* Or, we can all wait until after the 13th and then start pairing, so we can pool your frontend knowledge with Nimo's system knowledge and my optimization knowledge. 

What do you think?

**Comment by maxkrieger** [comment]
@hypotext I can definitely work on the more time-consuming or reusable skeleton components over the next 1.5 weeks, and we can iron out what's left as a group. It sounds like the hardest component is the energy landscape.

**Comment by hypotext** [comment]
@maxkrieger Starting on the skeleton components sounds great. I'll sketch something out tonight and send it to you.

Yeah, showing the energy landscape would be 1) very cool 2) definitely a stretch goal, not top priority. I'm not sure how to visualize the energy landscape clearly for optimization problems in more than two or three dimensions.

**Comment by maxkrieger** [comment]
Some preliminary library research:

**Comment by maxkrieger** [comment]
[ ] @wodeni mentioned that the old frontend had a basic debugging overlay with bezier control points, etc, which I can add sometime in the near future.

**Comment by maxkrieger** [comment]
Somewhat related: #212
