### ISSUE TITLE
innerProduct Broken

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#250]
This includes the syntactic sugared `<x,y>` version.
```
VectorSpace U

Vector A ∈ U
Vector B ∈ U

Scalar c := innerProduct(A,B)

Label A $\vec{u_{1}}$
Label B $\vec{u_{2}}$
AutoLabel U
```
Causes the error
```
Cannot find function "calcVectorsAngleCos" CallStack (from HasCallStack): error, called at src/Penrose/Functions.hs:1867:21 in penrose-0.1.1.1-KWQoTRZY50QIFUQaG3BaSs:Penrose.Functions
```
Looking closer at `Functions.hs`, it seems like `calcVectorsAngle` and `calcVectorsAngleWithOrigin` are the closest functions in resemblance. Not sure if it's as simple as a string replacement to fix.

**Comment by joshpoll** [comment]
Closing since `Functions.ts` now includes [`dot`](https://github.com/penrose/penrose/blob/dbf710646bcaad9f0e3142388ae4759ca6b3a740/packages/core/src/contrib/Functions.ts#L190).
