### ISSUE TITLE
Request to be able to edit Domain and Style program in IDE

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#253]
@keenancrane and I are testing the user/developer in the experience in the IDE and think it would be really helpful to be able to edit the Domain and Style programs there. It would also be helpful for demoing the system to people.

**Comment by maxkrieger** [comment]
Happy to prioritize this after I get back!

**Comment by hypotext** [comment]
Thanks! Let's discuss the idea with @joshsunshine and @wodeni first.

**Comment by maxkrieger** [comment]
Notes from bumping into @wodeni:

- [ ] Toggle panes for sty/domain editors
- [ ] If you "fork" stys/domains in your workspace, save those in the gist too
- [ ] Rewrite the notion of a workspace (in localStorage) to include multiple workspaces (localStorage model). As in, add a tab in the gallery for "my workspaces". Make clear which are synced to github gists and which aren't.
- [ ] Generate thumbnails in this for gist

**Comment by maxkrieger** [comment]
All set! Closing.
