### ISSUE TITLE
Discrete vs. continuous solvers

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#261]
Many of our plugins are discrete solvers that generate Substance objects given Substance "constraints". These discrete solvers, however, sometimes depend on the result from the numerical solver (i.e. the layout optimizer). For instance, in raytracing, the regex expander might need to be parameterized by the size of the container or the canvas size. The numerical solver also depends on the translation and thereby the output of the discrete solver. How do we break the circular dependency here?

Some ideas:

* The numerical solver can first generate some default values to invoke the discrete solver
* The discrete solver may operate on a lower level of abstraction (i.e. on GPIs in Style instead of Substance statements), but we need to think about how to maintain the semantics from the upper levels.

**Comment by joshsunshine** [comment]
Make plugins great again. #653
