### ISSUE TITLE
Add a layer keyword

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#264]
Currently the syntax for layering looks like this:

```
LOCAL.layering  = x.shape above y.shape
LOCAL.layering1  = y.text below x.shape
```

This syntax is ugly for two reasons:

1. it uses the LOCAL keyword, and, more importantly,
2. it requires the programmer to invent a name for each layering statement, which is never subsequently used.

Better would be to just allow a `layer` keyword that assumes local scope.  I.e.,

```
layer x.shape above y.shape
layer y.text below x.shape
```

The compiler can of course just expand this keyword into something that looks like the previous code, by generating a list of consecutive names (`LOCAL.layering1`, `LOCAL.layering2`, etc.).  So in a sense this is just a sugared version of the existing syntax.

**Comment by hypotext** [comment]
Resolved in #317 (except for porting old programs)
