### ISSUE TITLE
Renderer build regression

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#265]
Hey @maxkrieger, I think the latest commit 1c3fbaa0a might have introduced a build regression in the renderer. When I go thru the usual build process on the latest commit I get this error:

```
Failed to compile
./src/module.tsx
Attempted import error: 'IEditorEvents' is not exported from './Protocol'.
This error occurred during the build time and cannot be dismissed.
```

However I don't get this error when I build the renderer using the commit HEAD~1.

**Comment by maxkrieger** [comment]
Sorry about that, what a weird issue (https://github.com/babel/babel/issues/8361). I'm going to set up CircleCI tomorrow to catch these things.
