### ISSUE TITLE
Add 3D style for set theory

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#269]
From @keenancrane:

In our meeting today I raised the question of how to cook up some examples where people won't say, "What's the point? I could just do that by hand."

One way to construct this kind of example is to make it more complicated, i.e., more pieces that have to be arranged in an intricate way.  That we should be able to do by writing some more elaborate Substance programs.

Another axis that we haven't really explored—but is probably worth doing at least one example for the paper—is amping up the aesthetics in a way that is superficial at a programmatic level, but a pain to execute by hand.  For example, I took Nimo's latest subset diagram, and added some nice shading, styling, etc.:

![image](https://user-images.githubusercontent.com/2762356/66143117-a4aadf80-e5d4-11e9-974f-910b9e8e0e51.png)

In Illustrator, this was a pain in the butt and took me ~20 minutes.  In Penrose, this is a simple matter of drawing a pre-baked semi-transparent SVG file on top of the existing circles.

![image](https://user-images.githubusercontent.com/2762356/66143131-aa082a00-e5d4-11e9-8107-b05509ab40ba.png)

Seeing this kind of example in the paper could go a long way toward giving people the impression that you can do some really sophisticated, nice-looking stuff in Penrose—and not just something you can easily do in tools like TikZ, Inkscape, etc.

P.S. The other tweak I made was making the text size a fraction of the disk size.  This is trivial in Style, but painful by hand.  In general this sounds like a good mantra when thinking about things to do with examples for the paper:

_"Trivial in Penrose; painful by hand"_

**Comment by wodeni** [comment]
Resolved in #273.
