### ISSUE TITLE
Generate diagrams of algorithms and data structures from code

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#27]
e.g. linear algebra and mesh diagrams, or see L. Kuper's comment on Twitter.

**Comment by hypotext** [comment]
Substance currently only has static visual semantics because there is no evaluation model or control flow. Think about how we might give it a _dynamic_ visual semantics so that we can model and visualize processes, e.g. Markov chain convergence, dynamical systems, and mesh algorithms.

**Comment by samestep** [comment]
This seems to relate to #134 perhaps?
