### ISSUE TITLE
Renderer socket error

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#274]
On the `paper-example` branch, I sometimes get this error in Chrome (fairly often) and need to close this tab and reopen the renderer. Not sure how to repro.

```
Protocol.tsx:33 WebSocket connection to 'ws://localhost:9160/' failed: Unknown reason
Protocol.setupSockets @ Protocol.tsx:33
_this.ws.onclose @ Protocol.tsx:39
browser.js:96 renderer:info Connection status: SOCKET_ERR +3ms
browser.js:96 renderer:info Connection status: SOCKET_ERR +1ms
...
```

**Comment by wodeni** [comment]
My naive guess is that the previous ws connection was not closed entirely when the new tab tries to connect? If that's the case, `penrose editor` should now have the same problem, as it accepts multiple concurrent clients. @maxkrieger may have a better idea about the behavior of the `Protocol` module.

**Comment by maxkrieger** [comment]
Can't repro right now but whenever I've gotten similar-ish errors I set the
`--domain` flag for the penrose binary explicitly to "localhost" or
"127.0.0.1"

**Comment by hypotext** [comment]
Obsolete
