### ISSUE TITLE
Can't export to SVG/PDF with an imported SVG

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#275]
On my branch, with path `runpenrose examples/geometry-domain/teaser.sub examples/geometry-domain/hyperbolic.sty examples/geometry-domain/geometry.dsl` when I try to export to PDF or SVG, using this SVG as import: https://upload.wikimedia.org/wikipedia/commons/9/9e/Ideal-triangle_hyperbolic_tiling.svg

I get this result:

[Penrose.pdf](https://github.com/penrose/penrose/files/3719849/Penrose.pdf)

but it should look more like this: https://github.com/penrose/TOG-2019/issues/5#issuecomment-541249735

Thoughts on why this is happening? I'd like us to prioritize this bug since it involves the diagram iteration process.

**Comment by wodeni** [comment]
Do the SVG and PDF exports have the same anomalies? We used to have missing images/transforms before, but I thought the issues were resolved and the new 3D style works fine when exported. 

Also, I was trying to use the deployed IDE to quickly look at it, but the hyperbolic example failed with the following:
```
Cannot find function "pathToDiskAndScreen" CallStack (from HasCallStack): error, called at src/Penrose/Functions.hs:1876:21 in penrose-0.1.1.1-KWQoTRZY50QIFUQaG3BaSs:Penrose.Functions
```

**Comment by hypotext** [comment]
Yes, the svg and pdf have the same anomalies.

The deployed ide doesn’t work for this domain because I made changes to the
Penrose system on this branch, which are not reflected on the master
branch, so the deployed ide is still running an old version w/o the missing
function.

**Comment by wodeni** [comment]
A couple of things I learned after looking into this:

First, I was able to fix the size issue by setting a viewBox on the imported image: 
```svg
<svg
    xmlns="http://www.w3.org/2000/svg" version="1.1"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width='800.0' height='800.0' viewBox="0 0 800 800">
```
Without a defined viewBox, I think the child elements are going to have absolute coordinates.

Second, setting the `opacity` of the image is going to work in the renderer, but not the exported version, as we are not exporting the attributes when converting the diagram into a standalone SVG, which is a (surprisingly) weird process. For now, you should style the imported image yourself to make sure the export is consistent with the rendered version. 

Finally, I double-checked the layering of the exported SVG elements. Seems okay. 

Anyway, hope this helps!

**Comment by hypotext** [comment]
Thanks @wodeni, fixed! Somehow I didn't realize that original exported PDF contained an unscaled version of the original SVG---it just looked like some kind of path problem.
