### ISSUE TITLE
Parse nested predicates in Style

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#279]
I believe the Style parser hasn't been updated to work with nested predicates. @wodeni could you look into this? I can handle the matching part after the parsing works.

Repro: 

On branch `sets-functions`, do `runpenrose functions-domain/spec-function.sub functions-domain/continuous.sty functions-domain/functions.dsl` with any selector changed to use a higher-order predicate, for example:

```
Map f
with Set domain; Set image
where From(f, domain, image); Surjection(f); Not(Injection(f)) {
 ...
}
```

This results in a Style parser error:

```
penrose: StyleParse "141:5:\n    |\n141 | Map f\n    |     ^\nunexpected 'f'\nexpecting '{'\n"
CallStack (from HasCallStack):
  error, called at src/Penrose/ShadowMain.hs:90:23 in penrose-0.1.1.1-48BPgk0PsSLLYhNgmgMMI9:Penrose.ShadowMain
CallStack (from -prof):
  Penrose.ShadowMain.penroseRenderer (src/Penrose/ShadowMain.hs:(84,1)-(106,45))
  Penrose.ShadowMain.shadowMain (src/Penrose/ShadowMain.hs:(63,1)-(80,79))
```

**Comment by wodeni** [comment]
Fixed in 66e8e8a721b1376f7b428be2eee047d15b90a097
