### ISSUE TITLE
Variable names in Substance affect the diagram layout for linear algebra

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#280]
There's a strange bug where variable names in substance affect the diagram layout in a way that's clearly broken (i.e. misplaced labels). If the variables were uniformly renamed, the diagram layout might change, but it should not break.

Repro: On the `sets-examples` branch, run the two versions of `oneVector.sub` with `linear-algebra.sty` and `linear-algebra.dsl`.

Thoughts:

* Does the presence of upper/lowercase, numbers, and single vs. multiple letters matter?
* Diff the resulting output translations and see what changes there are. It seems like maybe an objective/constraint is not being applied via cascading?
* The variable names might influence the ordering of the shapes in State? (Nimo)

TODO: attach images

**Comment by wodeni** [comment]
Can't repro this anymore. Closing for now.
