### ISSUE TITLE
Show visual feedback about whether all the constraints were satisfied and objectives were minimized

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#281]
Currently feedback on whether the constraints are satisfied is shown in the frontend.  But these are just boolean values ("yes" or "no") in a long plain-text list, which can be hard to debug for diagrams with many constraints.

It would be very helpful to show constraint violations visually.  E.g., "draw a red rectangle around everything in the block if it's violated."

Would also be good to think about how to visually show energy levels for each penalty term, in the diagram itself.

This issue is reminiscent of the "optimization transparency/debugging UI" (#25) that we prototyped earlier.

**Comment by hypotext** [comment]
We can also provide feedback about individual objectives, to help with debugging. (See 2/11/21 meeting notes)

**Comment by wodeni** [comment]
Closing because #534 partly addresses this, and in-diagram feedback is not high priority for now. Collected in #653
