### ISSUE TITLE
Uniquely specify points that are in the image of a function with Alloy plugin

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#289]
From Slack:

I have a quick request for the functions plugin. Can you extend it to output a predicate on each point that is in the image of `f`?

If, for example, `f(x1) = y1` and `f(x2) = y1`, it would just generate the one predicate `InImage(f, y1)`. On the other hand, if there's some point `y2` that is in the codomain of `f` but not the image, it doesn't generate any predicate. 

The reasoning behind this is that the Style needs to be able to select each point that's in the image of `f`, but the current predicates are not expressive enough. Since the `PairIn` predicate is generated once for each domain point, using that predicate produces too many matches. This is needed for the hue optimization in https://github.com/penrose/TOG-2019/issues/11

---

How the predicate will be used:

Current Style program:

```
Point q1; Point q2 -- All points in codomain that get mapped to
with Point p1; Map f; Point p2 
where PairIn(p1, q1, f); PairIn(p2, q2, f) {
    LOCAL.hueDistFn = encourage repel(q1.hue, q2.hue, 1.0, "angle")
    -- TODO: a point in the codomain will get matched more often (and hence receive extra repel objectives) if multiple points map to it
}
```

Ideal Style program:
```
Point q1; Point q2
with Map f
where InImage(q1, f); InImage(q2, f) {
    LOCAL.hueDistFn = encourage repel(q1.hue, q2.hue, 1.0, "angle")
}
```

---

Another option is to add more expressive Style language constructs for filtering matches, but arguably this problem is more easily addressed at the domain/predicate/plugin level for now.

**Comment by wodeni** [comment]
Added the `InImage` predicate generation in the Alloy example. For instance:

* Substance program:
```
f: A -> B
Not(OneToOne(f))
Onto(f)

AutoLabel All
Label A $x$
Label B $f(x)$
```
* Generated Substance program:
```
Point A_0
In(A_0, A)
Point A_1
In(A_1, A)
Point A_2
In(A_2, A)
Point A_3
In(A_3, A)
Point A_4
In(A_4, A)
Point B_0
In(B_0, B)
Point B_1
In(B_1, B)
PairIn(A_0, B_1, f)
PairIn(A_1, B_1, f)
PairIn(A_2, B_1, f)
PairIn(A_3, B_0, f)
PairIn(A_4, B_0, f)
InImage(B_0, f)
InImage(B_1, f)
```
* The output (@hypotext lmk if it look okay):
![image](https://user-images.githubusercontent.com/11740102/68548657-71225880-03bd-11ea-9557-ff69058304b8.png)

**Comment by hypotext** [comment]
Looks great, thanks for the quick response @wodeni
