### ISSUE TITLE
Make Style selectors more expressive to express distinctness, permutations, and more

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#290]
Keenan and I worked out several features to add to Style selectors to make them more expressive. In addition, these features all have a nice grounding in what people actually say in mathematics, which feels simple and principled.

## Motivating example

![image](https://user-images.githubusercontent.com/2762356/68678320-be243d00-052b-11ea-9ed1-59164ca641a3.png)

Imagine trying to draw a diagram of a complete graph, with or without self-loops, and with a legend. You would want to do the following:

* draw an edge between every pair of distinct vertices
* draw a self-loop for every single vertex (and itself)
* draw a legend if a kind of element exists in this example

These translations can be expressed with the following selectors:

Domain: `Type V, E`

```
forall (V x, V y)
s.t. Distinct(x, y) {
   local.shape = Line { ... }
}

forall V x {
   local.shape = Path { ... }
}

exists V x {
   legend.shape1 = ...
}

exists E e {
   legend.shape2 = ...
}
```

## Permutations vs. combinations

Sometimes the Style-writer wants to match every permutation of names for a type. Sometimes they want to match every combination of names. The idea is to allow matching permutations via a list syntax `[T x, T y]` (matches `a, b` and `b, a`) and to allow matching combinations via a set syntax `(T x, T y)` (only matches `a, b`).

## Distinctness and identity

When enumerating tuples, the mathematically right thing to do includes matching the same object twice: `(T x, T y)` also matches `a, a`. That's usually (but not always) undesirable behavior, because visually, we often want to special-case something based on identity. So, matching objects with the same identity can be disallowed by applying the `Distinct` predicate to **two or more** objects.

## Composing the features

The selector in the example above:

```
forall (V x, V y)
s.t. Distinct(x, y) {
   local.shape = Line { ... }
}
```

only matches all unique pairs of vertices where the vertices are distinct from each other.

## Forall 

From Keenan:

A long time ago we discussed whether we could and should have expressions like “there exists” and “for all” in Penrose.

Inadvertently, we have the latter—the universal qualifier ∀ (“for all”)—but do not currently make this statement explicitly.

In particular, every pattern match in Style has the form

```
For all (...)
Such that (...) {
   Do something
}
```

In keeping with the idea that Penrose should adopt familiar mathematical notation, I would be very much in favor of allowing these statements explicitly in Style. For instance, being able to write

```
forall Set X, Set Y
where Subset(Y,X) {
   ...
}
```

Is the keyword “forall” absolutely necessary? Clearly not: we’ve gotten away without it so far!

But it does a service to the programmer: it makes the meaning of this code crystal clear. This pattern will match on *all* instances that satisfy the conditions.

It would also be very much in keeping with our “user-friendly” keywords like “ensure,” “encourage”, “then,” etc.

And, I would imagine, comes with very little implementation burden: if the statement “forall” appears at the beginning of a block, ignore it! (That way we preserve backward compatibility with existing Style files).

Would also be fine to allow the Unicode sugar “ ∀” in addition to “forall”

## Exists

And thinking about this just a moment longer: It is also extremely natural to have existential quantifiers in Style. For instance, a block like

```
exists Type x {
   ...
}
```

could be used to do something like, “if there are any objects of type Type in the Substance, draw a *single* shape related to all of them.” Say, a single box around the diagram if it contains *any* points at all.

This obviously takes more implementation effort. But it’s so natural (drawing just one thing if any particular match shows up) I’m surprised we didn’t stumble across it before...

Addition from discussion: the selector should be allowed to refer to objects by name (so it can apply predicates to them). However, the block following it should not be allowed to refer to those names, because all it needs to know is the existence of an object.

## Lists

We didn't discuss this feature, but a past issue proposes a selector feature that would come in handy for colors, labels, and more:

Does Style need a "for all?" (in this case, the ability to pull in a whole list of matched things) #177 

## Implementation of the above

Not yet worked out. Forall and exists should be easy. 

Permutation and uniqueness need to be done more carefully. I believe the current Style compiler explicitly rules out the special case of `T x; T y` matching the same name twice. This needs to be worked out for different types. See #287 for further discussion.

## Related discussions

Issues #177, #287 

"We have universal qualifiers in Penrose" ([Google Groups discussion](https://groups.google.com/forum/#!topic/penrose-team/s6ZEKYYwF7M))

There are also some old notes about adding the `?=` operator in Style to check distinctness, which I can't find now.

**Comment by keenancrane** [comment]
Another pragmatic addition would be the qualifier ∄, i.e., "does not exist," which enables a Style programmer to define a block that is instantiated only in the absence of a given match.  The first example usage that comes to mind (though surely not the only one!) is just enabling the Style writer to provide visual warnings.  E.g., in the context of a package for graphs:

```
notexists Vertex v {
   local.shape = Text {
      string: "Graph has no vertices!"
   }
}
```

**Comment by keenancrane** [comment]
A natural follow-up is then to provide a more complete first-order logic that provides, e.g., conjunctions and disjunctions.  For instance,

```
-- if the graph has vertices but not edges, draw all vertices in red
-- to indicate that something fishy may be happening…
∃ Vertex v and ∄ Edge e
{
   Color.vertexColor = rgba( 1., 0., 0., 0. )
}
```

**Comment by JonathanAldrich** [comment]
Our existing design essentially allows nesting an exists within a forall; this is often needed and something we should be sure to support.

If matching the same object twice is usually undesirable, are we sure we want that to be the default?

**Comment by keenancrane** [comment]
> If matching the same object twice is usually undesirable, are we sure we want that to be the default?

The "principle of least" surprise would seem to dictate that it's the right thing to do: in mathematics the statement "for all x,y in A" includes the case x = y.  So if we use the keyword "forall", a programmer will probably expect this behavior.

**Comment by JonathanAldrich** [comment]
True.

**Comment by keenancrane** [comment]
Just wanted to send a message from the year 2021 (almost 2022…) that an `exists` keyword in Style would still be **super** helpful (along with the other things in this discussion).

As of today, there's still no way to draw, say, a legend or box if at least one instance of some type exists.

**Comment by keenancrane** [comment]
Note: the symmetric aspect is elaborated on in #744.

**Comment by joshsunshine** [comment]
@liangyiliang there are several pieces of discussion in this issue, including `exists` and lists that are relevant to you.

**Comment by liangyiliang** [comment]
Just to clarify, say we have an `exists` block. We want this to be matched and triggered _at most once_, right? @keenancrane

**Comment by liangyiliang** [comment]
The distinction between _permutation_ and _combination_ seems a lot like the distinction between _ordered_ and _unordered_ matching. Our current methodology performs _combination_ matching. If it sees _(a, b) => (A, B)_, then it does not consider _(a, b) => (B, A)_, except if the matched relations are different.

**Comment by joshsunshine** [comment]
Yes, @liangyiliang, `exists` selectors should match at most once.

**Comment by keenancrane** [comment]
This is a big issue, with lots of thoughts, and we never really fleshed out just the `exists` keyword.

There are three things I can think of that you would want to do after writing `exists`:

1. Just draw something that doesn’t depend on any particular instance of the matched type(s).  E.g., if there exists any vectors at all, draw some coordinate axes.  I don’t need to know about any particular vector to do this.
2. Do something with one particular instance.  E.g., put a constraint on just one vertex of a graph (pin it to the origin, say).
3. Do something with all instances that match the pattern.  E.g., take a sum or product over all instances.

What syntax supports these use cases?

For (1), nothing needs to be done: if the `exists` match happens, I can just start defining shapes, constraints, objectives, etc., as usual.

For (2), I need to be able to refer to a particular instance.  An easy proposal would be that if I write
```
exists Type1 a; Type2 b
where Predicate(a,b) {
 ...
}
```
then I can just reference `a` and `b`  in that rule as usual.  These statements will get applied to one particular instance—with no guarantees about which instance I get.

For (3), which is the most interesting case, we need to introduce some new syntax.  My proposal is
```
exists Type x {
   vec2 center = (1/match_total) match_sum( x.icon.center )
}
```

The keyword `match_total` is already implemented (thanks to @liangyiliang), and in this case (as with `forall`) gives the number of times the given pattern matches in the Substance.

The keyword `match_sum` is a new Style keyword that takes a sum over all instances `x` that match the pattern.

We have badly needed the summation feature for a long time.   We have also wanted an `exists` keyword for a long time.  Maybe this is a good way to kill two birds with one stone.  I suspect that this solution to summation is also the most palatable from a functional language point of view—especially compared to other proposals we’ve had in the past.  We’re not mutating a value (with `+=` or something).  Rather, we’re defining a single quantity, once, in an immutable way.

I would also propose we have `match_product` , which takes the product over all the matches.  If we wanted to get fancier in the future, we could implement more general “match map/reduce” operations.  But I bet this already gets us quite far for real diagramming, and is an easy way to test the waters without going overboard.

**Comment by wodeni** [comment]
> 1. Just draw something that doesn’t depend on any particular instance of the matched type(s).  E.g., if there exists any vectors at all, draw some coordinate axes.  I don’t need to know about any particular vector to do this.
> 2. Do something with one particular instance.  E.g., put a constraint on just one vertex of a graph (pin it to the origin, say).

Practically, it's fairly easy to support these two use cases because the semantics are quite simple: match on just one instance and proceed as usual. 

> 3. Do something with all instances that match the pattern.  E.g., take a sum or product over all instances.

First, this sounds like something you would do under a `forall` selector? Also, I don't feel like `match_*` values/functions make much sense here. Notably, `match_id` and `match_total` will be both `1` if we use the existing semantics, i.e. how many matches did the Style compiler produce. I prefer the proposal in #1279 for the example:

```
forall Type x {
   vec2 c = total( x.icon.center ) / match_total
}
```

**Comment by samestep** [comment]
Closing in favor of #1469. If there's other stuff in this issue not covered by that one, let's open separate issues for those.

**Comment by keenancrane** [comment]
I'm reopening, since #1469 discusses just `exists`, whereas this issue discusses several features (permutations vs. combinations, distinctness and identity, composing the features, lists).  I'm not 100% sure this whole list has been resolved, though pieces of it surely have.  Let's carefully comb through this issue + closed PRs/other open issues before finally closing it.

**Comment by keenancrane** [comment]
I think we can close this now.
