### ISSUE TITLE
Add constraint-driven UI controllers for non-spatial attributes of a diagram

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#291]
e.g. hue wheels for color:

![image](https://user-images.githubusercontent.com/2762356/68718315-db322d80-0576-11ea-804f-eb36f91f7373.gif)
![image](https://user-images.githubusercontent.com/2762356/68718445-467bff80-0577-11ea-950e-9bbcc0f8cc6c.gif)

Ideally the user can manipulate these while preserving the objectives/constraints on the non-spatial attributes as well.

Related:
https://github.com/penrose/TOG-2019/issues/12#issuecomment-553158769
https://github.com/penrose/TOG-2019/issues/11#issuecomment-553159286

**Comment by maxkrieger** [comment]
We can definitely re-architect https://github.com/penrose/penrose/wiki/Debugging-Graphically to support this
