### ISSUE TITLE
Frontend crashes when label text is an empty string

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#294]
## Issue

The frontend crashes when label text is an empty string. I think this happens because MathJax doesn't render the label if the string is empty. So when later the frontend looks for something like `v1.text`'s property `h`, the frontend can't find that shape `v1.text`, and then crashes because it doesn't handle the error.

See commit where I added error-reporting code to the frontend: https://github.com/penrose/penrose/commit/3bf9950d7f4ea11417045d857353aa436c42038b

## Desired behavior

In any Style program, would like to be able to make a Text GPI with property `string : " "`. 

## Workaround

Currently, I write this in Style, which seems to successfully make a text GPI with "special empty text" to get around the problem:

`Text { string: "\\text{ }" }`

## Repro

In any Style program, try to make a Text GPI with property `string : " "`. 

Or you can check out commit https://github.com/penrose/penrose/commit/3bf9950d7f4ea11417045d857353aa436c42038b on branch `mesh`, and do `runpenrose mesh-domain/Figure1.sub mesh-domain/SimplicialComplex.sty mesh-domain/mesh.dsl`, with line 129 instead of 128 in the mesh style.

**Comment by wodeni** [comment]
Fixed in #553
