### ISSUE TITLE
Labels aren't added to Substance object in translation without existing match

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#302]
If a Substance object `X` hasn't been created in the translation (i.e. hasn't been matched), then attempts to refer to its label `X.label` elsewhere in Style will fail, because the label doesn't seem to be added to the translation if `X` doesn't already have a mapping. 

TODO: add repro instructions / fix on `mesh` branch

**Comment by joshsunshine** [comment]
We should investigate this.

**Comment by wodeni** [comment]
I was able to repro this. See the following example

https://panes.penrose.ink/gist/c98fae02ac54453d06f2dd985a219224

```
canvas {
  width = 800
  height = 700
}

-- Uncomment this block to make it work
-- forall Set x {
--     x.icon = Circle {}
-- }

forall Point x
with Set y {
    x.text = Text {
        -- trying to make `x`'s GPI have the label string of `y`'s label. Error: "Error looking up path 'A.label' in translation. Name 'A' does not exist."
        string : y.label
    }
}
```
