### ISSUE TITLE
Support export to TeX with labels

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#303]
Currently we dump labels as part of the output image itself, which is useful in contexts where the image will be used directly.  When the image is meant to be used as a figure in a TeX document, it would be nice to actually typeset the labels via TeX itself.  This can be done via the [`overpic` package](https://ctan.org/tex-archive/macros/latex/contrib/overpic?lang=en), which superimposes TeX math over a PDF image.

Here's an example:

```
\begin{overpic}{images/ddg_surface_patch.pdf}
   \put(210.6387,134.2822){\(f\)}
   \put(64.3818,33.7637){\(X\)}
   \put(428.127,64.626){\(f(M)\)}
   \put(116.3086,27.2295){\(M\)}
   \put(344.8896,62.5127){\(\dfX\)}
   \put(377.1357,99.0137){\(N\)}
\end{overpic}
```

This TeX code will display the image `ddg_surface_patch.pdf`, and then place the given labels on top of it at the specified (x,y) coordinates (see `overpic` docs for details).

To incorporate this into Penrose we need to make a few small changes:

- Don't output label images in the final SVG
- Output a TeX file with the (x,y) coordinates and label strings, following the `overpic` example above
- Make sure to perform the correct conversion from the Penrose coordinate system to the TeX/PDF coordinate system, namely: (i) all coordinates should be relative to the corner of the document, and (ii) the scale between Penrose units and PDF units should be properly accounted for

(It's really this last bullet point that will likely be most painful to get right…)

**Comment by maxkrieger** [comment]
> all coordinates should be relative to the corner of the document

To clarify: do you mean the host letter-size document or the diagram? If it's the former, that doesn't seem very portable, I'd expect there to be a way to make the coordinates relative to the figure environment.

**Comment by hypotext** [comment]
> To clarify: do you mean the host letter-size document or the diagram (exported to PDF)?

I believe it's the latter.

**Comment by wodeni** [comment]
Also marking this as a good first issue because the implementation will only touch the renderer and the IDE.

**Comment by wodeni** [comment]
Another option is to run a naive Penrose binary in the TeX engine :p

**Comment by keenancrane** [comment]
It seems that a similar solution to the [overpic](https://ctan.org/pkg/overpic?lang=en) proposal is already provided by the [LaTeX svg package](https://ctan.org/pkg/svg?lang=en), which in turn invokes a [PDF+LaTeX export](https://wiki.inkscape.org/wiki/index.php/LaTeX#How_to_turn_an_Inkscape_drawing_into_an_editable_LaTeX_document) from Inkscape.  In fact, the `svg` package is just a lightweight wrapper around the Inkscape invocation

```
inkscape -D -z file=image.svg export-pdf=image.pdf export-latex
```

which generates both a PDF image without text, and a `.tex` file that superimposes text on the image via the [built-in LaTeX picture environment](https://www.overleaf.com/learn/latex/Picture_environment) (rather than overpic).  Using the `svg` package, including SVGs generated by Penrose is as simple as

```
\includesvg{penrose-diagram.svg}
```

The [svg-inkscape example](https://ctan.org/tex-archive/info/svg-inkscape) has some very useful information about text placement, etc.

To make the path from Penrose -> TeX fully automatic, there are still a few things we need to do:

**1. Automatically convert all `Equation` shapes to `Text` shapes, replacing the string `S` with the string `$S$` so that it gets typeset as math when imported into TeX.  (Note that with this conversion, existing `Text` shapes are unaffected will still get rendered properly within TeX.)**
2. Fix an issue with bounding boxes for embedded SVGs.  Basically the way that the Penrose renderer currently includes SVGs is to simply dump a copy the entire SVG (including `<svg></svg>` tags) into the output.  This confuses Inkscape, resulting with the wrong size bounding box in the converted PDF, and in turn, large extra white space between figure and caption (see below).

Even just providing (1) would already be a big leap forward for Penrose -> TeX interoperability.

<img width="902" alt="image" src="https://github.com/penrose/penrose/assets/3604525/ae2f4017-0b45-4196-9c26-e6e5e4370f51">

**Comment by keenancrane** [comment]
It seems one way around the bounding box issue is to invoke Inkscape with a `-C` flag instead of `-D`:

```
-C, --export-area-page                     Area to export is page
-D, --export-area-drawing                  Area to export is whole drawing (ignoring page size)
```

This flag can be invoked by using the `inkscapearea=page` option for the `svg` package.

Here's a complete example:

```
\documentclass{article}
\usepackage[charter]{mathdesign} % match document font to label font used in Style program
\usepackage[fontsize=9pt]{scrextend} % match document font size to label font used int Style program
\usepackage[inkscapearea=page]{svg} % import SVGs with same document size as specified in SVG

\title{Import Penrose-generated SVG into \LaTeX}
\date{}

\begin{document}

\maketitle

\begin{figure}[h!]
   \centering
   \includesvg{figure.svg}
   \caption{Imported from Penrose, via \texttt{svg} package/Inkscape}
\end{figure}

\end{document}
```

Here's the input SVG (rendered in Chrome):

<img width="713" alt="image" src="https://github.com/penrose/penrose/assets/3604525/d4c7d633-59cc-4501-9844-e3da88735fc8">

Here's the output (rendered as a PDF in Mac OS X Preview):

<img width="598" alt="image" src="https://github.com/penrose/penrose/assets/3604525/26044d34-fc82-44f6-a2ce-f5fab917955d">

**Comment by keenancrane** [comment]
One small-but-important feature that would also be nice to support is stroking math text, which we are also trying to restore in #1420.  The Inkscape conversion likewise does not attempt to preserve stroked text. However, it seems stroked math can be achieved in TeX via the following steps:

1. Export SVG from Penrose (with or without stroked text).
2. Perform a "manual" SVG -> PDF+TeX conversion, i.e., run `inkscape -C -z file=image.svg export-pdf=image.pdf export-latex`.
3. Edit the generated file `image.pdf_tex`, replacing each stroked instance of `\textit{...}` with `\contour[color]{...}` where `color` is the stroke color.

Obviously this is a tedious and brittle process; would be nice to have something more automatic.  The end result at least looks good:

<img width="550" alt="image" src="https://github.com/penrose/penrose/assets/3604525/adb958d1-fc4e-4e53-bba9-037036d262c5">

**Comment by keenancrane** [comment]
Longer-term, it would be nice to eliminate the dependency on Inkscape, and be able to directly export PDF + TeX from `roger` (and/or the IDE).  This would also give us finer-grained control over how attributes get translated from SVG to PDF/TeX (such as the font stroking described above).

One possible path here is the [jsPDF library](https://github.com/parallax/jsPDF), and in particular the fork [svg2pdf.js](url).  We would also need to generate the associated TeX, but this is not too bad—the meat of the TeX generated by `svg` looks like this (where a lot of these commands are even extraneous):

```
  \begin{picture}(1,0.83333333)%
    \lineheight{1}%
    \setlength\tabcolsep{0pt}%
    \put(0,0){\includegraphics[width=\unitlength,page=1]{figure_svg-tex.pdf}}%
    \put(0.84248765,0.23965263){\color[rgb]{0,0,0}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}\contour{white}{$x_2$}\end{tabular}}}}%
    \put(0.73425573,0.07528286){\color[rgb]{0,0,0}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}\contour{white}{$x_k$}\end{tabular}}}}%
    \put(0.42003552,0.42962395){\color[rgb]{0,0,0}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}\contour{white}{$x_0$}\end{tabular}}}}%
    \put(0.14974877,0.70129783){\color[rgb]{0.50196078,0.50196078,0.50196078}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}$\Omega$\end{tabular}}}}%
    \put(0.74261405,0.4033432){\color[rgb]{0,0,0}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}\contour{white}{$x_1$}\end{tabular}}}}%
    \put(0.79385459,0.09153233){\color[rgb]{0,0,0}\makebox(0,0)[t]{\lineheight{1.25}\smash{\begin{tabular}[t]{c}\contour{white}{$\ldots$}\end{tabular}}}}%
  \end{picture}%
```
