### ISSUE TITLE
Prose generator

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#304]
Given how nicely structured Substance code is, it wouldn't seem too hard to generate standard mathematical prose corresponding to a given Substance program.  For instance,

```
VectorSpace X
Vector x1, x2
In( x1, X )
In( x2, X )
Orthogonal( x1, x2 )
label x1 $x_1$
label x2 $x_2$
```

could become

> Let $X$ be a vector space, and let $x_1,x_2 \in X$ be orthogonal vectors.

**Comment by hypotext** [comment]
@maxkrieger If you're interested in working on this, check out our paper draft for the most recent version of the prose.

**Comment by maxkrieger** [comment]
@hypotext great! What's the timeline on this? I probably wouldn't be able to start for another 2 weeks

**Comment by hypotext** [comment]
@maxkrieger Absolutely no rush. This is more of a bucket list item!
