### ISSUE TITLE
External tools don't render Penrose-exported SVGs correctly

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#305]
In `geom` branch, doing `runpenrose geometry-domain/teaser.sub geometry-domain/euclidean.sty geometry-domain/geometry.dsl` and exporting/importing SVG with illustrator yields an incorrect result:

<img width="460" alt="Screenshot 2019-12-09 11 15 41" src="https://user-images.githubusercontent.com/2762356/70456131-8bfaf200-1a7b-11ea-85fd-386735bd7ef5.png">
<img width="460" alt="Screenshot 2019-12-09 11 15 41" src="https://user-images.githubusercontent.com/2762356/70456163-9a490e00-1a7b-11ea-86e5-9262ef298873.png">

Is this a known issue? I realize it may well be a problem with Illustrator and not our export, as it opens fine in Inkscape.

Btw, I tried to fix it by rounding numbers to 2 places for lines and arrowheads in https://github.com/penrose/penrose/commit/2ed67f42a399cc5f9a60816097310948a7f77405 but that didn't seem to fix the illustrator problem.

Related issue: https://github.com/penrose/TOG-2019/issues/16 (needed to put together teaser)

**Comment by wodeni** [comment]
My random guess is that either we didn't make the markers in a standard way or Illustrator is not handling them properly. I would look into its support for svg `<marker>`s.

**Comment by keenancrane** [comment]
The bigger meta-issue here is that Illustrator's SVG support is incomplete/imperfect.

One solution is to say: who cares, we're SVG compliant, and if Adobe isn't well then that's their problem.

A more pragmatic approach is to say: a lot of people who want to use Penrose might also like to import our diagrams into Illustrator.  So, it's to our benefit to produce output that Illustrator can read correctly.

This takes a bit of reverse engineering on our part, but basically we just need to keep tabs on SVG features that don't jive with Illustrator, and find alternative ways of exporting to SVG when those features don't work.

This is all in balance with preserving, to the greatest degree possible, editability of the diagrams.  E.g., for the sake of compatibility we could convert all paths to outlines, and flatten all grouping/transforms, but now the diagram becomes harder to tweak by hand.

**Comment by wodeni** [comment]
Related issue from the illustrator community: https://illustrator.uservoice.com/forums/333657-illustrator-desktop-feature-requests/suggestions/38634631-svg-paths-with-marker-endings-render-only-the-mark. 

Still not resolved in 2022.

**Comment by wodeni** [comment]
Closing in favor of https://github.com/penrose/penrose/issues/871 as it's a more concrete solution.
