### ISSUE TITLE
Inkscape exports arrowheads with extra markers (also missing gradient)

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#306]
On branch `geom`, most recent commit 2ed67f42a399cc5f9a60816097310948a7f77405 (even with pulled commit from master), Inkscape still exports the diagrams with extra arrowheads. In Inkscape, I composed all the SVGs together in an SVG file, then exported to PDF.

![image](https://user-images.githubusercontent.com/2762356/70457036-5b1bbc80-1a7d-11ea-9361-c46252d06d8d.png)

There is also a missing gradient on the sphere.

@wodeni Can you take a look at this? If we think Inkscape is the most viable option for composing the teaser figure, then we can just address this issue (if it's indeed a renderer problem and not an Inkscape problem). The alternative is to address #305 (the Illustrator issue). As it is, neither of our software options works fully. Fixing this would be really helpful for the teaser. Thanks!

The original source files are here: 
https://github.com/penrose/TOG-2019/blob/master/Media/teaser-510x243pt-withcontent.svg
https://github.com/penrose/TOG-2019/blob/master/Media/teaser-510x243pt-withcontent.pdf

Repro:
`runpenrose geometry-domain/teaser.sub geometry-domain/euclidean.sty geometry-domain/geometry.dsl`
`runpenrose geometry-domain/teaser.sub geometry-domain/spherical.sty geometry-domain/geometry.dsl`
`runpenrose geometry-domain/teaser.sub geometry-domain/hyperbolic.sty geometry-domain/geometry.dsl`

Related issue: https://github.com/penrose/TOG-2019/issues/16 (needed to make the teaser figure)

**Comment by wodeni** [comment]
Closing in favor of #305, where we keep track of other SVG export issues.
