### ISSUE TITLE
Show the sample number of the diagram in the renderer

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#311]
e.g. "This diagram is sample number 3 of 100, with random seed(s) 98 and 2"

This would be helpful for reproducibility, because often I see a Penrose diagram and can't remember the steps for recreating it!

**Comment by maxkrieger** [comment]
For the 3/100 part, is this data already in the state structure or should a counter be incremented separately @wodeni

**Comment by maxkrieger** [comment]
If you happen to remember the exact keys for the data off hand I can just put those right in the view!

**Comment by joshsunshine** [comment]
This is not available in the "Options" tab of the new IDE.
