### ISSUE TITLE
Revise syntax for named parameters in Domain functions/predicates

### ISSUE THREAD

**Issue by GeometryCollective** [penrose/penrose#312]
Domain currently allows types to have names, e.g., instead of writing just

`predicate From: LinearMap * VectorSpace * VectorSpace`

one can write

`predicate From: LinearMap * VectorSpace domain * VectorSpace codomain`

However, this syntax is fairly awkward in terms of legibility.  E.g., seeing `domain * VectorSpace` juxtaposed may be jarring for someone used to a language like Haskell.  On the other hand, omitting these names altogether feels like a bad solution, since they essentially provide useful comments that give semantics to functions and predicates.

Jonathan proposes a syntax like

`predicate From(LinearMap, domain:VectorSpace, codomain:VectorSpace)`

I'm on board with this, or any variant.  To me (and I suspect others), the most natural thing would be a C-like prototype:

`predicate From(LinearMap, VectorSpace domain, VectorSpace codomain)`

But we should think about what makes most sense in Penrose.

**Comment by joshsunshine** [comment]
We're going to go with the Keenan syntax.

**Comment by samestep** [comment]
> We're going to go with the Keenan syntax.

Which one is the Keenan syntax? Is it this one?

> ```
> predicate From(LinearMap, VectorSpace domain, VectorSpace codomain)
> ```

**Comment by keenancrane** [comment]
> Which one is the Keenan syntax? Is it this one?

Yeah, and more importantly this convention is consistent with the way typed instances are declared throughout the rest of Penrose.  For instance, in Substance you write

```
TypeName instanceName
```

and in Style you write

```
forall TypeName instanceName ...
```

So it makes sense to stick with the same convention in Domain.
