### ISSUE TITLE
Provide visual feedback about violated constraints

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#314]
It would be relatively easy to provide visual feedback about constraints that fail to be satisfied by an optimized diagram.  One scheme, for instance, is to

1. evaluate each constraint to see if it's satisfied, and
2. if it's not satisfied, draw a red box around any shapes involved in the violated constraint
3. perhaps also label the box with the line of the **ensure** statement corresponding to the violated constraint.

This idea is similar to how MathJax does error reporting.  I couldn't find a great screenshot, but basically rather than just aborting it prints an inline error message about what went wrong:

![image](https://user-images.githubusercontent.com/3604525/72222486-21821980-3533-11ea-9d39-409d5aa9f66d.png)

This mechanism of feedback is a huge improvement on standard TeX, which does ordinary console-style error reporting (i.e., compilation stops, and it spews out some indecipherable error message about what when wrong).

**Comment by maxkrieger** [comment]
@wodeni is this info contained in state packet already or would it have to be added?

**Comment by keenancrane** [comment]
Whoops, this issue is redundant w/ #281.

**Comment by wodeni** [comment]
Closing in favor of #281.
