### ISSUE TITLE
Add graph layout to Penrose as JS plugin

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#319]
Ideal API: https://www.graphviz.org/

Description of main graphviz algorithm (can't be reproduced with pure optimization, it seems): https://www.graphviz.org/pdf/dotguide.pdf

Options in the browser:
* http://viz-js.com/ (uses emscripten around graphviz; seems gnarly)
* https://github.com/dagrejs/dagre/wiki#using-dagre (this requires node sizes, which we don't have at the plugin level)
* **https://github.com/magjac/d3-graphviz** (this seems like the best one because it has a graphviz-like API--but seems to output an SVG, not the node positions)
* Mermaid ([API](https://mermaid-js.github.io/mermaid/#/mermaidAPI), [GitHub](https://github.com/mermaid-js/mermaid))

Goal for graphs to make:
![image](https://user-images.githubusercontent.com/2762356/75931206-685d0300-5e42-11ea-8946-e1e45adcc7f4.png)
![image](https://user-images.githubusercontent.com/2762356/75931216-6e52e400-5e42-11ea-9f09-fc62aacc289e.png)

Existing work on extending Penrose with computational graphs: https://github.com/penrose/penrose/pull/239

Question: who makes the splines? The plugin? Or Penrose?

Design:
* Plugin returns list of spline points, associated to a pair of names (by some magic protocol)
* (Need to extend JSON + Style to deal with lists of points)
* In Style, match on each pair of nodes w/ an arrow predicate, make a LOCAL curve, and set the curve's spline points to be the spline points of the plugin

Related issues: #238

**Comment by RobbieMcKinstry** [comment]
[Mermaid])(https://mermaid-js.github.io/mermaid/#/) offers a JS implementation of the Graphviz core syntax. Not sure exactly what your requirements are, but that might help. When you say API, you mean the language syntax, or are you referring to an actual programmatic JS API?

**Comment by hypotext** [comment]
As @wodeni and I discussed:

* Improving this domain should probably be done in "pure Penrose" objectives/constraints
* This may require improving those objectives/constraints, instead of hacking together something with them
* Which may require reviving the polygonization/layout code discussed in #216 #198 

I will work on the simplest (possibly hackiest) plugin solution; @wodeni will investigate the more principled approach.

**Comment by hypotext** [comment]
Thanks @RobbieMcKinstry, we'll check out Mermaid as a possible solution.

**Comment by joshsunshine** [comment]
We don't have plugins anymore. We are going to close this due to inactivity.
