### ISSUE TITLE
Please add explanation to README how to run penrose

### ISSUE THREAD

**Issue by yurivict** [penrose/penrose#321]
Usage says that the way to run it is ```penrose <substance> <style> <element>```, but the README only contains ```tree.sub``` and ```venn.sty```. ```penrose``` also wants the ```element``` file. What should be its content?

Also what NodeJS components are required and how to run them? Is there a complete example anywhere?

**Comment by hypotext** [comment]
Hey @yurivict, thanks for your interest. The README is currently out of date, and we are working on cleaning up the documentation for public use in a few months. In the meantime, here are some more up-to-date steps:

Building and running: https://github.com/penrose/penrose/wiki/Building-and-running
All working triples of programs: https://github.com/penrose/penrose/wiki/Paths-for-testing-(paper-submission)

**Comment by hypotext** [comment]
Hey @yurivict I cleaned up the installation instructions so hopefully it's clearer: https://github.com/penrose/penrose/wiki/Building-and-running Let us know if you run into other problems.
