### ISSUE TITLE
Linear algebra diagrams are too regular

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#328]
In b1945128db265e64f68e5bed4f33081f69acb71b:

Checking out use.penrose.ink, determinant example, results in a diagram that's too regular:

![image](https://user-images.githubusercontent.com/2762356/77001654-a5d88a80-6930-11ea-848b-3607306c18d7.png)

This example (with one of the `labelAvoidFn`s commented out) has a better result, but is still too symmetric: https://use.penrose.ink/sub/gh/4ac2b4c24112acd6bbe14bfc87a14618

![image](https://user-images.githubusercontent.com/2762356/77001804-e6380880-6930-11ea-8f7a-938d3bdc9686.png)

**Comment by wodeni** [comment]
The LA domain is quite different now so I can't repro this. Closing for now.
