### ISSUE TITLE
Improve Penrose homepage

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#329]
See Figma.

**Comment by joshsunshine** [comment]
We should incorporate the logos that the PROPS supply folks added.

**Comment by joshsunshine** [comment]
We should make it easy for anyone on the team to edit. Perhaps we should use a simple Jekyl theme or something of that nature?

**Comment by maxkrieger** [comment]
Yeah genericness is preferable since it affords easy editing, we can add flair later. Not sure what the safest option is these days. Gatsby is alright and I'm going to use it for the autodocs.

**Comment by maxkrieger** [comment]
Can just use #771 as a pretty maintainable one
