### ISSUE TITLE
Add concrete examples and assumptions to all documentation; standardize code style

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#33]
All function comments should be illustrated by and accompanied by concrete examples.

_For example_, "f gives the head of a reversed list" is better written as "On an example list y = [1,2,3], f reverses the list to [3,2,1] and returns the head element [3]."

Even better, these concrete examples should just be written as unit tests (#8). Better readability and usability.

Also, make all assumptions explicit, e.g. "f assumes that the input list y is nonempty." Ideally, enforce them via invariants: "f [] = error 'empty list'" or better.

All function declarations should have type annotations, unless typeclasses and polymorphism make it too unwieldy. 

Try to avoid single-letter variable names unless it's `i`, `j`, (index), `n` (number), or a specific parameter without meaning (e.g. `a` in line search).

In `where` clauses, declare things in definition order, like you would in a series of `let` clauses.

Standardize `where` vs. `let` usage. (I prefer let, since it enforces an order that is more readable.)

**Comment by cronokirby** [comment]
A concrete step to this effect would be to use `doctest`

**Comment by hypotext** [comment]
@cronokirby Thanks! (edited your comment to add link)

**Comment by wodeni** [comment]
We use ESLint and prettier for this now. Closing this issue.
