### ISSUE TITLE
Streamline Penrose install process and instructions for devs

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#337]
See Keenan's install notes on Slack [here](https://pen-rose.slack.com/archives/C2EV136RX/p1585695711000900).

Ideally we would provide a build script that streamlines all the installation that first-time devs need to do, especially the various JS steps.

**Comment by maxkrieger** [comment]
If everything's unified in a single module then yeah we'll only need a
single npm start command

**Comment by hypotext** [comment]
Related: https://github.com/penrose/penrose/issues/341

**Comment by maxkrieger** [comment]
closing for now (#464)
