### ISSUE TITLE
Some issues in first-time install

### ISSUE THREAD

**Issue by willcrichton** [penrose/penrose#341]
Hey team, just went through the install process and wanted to report a few snags I encountered. Building on Catalina.

- The `node-gyp` dependency in `react-renderer` failed to install. I had to follow the fix [here](https://github.com/nodejs/node-gyp/issues/1917#issuecomment-552101171).
- I found the console output of `penrose` to be a little confusing. It ends with `Waiting for the frontend UI to connect...`, and prints nothing even after connecting to the frontend. 
- The `plugins/regex.py` is not Python 3 compatible.
- `examples/graph-theory-domain` seems to be broken (outdated syntax).
- The drag/drop functionality in the UI seems to be incorrectly calculating coordinates. When I drag an element, after I drop, it ends up far away from my cursor.
- The `mesh-domain` is extremely slow. It took ~5 minutes to just load into the UI. And sometimes it doesn't seem to load in the UI at all.
- The documentation on [Building and Running](https://github.com/penrose/penrose/wiki/Building-and-running) has multiple dead links.
- The web page sometimes dies with this error (don't know the cause): 
<img width="1792" alt="Screen Shot 2020-05-15 at 5 17 55 PM" src="https://user-images.githubusercontent.com/663326/82105433-22d57580-96d0-11ea-8753-89f7ac5fb593.png">

Also I wanted to try out the fancy web IDE! Is that still too in-progress to show publicly?

**Comment by hypotext** [comment]
Hey @willcrichton, thanks for trying this out! We appreciate your reporting of the snags and plan to streamline the install process after we finish some core eng work on the system. I'll follow up about the web IDE via email.

**Comment by maxkrieger** [comment]
simplified a lot in #464, closing for now
