### ISSUE TITLE
Broken link "Grammars for languages"

### ISSUE THREAD

**Issue by ShrykeWindgrace** [penrose/penrose#344]
Seen on <http://penrose.ink/siggraph20>, the link for "Grammars for languages" reads

`http://penrose.ink/Penrose_SIGGRAPH2020_Supplemental_Grammars.pdf`, and it should be - I guess - `http://penrose.ink/media/Penrose_SIGGRAPH2020_Supplemental_Grammars.pdf`

**Comment by hypotext** [comment]
Fixed, thanks @ShrykeWindgrace
