### ISSUE TITLE
can not find penrose-ide

### ISSUE THREAD

**Issue by zhanglei890512** [penrose/penrose#346]
When I was trying to install it, I can not find https://github.com/penrose/penrose-ide.

**Comment by maxkrieger** [comment]
Sorry about that! It's a private repo and that instruction is for internal use right now. The IDE is in a state of flux and since everything with the Penrose system is being refactored, the IDE and all its intricacies are probably not worth setting up on your machine at least for now.

**Comment by zhanglei890512** [comment]
Thank you for your attention. This is my first time trying to use it. Can I use it without IDE?

**Comment by maxkrieger** [comment]
Yes, check out the examples on the wiki, you can run it via command line
with text files.

**Comment by zhanglei890512** [comment]
Thanks for your answer. 
But I find that
-bash: runpenrose: command not found

**Comment by maxkrieger** [comment]
Try simply "penrose", assuming stack install was successful.

**Comment by zhanglei890512** [comment]
I think my installation failed, so now how do I delete it completely？
-bash: penrose: command not found
Thank you！

**Comment by maxkrieger** [comment]
Check home directory for .stack-work and other Haskell stuff, and then
delete the cloned repo

**Comment by zhanglei890512** [comment]
Thank you very much!
