### ISSUE TITLE
Look into migrating from Haskell to browser-native language

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#35]
Candidates: Elm, Purescript, Typescript, Javascript, maybe using d3, Svelte, Snap, React.

Figure out the state of web support in the following: 

- Sophisticated static type systems and typechecking
- Autodifferentiation
- Optimization, linear algebra, and numerical computation
- Parser combinators and generators
- DSL definition, design, metaprogramming, reflection, language workbenches
- Property-based testing and unit testing
- UI libraries for prodirect manipulation

Figure out which parts of the backend to leave in Haskell.

**Comment by hypotext** [comment]
We might be able to use one of the js deep learning libraries for autodiff, but there's no operator overloading, so defining objective functions and computations would be tedious. 

https://deeplearnjs.org/docs/tutorials/ml_beginners.html
https://github.com/dritchie/adnn

**Comment by vsoch** [comment]
Does something like https://beta.observablehq.com/ fit in here? It's created by Mike Bostock (creator of d3) and in my mind, is sort of like "data science" meets JavaScript.

**Comment by vsoch** [comment]
A ton of work has been done with d3 and various kinds of mathy plots (e.g., venn diagrams, clustering) so if there could be an easy plug in to d3, that would be really great. The only limitation of d3 is rendering number of objects in the dom - canvas would be better for that.

**Comment by wodeni** [comment]
I think now is the time to close this issue 😃:
![image](https://user-images.githubusercontent.com/11740102/119726677-fb62ce00-be36-11eb-9c8e-35cb163ce2fb.png)
