### ISSUE TITLE
inline computations need to support autodiff vars (e.g. tensors)

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#350]
Via @strout18:

> you should be able to repro bug I mentioned in Evaluator (binary ops fail in weird cases) by running `runpenrose linear-algebra-domain/scale.sub linear-algebra-domain/linear-algebra-1d.sty linear-algebra-domain/linear-algebra.dsl`

Currently working on this on branch `evaluator-bug`; throws an error when `NaN` appears, but really not sure where the `NaN` is coming from. Seems to happen when dividing by an inline constant (?) 

The specific op that seems to cause this is like `const.vectorSpaceSize / 200.0` — weird because in the console, you can see that it successfully does the division earlier

**Comment by hypotext** [comment]
Update: I believe this bug is happening because our inline computations (e.g. `len`, `sampleColor`, etc.) do not support tensors! 

Earlier this was not an issue because evaluating the shapes with numbers (to display them on the screen) would only call the inline computations with numbers.

Now that they appear in the autodiff, e.g. in the offending line:

`v.maxSize1 = ensure lessThan(len(v.shape), len(U.shape)/2.0)`

Calling these functions with Tensors will fail with a `NaN` due to TS's permissive typechecking, and the fact that our evaluator allows both numbers and Tensors.

I think fixing the issue requires some more careful thinking about the system: 

Do we really want two versions of all computations, one for numbers and one for tensors? Or should we just have one for tensors, and convert everything to numbers when rendering? What do you think @wodeni?

P.S. @strout18 I think an OK workaround for now is to eliminate any calls to inline computations in Style, for now, and just do it in Constraints.ts. Sorry for the inconvenience!

**Comment by wodeni** [comment]
I think it's okay to just write the computations in terms of tensors. All the rest should work out of the box, as we are doing number-to-tensor conversions in `resolvePath` and the inverse before rendering.

**Comment by hypotext** [comment]
Resolved in the `web-runtime` merge
