### ISSUE TITLE
add IDE support for Style (domain, shapes, and functions)

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#353]
In the process of documenting our "standard library" ([shapes and functions](https://github.com/penrose/penrose/wiki/Shape-and-function-library)), I thought it would be nice if Style could use this information to provide IDE support for writing selectors (Domain) and blocks (shapes and functions).

Some ideas: 
* could this documentation be generated automatically from shape/function code?
* when writing a shape, can we have an interface like the CSS inspector, with a dropdown/autocomplete of property names, and hover info about the property type/initialization/meaning?
    * for example, I constantly forget what properties a shape has available, their exact names, and their types / range of possible values
* how can the IDE help people compose objectives and constraints?
    * e.g. `ensure near(...`) autocompletes with shapes/paths of the right type and name that are present in the block environment, or presents an error if the type is wrong, or name is not present
* can we use Penrose to automatically illustrate the meaning of each shape with 'visual' documentation? (@keenancrane's suggestion)
    * e.g. illustrate the `rx` and `ry` of an ellipse
* is there some way we can piggyback off the Chrome inspector to make any of this happen in the short term? or use VSCode's LSP?

**Comment by wodeni** [comment]
> could this documentation be generated automatically from shape/function code?

The baseline is to use typedoc to generate documentation automatically. Not sure how extensible they are. It'd be cool if we can generate examples in our doc and embed live Penrose diagrams!

> when writing a shape, can we have an interface like the CSS inspector, with a dropdown/autocomplete of property names, and hover info about the property type/initialization/meaning?

Probably possible with the existing LSP API, just like how intellisense figures out completion items given where you are in the program. 

> e.g. ensure near(...) autocompletes with shapes/paths of the right type and name that are present in the block environment, or presents an error if the type is wrong, or name is not present

This is fairly standard. The concrete next step is to rethink how we handle errors. Some current issues
* Identifying, storing, and reporting source positions of errors
* Unified system of error types and reporting

In general, we have many kinds of errors, some of which might be domain-specific others span across multiple languages.

**Comment by maxkrieger** [comment]
I don't have a fully clear picture here but as usual I'm hesitant to do
types as data instead of data as data. Using typedoc as an input to our DSL
services feels hacky to me.

**Comment by hypotext** [comment]
Thanks for the responses, all! Just want to clarify that this is not an urgent/high-priority issue, but an idea we can think about at leisure :)

> The concrete next step is to rethink how we handle errors. Some current issues...

@wodeni I agree, and think that error-handling is actually a root issue that we should handle soon (or at least think carefully about and improve slightly) before we do a release.

**Comment by wodeni** [comment]
> I don't have a fully clear picture here but as usual I'm hesitant to do types as data instead of data as data. Using typedoc as an input to our DSL services feels hacky to me.

Oh that's not what I meant! I mentioned typedoc as a baseline doc generator, which is irrelevant to the second point about lang services

**Comment by hypotext** [comment]
Also looping in issue #158 re: errors. Maybe we should update the thinking there WRT the web runtime.

**Comment by joshsunshine** [comment]
@liangyiliang can you determine which parts of this issue have been completed, and which are still relevant?

**Comment by wodeni** [comment]
Some progress was made on this front such as https://github.com/penrose/penrose/pull/1513. Closing in favor of more concrete issues.
