### ISSUE TITLE
Constraints and objectives interact problematically in the box-and-arrow domain

### ISSUE THREAD

**Issue by strout18** [penrose/penrose#354]
The following constraints/objs interfere with each other (understandably):
sideMidPts
connect
minLength
totalMinLength
cardinal
connectMid
equalLength
sameLine

sideMidPts, cardinal, and minLength caused me the most trouble. I had to adjust the weights on each of these to get diagrams I wanted, and even then they weren't perfect (ignoring the text issues).

![twopoints](https://user-images.githubusercontent.com/40800240/85480149-7bc8e100-b58d-11ea-97b9-c6068de07716.gif)
To generate this diagram I set totalMinLength to 100, cardinal to 50, and connectMid to 8000. 

Also, it seems that connectMid and connect are mutually exclusive, even though the former is an objective (place it on the middle of the perimeter) and the latter (place it on the perimeter) a constraint. They weren’t coded to be (possible bug), though, so I’m not sure why it was impossible to use both in a sty file without only the constraint being satisfied. I ended up only using the connectMid function in my diagrams (after determining connect worked properly).

It also seemed that the optimizer got stuck on undesirable local minima for the connectMid function: on the diagram above, as you can see, the leftmost endpoint is on the left side of the box, even though moving the endpoint to the top side would decrease the energy of the totalMinLength objective. It is possible that given enough time, this would have happened, but after >10 minutes with no change, I gave up on this.

The optimizer ran reeeaalllly slowly, but this has already been noted.

I was also surprised to see the unevenness of the optimizer solving. In the below diagram, both lines D and E have the same constraints and objectives applied to them (path is `runpenrose baa/noblock.sub baa/noblock.sty baa/baa.dsl` ) but they quickly diverge. Eventually, after maybe 20+ minutes they do converge but that is obviously too long to wait. The gif below is after ~2 minutes of running.

![noblock](https://user-images.githubusercontent.com/40800240/85480309-cba7a800-b58d-11ea-9781-e60d78c69b59.gif)

**Comment by wodeni** [comment]
Thanks for writing this up! You definitely took this further than I did :D. The weight issue is quite interesting and generally unexplored. We once had a thought of normalizing the "units" of objectives and constraints (e.g. `repel` is 1/(distance)^2 and `contains` is `distance^2`). I wonder if there are other opportunities to auto-tune weights, which is obviously a longer-term problem.

**Comment by wodeni** [comment]
Many of the constraints from this issues are removed from the standard library, and the weight issue is a much bigger topic. Closing this issue for now.
