### ISSUE TITLE
Flexible command-line argument order

### ISSUE THREAD

**Issue by strout18** [penrose/penrose#360]
When running Penrose through the command line, the general format is `runpenrose X.sub X.sty X.dsl`. Switching the order of the three passed files results in a parsing error because a Substance file is being parsed as a Style file, for instance. It seems natural (and more lenient to the user's memory) to parse/eval files based on their extension, rather than the order in which they are passed.

**Comment by hypotext** [comment]
This would be a good place to start: https://github.com/penrose/penrose/blob/web-runtime/src/Penrose/ShadowMain.hs#L66

It would be good to test that the existing programs work, and that programs in any new order work.

**Comment by hypotext** [comment]
Also for this issue, it's fine to branch off of `master` since it's unrelated to `web-runtime` (cc @apatriarca)
