### ISSUE TITLE
Add Penrose linter, or better error messages between languages

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#371]
Right now when something goes wrong, it's hard to track down whether the user made a typo or "thinko," and which program caused the problem (Substance or Style or Domain or some combination of them). It would be useful to give the user hints about possible problems and where to find them.

See discussion in [#implementation](https://pen-rose.slack.com/archives/C2EV136RX/p1598873346001500).

**Comment by maxkrieger** [comment]
This seems to be improved by current efforts, unless we want to formalize this more before closing
