### ISSUE TITLE
Cos/sin shouldn't use degrees

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#374]
The implementation of cos/sin currently accessible from Style assumes that angles are given in degrees, and automatically converts to radians:

https://github.com/penrose/penrose/blame/9274f1350d4b5315ac793b3f7bc1f4d6b171a37c/src/Penrose/Functions.hs#L654

This convention violates the "principle of least surprise," since in essentially every other language cos/sin expect radians (see for instance the [ISO/IEC 9899 spec](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf), §7.12.4.5).

This is easy enough to change (just remove the conversion), but I'm not sure if there are examples that it will break…

**Comment by cmumatt** [comment]
Resolved in main by PR #677
