### ISSUE TITLE
Vectors should be first-class type in Style

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#375]
Anybody writing graphics code will expect to be able to work with (2D and 3D) vectors using nice syntax.  Currently, for instance, if we want to implement the computation

```
u = (c1 - c0)/norm(c1-c0)
```

where `u`, `c0`, and `c1` are 2D vectors, we have to write it out in terms of components

```
   LOCAL.ux = LOCAL.c1x - LOCAL.c0x
   LOCAL.uy = LOCAL.c1y - LOCAL.c0y
   LOCAL.m = sqrt( LOCAL.ux*LOCAL.ux + LOCAL.uy*LOCAL.uy )
   LOCAL.vx = LOCAL.ux / LOCAL.m
   LOCAL.vy = LOCAL.uy / LOCAL.m
```

Even if we get rid of the `LOCAL` keyword (a la #372), the code would still look something like

```
   var ux = c1x - c0x
   var uy = c1y - c0y
   var m = sqrt( ux*ux + uy*uy )
   var vx = ux / m
   var vy = uy / m
```

which is **extremely** verbose by graphics standards.  (Compare to languages like [GLSL](https://en.wikipedia.org/wiki/OpenGL_Shading_Language).)

Some things we really want to support:

- At least 2D, 3D, and 4D vector types (4D are super common for working with homogeneous coordinates...); nD may be overkill, but we should discuss.
- Definitely want syntactic sugar for vector operations, e.g., `u + v` not `add( u, v )`
- Also have to think about component accessors, e.g., saying something like `myScalar = myVector.y` to get the _y_ component, versus, `myScalar = myVector[1]`; some languages (GLSL?) support both.
- A "nice to have" feature, that actually can make a lot of code quite nice/clean, is "[swizzling](https://en.wikipedia.org/wiki/Swizzling_(computer_graphics))", e.g., `myVector.yxz = yourVector.xyz` will swap the _x_ and _y_ components.

In general, would be good to look at languages (such as GLSL, [HLSL](https://en.wikipedia.org/wiki/High-Level_Shading_Language)) and other graphics code (such as PBRT) to see what kinds of design decisions people have made.

**Note:** TensorFlow currently makes it tough to implement this stuff, since the TF paradigm is to basically never pull elements out of tensors.  Some of these issues should be resolved when we switch to @hypotext's autodiff system.

**Comment by wodeni** [comment]
Addressed in #403
