### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by neizod** [penrose/penrose#380]
This project looks cool, but I have no experience in building/installing Haskell project at all. Please write some document on how to install it.

**Comment by hypotext** [comment]
Hey @neizod, we've written an install guide [here](https://github.com/penrose/penrose/wiki/Building-and-running). Please try it out and feel free to reopen this issue if you run into any problems.

**Comment by neizod** [comment]
@hypotext thank you, and my bad I don't see this on the README (I do ctrl+f ony for "install", not "build" keyword LOL)
