### ISSUE TITLE
Better parsing of floating point numbers

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#381]
Currently the Style parser is very rigid about the floating point number formats it accepts—I _think_ it only handles numbers of the form `a.b`, i.e., digits separated by a decimal place, but not (say) `a.` or `.b`.  It also doesn't seem to accept integers in places where floating point numbers are expected.  In general, graphics programmers will likely also want to use scientific notation, e.g., `1e-4` or `1.2e-4` or `.2e-4`, etc.

Can we use some (existing) standard parser for floating point numbers in Style?

**Comment by hypotext** [comment]
cc @wodeni, looks like this is pretty doable in Parsec:

* https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/parsing-floats-with-parsec#parsing-floats
* https://hackage.haskell.org/package/parsec3-numbers-0.1.0/docs/Text-Parsec-Number.html

**Comment by wodeni** [comment]
Megaparsec comes with a set of builtin lexers (https://hackage.haskell.org/package/megaparsec-9.0.0/docs/Text-Megaparsec-Char-Lexer.html). I used their `float` lexer. There's `scientific` for cases @keenancrane mentioned.

**Comment by keenancrane** [comment]
> There's `scientific` for cases @keenancrane mentioned.

Do we need scientific to handle cases like `123.` and `.123`?  Those currently aren't accepted by Style.

**Comment by maxkrieger** [comment]
Is this resolved? Not sure how `parseFloat` does it.

**Comment by wodeni** [comment]
All done and tested in #428. Closing now.
