### ISSUE TITLE
Make keyword capitalization consistent across languages

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#390]
Currently almost all language keywords are lowercase, with at least two exceptions:

- the `Label` keyword in Substance, and
- the `LOCAL` keyword in Style

Seems the easiest thing would be to change `Label` to `label`; `LOCAL` will be deprecated in Style v1.1.

**Comment by wodeni** [comment]
Closing as `LOCAL` is no longer a keyword in Style
