### ISSUE TITLE
Don't report error if there are no objectives/constraints

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#391]
Currently if you write Substance/Style programs that yield no objectives/constraints, we produce an error

`Unhandled Rejection (Error): no objectives and no constraints`

But diagrams with no objectives/constraints are fine—for instance, maybe you want to just randomly sample different parameter values, and otherwise construct the diagram deterministically.  Perhaps we can just change this error to a warning?

**Comment by hypotext** [comment]
Resolved in #391 (also removed console error for the `BinOp` thing you encountered earlier)
