### ISSUE TITLE
Support empty fill and stroke style

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#392]
Currently to draw curves in Style we set the fill color to an RGBA color with zero opacity, e.g., `shape.color = rgba(0.0, 0.0, 0.0, 0.0)`.  A shape with opacity zero is however different from a shape with an empty fill style, specified in SVG (and CSS) via `fill: none;`. With an empty fill style, the interior does not get rasterized, and likewise, the interior is not treated as a selection mask.  Empty shapes are important for, e.g., drawing empty circles as outlines, rather than solid disks.  Similarly for strokes.

**Proposal.** In Style, define a type that has both `rgba` and the flag `none` as subtypes (say, `fillType`).  Then one can write either

```
x.shape = Circle {
   fill: rgba( red, green, blue, alpha )
}
```

or

```
x.shape = Circle {
   fill: none
}

Note that having a richer type `fillType` opens the door to (eventually) supporting other standard SVG features, such as [filling with a pattern](http://tutorials.jenkov.com/svg/fill-patterns.html).

**Comment by cmumatt** [comment]
Resolved in main via merged PR# 699
