### ISSUE TITLE
Style compiler should issue warning/error if a GPI property does not exist

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#394]
Currently the compiler issues no error/warning if a field of a shape does not exist.  Consider for instance this example, which draws a triangle as three line segments:

```
forall Triangle t; Vertex a; Vertex b; Vertex c
where t := MakeTriangle( a, b, c ) {
   t.s1 = Line {
      startX: a.x
      startY: a.y
      endX: b.x
      endY: b.y
      color: Colors.black
      strokeWidth: Global.thinStroke
   }
   t.s2 = Line {
      startX: b.x
      startY: b.y
      endX: c.x
      endY: c.y
      color: Colors.black
      strokeWidth: Global.thinStroke
   }
   t.s3 = Line {
      startX: c.x
      startY: c.y
      endX: a.x
      endY: a.y
      color: Colors.black
      strokeWidth: Global.thinStroke
   }
}
```

The error here is subtle: `Line` doesn't have a field `strokeWidth`, though it does have a field `thickness`.  Yet the compilation succeeds anyway—and the renderer even sets one (but not all) of the stroke weights to the provided value:

![image](https://user-images.githubusercontent.com/3604525/97162108-1f511a80-1755-11eb-8564-0ba4179e183f.png)

Changing `strokeWidth` to `thickness` produces the expected result:

![image](https://user-images.githubusercontent.com/3604525/97163078-786d7e00-1756-11eb-97e3-be66151f2324.png)

But obviously this situation is quite confusing to debug: the programmer goes looking for some asymmetry in their code (after all, _one_ of the segments rendered properly...).

The question is: what's the right solution here?  Two options:

- **Be fault-tolerant.**  If a field is requested that doesn't exist, simply ignore this line—with no side effects.  Issue a warning, not an error.  Provide an option to treat all warnings as errors.  A pragmatic reason for being fault-tolerant is that it makes it more likely a malformatted program will yield _some_ useful output that the programmer can expect, rather than refusing to compile.  This also helps with future proofing to some degree: if fields of a shape change, the diagram won't completely fail to compile in the new version of Penrose.  Another reason for being fault tolerant is just to help the programmer quickly explore changes.  E.g., say I want to change a bunch of `Arrow`s into `Line`s for a second, just to explore an idea.  It's nice if I don't have to remove all fields pertaining to arrowheads—even though I will do so eventually in order to remove the warnings. [Note that the current implementation fails this bar: there are no warnings, and there _are_ side effects—in this case, one of the line's widths getting set even though `strokeWidth` is not a valid field for this shape.]
- **Be strict.** Simply issue an error and refuse to compile if the field does not exist.  The benefit of this approach is that it forces programmers to be more disciplined, and produce code that is clearer and more correct.  This makes things easier for both the compiler and other people reading the code.

**Comment by hypotext** [comment]
That's definitely unwanted behavior. I agree that the Style compiler should issue a warning/error (changed your issue name to use "GPI property," by the way). I also don't know why it would succeed for just one line—my thought is that all the line widths got randomly sampled since `thickness` was left unspecified.

As for what approach to take, I'd actually prefer the former, since it aids experimentation. (I believe CSS also takes the former approach, and will just let you write any old property and then ignore it.)

**Comment by samestep** [comment]
@cmumatt Do you happen to know if this is still something we plan to do? I don't remember the conclusion of our passthrough conversations in January:

- #749
- #759
- #806

**Comment by cmumatt** [comment]
@samestep, right.  This pre-dates SVG passthrough, which makes all properties valid.  Based on that change in January, issuing compiler errors as originally described is no longer feasible.  It does seem Penrose should do something to help make typos more obvious. Maybe an appropriate user aid might be to provide hints in the IDE such as a different color to help the user recognize when a property is unknown and thus, SVG passthrough.

**Comment by samestep** [comment]
Ahh I like that idea!

**Comment by joshsunshine** [comment]
The compiler does issue an error if the style program tries to create an invalid shape. For example, if the style program includes code like `x.icon = Foo {...}` the compiler will issue the following warning `Got invalid GPI type Foo. Available shape types: Circle,Ellipse,Equation,Image,Line,Path,Polygon,Polyline,Rectangle,Text` I think the @cmumatt's change to allow pass-through properties makes the rest of this issue mostly irrelevant.
