### ISSUE TITLE
fix LBFGS constantly getting stuck in geometry example

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#400]
Noticed in 1a3939f4226eae8b87b3212155c36f5cdcf8a18e (used to be a NaN, I think).

Path: `runpenrose geometry-domain/pythagorean-theorem-sugared.sub geometry-domain/euclidean-simple.sty geometry-domain/geometry.dsl`, second sample, LBFGS keeps resetting correction vectors and gets stuck.

**Comment by wodeni** [comment]
Closing because we can't repro this example now due to major language changes since this issue was opened.
