### ISSUE TITLE
Missing Label in .sub file leads to unclear error

### ISSUE THREAD

**Issue by mmp** [penrose/penrose#417]
With the attached test case, penrose gives the unclear error "penrose: path 'p.text's field doesn't exist in trans". (Uncommenting out the `Label` at the end of twoVectorsPerp.sub fixes it.)

[bug.zip](https://github.com/penrose/penrose/files/5632488/bug.zip)

**Comment by hypotext** [comment]
Thanks, improved in  779d4cd to have a better error message (see below) but leaving this open to address further in our errors-and-warnings overhaul.

```
penrose: path 'x2.text's field doesn't exist in trans: did you label the variable in Substance? Use `Label x2 $LABEL` or `AutoLabel All`
```
