### ISSUE TITLE
change frontend default optimization settings to autostep

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#420]
From Slack:

> On the user end, it probably make more sense to do the layout automatically—and perhaps just show a progress bar rather than visualizing the optimization. (This may speed things up anyway.) Visualizing the optimization sounds like something you’d expect to see in “debug mode.” Maybe for now we can just toggle the initial state of the existing button, and label it “debug optimization”?

**Comment by hypotext** [comment]
Hey @wodeni @maxkrieger would one of you mind getting this? I would do it but I don't know how it might interact with the React app lifecycle, async stuff, etc.

**Comment by wodeni** [comment]
Fixed in 712ff5c. Closing now.
