### ISSUE TITLE
Reduce bundle size of `@penrose/core`

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#423]
Our production build of `penrose-web` is quite big (see output for `npm run build` or `npm run build:bundle`). At some point, we will need to cut down our dependencies or look into other optimization options. The bundle size also affects our CI, as `terser` sometimes reports `Call retries were exceeded` even with increased memory.

**Comment by wodeni** [comment]
`@penrose/linear-algebra` is quite large: https://bundlephobia.com/result?p=@penrose/linear-algebra@1.0.1
Overall size distribution here:
![image](https://user-images.githubusercontent.com/11740102/102419187-e3a03780-3fc4-11eb-8079-0997765ff963.png)

**Comment by wodeni** [comment]
New stats coming from #465 
![image](https://user-images.githubusercontent.com/11740102/107861568-4c146500-6e0c-11eb-8ddb-196a89454a9d.png)

**Comment by samestep** [comment]
Using [esbuild-visualizer](https://www.npmjs.com/package/esbuild-visualizer) on #1165:

<img width="1362" alt="Screen Shot 2022-12-09 at 11 25 13 AM" src="https://user-images.githubusercontent.com/8246041/206747138-1691f362-b97e-4d72-95b4-7a17f9e2acd3.png">
