### ISSUE TITLE
minSize and maxSize constraints don't have clear meaning

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#424]
Currently Style has constraints of the form

```
  ensure minSize(h.circleShape)
  ensure maxSize(h.circleShape)
```

It's completely opaque what these mean / what they're supposed to do.  I find myself asking, "what minimum/maximum size is this going to constrain the shape to?  What property of the shape is going to be constrained?  Its radius?  Its diameter?  Its bounding box diagonal?"  Etc.

If the purpose of a DSL is to enable the programmer to express ideas in familiar terms, this is not really compatible with a specification that a diagrammer would typically use.  They might say, "I want to make sure that the radius is at least as big as (some other quantity)."  But they wouldn't just generically say, "I want this shape to have at least the minimum size" (for the reasons mentioned above).

Resolving this question takes some thought.  For instance, in CSS/HTML there are all sorts of semantics for specifying how big things should be, or how big they should be relative to each-other in a collection (so that, e.g., elements don't shrink to zero).  We could likewise come up with such mechanisms in Style, but it will take some work/thought to get it right.

**Near-term proposal:** First, let's get rid of these (too opaque) constraints (`minSize` and `maxSize`).  A simple and clear alternative is to make statements like `ensure inRange( h.circleShape.radius, minVal, maxVal )`.  Here, `minVal` and `maxVal` are user-defined constants---or perhaps reference properties of other shapes.  That's just the right level of being explicit, without having to say exactly what value the parameter should take.

**Long-term proposal:** In many cases, it may be easier for the user to specify sizes in relative terms, and have the system do some of the work of figuring out how to assign absolute values to the sizes.  One rough idea for such a specification is that each shape can be assigned some "screen real estate"—in whatever quantity the user likes—and the system will then divvy up the available space (e.g., the total size of the canvas) according to these values.  For instance, you could imagine that each graphical primitive has a field `realEstate: x` where x is a unitless number.  The compiler would then add up all these `realEstate` values to get a number `totalRealEstate`, and assign a target size like `(x/totalRealEstate)*canvasSize`.  There is still some ambiguity about what the "size" of a shape should be in this context.  For instance, it might be area, so that these shapes roughly fill in the whole area:

![image](https://user-images.githubusercontent.com/3604525/101677498-a5d26a80-3a2a-11eb-8139-508ee44bfdb9.png)

The complexity with designing such a system, is that probably we don't just want to divvy up real estate for all objects over the whole canvas, but rather, might want to divvy up real estate for a _subset_ of objects over a particular _region_ of the canvas/diagram.  E.g., some object's shape might be a rectangle, and within that rectangle we want to give several shapes equal real estate (consider the orange rectangle):

![image](https://user-images.githubusercontent.com/3604525/101677544-b4208680-3a2a-11eb-9f0b-405697010fea.png)

To make this work, we probably need to implement a `Group` graphical primitive (which is on our agenda anyway).

**Comment by wodeni** [comment]
@jiriminarcik refactored `maxSize` and `minSize` to use a generic shape query `shapeSize`. We also introduced opt-out `onCanvas` constraints for every shape in #694. Closing this issue now.

**Comment by wodeni** [comment]
The long-term proposal is still quite interesting. Perhaps we should refer to this issue whenever we run into discussions about shape sizes in the future.
