### ISSUE TITLE
Can't start floating point constants with decimal point

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#425]
The Style parser currently does not accept floating point constants that start with a decimal point.  For instance, one has to type `0.5` rather than `.5`.

The error message is also not helpful here (it doesn't mention the number at all):
```
penrose: Error when parsing Style: 
47:30:
   |
47 |    shape p.dotShape = Circle {
   |                              ^
unexpected '{'
expecting '*', '+', '-', '/', '^', '}', or newline
```

**Comment by wodeni** [comment]
Addressed in #428. Examples in the test suite: https://github.com/penrose/penrose/blob/4435e3e6c0c3902b0dd20bfbedac4a99b9dde7b1/penrose-web/src/parser/StyleParser.test.ts
