### ISSUE TITLE
No norm function in Style standard library

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#426]
There's currently no function `norm(x)` in the Style standard library; one expects such a function to compute the Euclidean norm of a `vector2` or `vector3`.

**Proposal:** Add this function. :-)

There is a function `normalize(x)`, but it doesn't have the expected behavior: "ize" sounds like it's going to mutate `x`, but instead it returns the normalized version of `x`.

**Proposal:** Rename this function to `unit(x)` or `unitVector(x)`.

**Comment by hypotext** [comment]
Resolved in e1dd598
