### ISSUE TITLE
Style parser confuses kebab-case and subtraction

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#427]
If there are no spaces between a minus sign and two operands, the Style parser interprets the token as a kebab-case name.  E.g.,

`R-r`

yields an error in a context where `R` and `r` are scalars (and there is no variable named `R-r`), whereas

`R - r`

parses correctly.

**Proposal:** We have a couple of options here.  The easiest, perhaps, is to forbid variables from having kebab-case names.  Otherwise, upon failing to find a kebab-case token, the parser will have to split up the token and try parsing it as a subtraction.

**Comment by wodeni** [comment]
Our new Style parser doesn't allow kebab-case anymore #428, as they lead to ambiguous grammar.
