### ISSUE TITLE
Optimized diagrams sometimes disappear in snap

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#43]
After the optimization is done in snap with autostep, sometimes the diagrams will disappear:

<img width="452" alt="screenshot 2018-01-10 18 52 07" src="https://user-images.githubusercontent.com/2762356/34801573-6b7301ae-f637-11e7-9bcf-bf7ef8f13565.png">

Also, sometimes the diagram will disappear after autostep is changed from on to off. 

Maybe the server is dropping frames?

I've sometimes been able to get the disappearing problem to stop by restarting the Haskell server.

This happens on branch `shapes`, with either of the following two commands: `./Main snap sub/cart-test.sub sty/cart-test.sty` or `./Main snap sub/twopoints.sub sty/twopoints.sty`

**Comment by wodeni** [comment]
Turned out to be a small problem in the front-end logic in the websocket handler. Now it should be fixed.

**Comment by hypotext** [comment]
Thanks for fixing it! Looks like it works for the optimization. However frames still disappear on autostep (see gif below). Should I open a separate issue?

![autostep](https://user-images.githubusercontent.com/2762356/34962399-752f6196-fa11-11e7-832e-2fa2ab0114e6.gif)

**Comment by wodeni** [comment]
I wasn't able to recreate the problem. I ran `./Main snap sub/tree.sub  sty/venn.sty`, went to the browser, enabled Autostep, and repeatedly click on the Autostep button. Here is the result:

![bug](https://user-images.githubusercontent.com/11740102/34964385-4de6eb54-fa1b-11e7-8401-b7829887a6d9.gif)
