### ISSUE TITLE
Initial parameters for some graphical primitives are surprising

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#430]
Currently we initialize some parameters of graphical primitives to random values.  E.g., the declaration

```
   g.shape = Line {
      start: p.dotShape.center
        end: q.dotShape.center
   }
```

gives the line a random thickness and color.  This behavior sort of violates the "principle of least surprise," and makes the programmer wonder if they maybe did something wrong, or if there's some bug in the compiler/renderer that's producing these funky values.

**Proposal:** Just initialize the fields to some sensible but deterministic value.

**Comment by wodeni** [comment]
Addressed by #1169.
