### ISSUE TITLE
Console warning is not meaningful

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#431]
Currently the JS console displays "optimizer:warn", making the programmer think that something perhaps went wrong.  But this "warning" really just provides some data that might be useful for debugging.

**Proposal:** Change this label to something like "stats" or "info dump," so that programmers aren't worried that something is wrong.

**Comment by wodeni** [comment]
+1. Now that we have a logger infra. Maybe it's worth going over the bigger modules (e.g. Optimizer, Autodiff) and decide on how we should log things.

For reference, [consola supports these log levels](https://github.com/nuxt-contrib/consola/blob/master/src/types.js)

**Comment by wodeni** [comment]
This issue is ddressed in d2b69ae. @hypotext lmk if you want to go over logging at some point.

**Comment by hypotext** [comment]
Agree, let's maybe address logging with the rest of the errors and warnings.
