### ISSUE TITLE
Implement a more comprehensive list of functions and constraints

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#434]
Currently we've implemented a bunch of functions and constraints in a "lazy evaluation" fashion, i.e., whenever we need something for a Style program, we implement it in Penrose.  We're getting to the point where we should really have a more complete/comprehensive list (e.g., that users can call at will).

How do we come up with this list?  One natural idea is to simply pick some libraries, and try to (more or less) reach parity with those libraries.  For instance:

- **Graphical primitives** — here it would be natural to match the list of shapes supported by SVG, since we currently output to SVG!
- **Math functions** — here the absolutely most natural thing would be to simply expose [the math functions available in Javascript](https://www.w3schools.com/js/js_math.asp)
- **Constraints** — the choice here is less obvious, but we could for instance look at the constraints available in Geogebra, D3, etc., to get a pretty good list of things that should be supported in Penrose

**Comment by hypotext** [comment]
One place to start with objectives and constraints is to port all of the graphical layout primitives that were available, both analytically (for particular shapes) and generically (for any polygon), in Haskell in the old system: [quick list below, more TBA]

spatial:
* disjoint
* contains
* boundaryIntersect
* distBetween
* sameCenter
* tangent
* alignAlong / orderAlong

size:
* minSize / maxSize / sameSize

position:
* at, near
