### ISSUE TITLE
args to predicates should be parsed into PredArg

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#436]
Some arguments to predicates are parsed as Style variables, when they should be wrapped in PredArg.

Repro:
* In `linear-algebra-paper-simple.ast.json`, search for `Orthogonal`. (In the Style program, the predicate is `Orthogonal(v,w)`.)
* You can see that the parsed AST contains `Orthogonal` applied to two `StyVars` for predicate arguments.
* However, that does not conform to the grammar in `types.d.ts`, which has this form for predicate arguments: `type PredArg = SelExpr | RelPred`

I would expect one of the following to be the solution:
* change the parser: either `Orthogonal(v,w)` should be parsed such that the arguments are two `SelExpr`s that are `SEBind`s of `StyVar`s
* or change the grammar: `RelPred` is either a `StyVar` or `RelPred` (this is fine since for now, we don't allow expressions in predicates, but in the future we may want the more general form we have now)

For now, the Style compiler works around it by accepting `StyVar` even if it doesn't appear in the grammar.

What do you think @wodeni?

**Comment by wodeni** [comment]
I probably missed this in #428. We decided to bypass `SelExpr` and only allow nested predicates or binding forms in `SelPred`. I changed the grammar to reflect this decision and also parse the binding forms into `SEBind`. Kind of a mix of both solutions.

Fixed in e9b10b5.
