### ISSUE TITLE
RelPred name is parsed into a string when it should be an identifier

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#437]
Similar repro as #436.

`RelPred` has a field called `name: string` in the grammar, but all other `name` fields in the grammar have type `Identifier`. 

In practice (i.e. in the JSON file), the name is actually parsed as an `Identifier`, and that's what the compiler receives.

I would recommend changing the type of `name` of `RelPred` in the grammar to `Identifier`.

**Comment by wodeni** [comment]
Agreed with the solution. Let me know if you bump into `string`s again. All AST nodes should really have `Identifier` type instead of `string`. 

Fixed in c07cf18.
