### ISSUE TITLE
Substance parser cannot parse `In`

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#44]
The following program does not parse and I believe it should:

```
Set A
Point B
In B A
```

Running `./Main snap sub/venn_comp_pt.sub sty/venn_comp_simple.sty` gives this error:

```
Main: sub/venn_comp_pt.sub:3:1:
unexpected 'I'
expecting alphanumeric character, end of input, letter, or newline

CallStack (from HasCallStack):
  error, called at ./Substance.hs:341:18 in main:Substance
```

**Comment by wodeni** [comment]
Pushed a fix to the issue with `In`. Turned out to be more complicated then I thought. It was mostly related to space consumer. I also upgraded Megaparsec to 6.3 for some new functionalities I used in this commit.

**Comment by wodeni** [comment]
Since we still have a couple of branches working on the older version of Megaparsec, please compile `Main` with the following command, which hides the newer version:
```
ghc Main -ignore-package megaparsec-6.4.0
```
