### ISSUE TITLE
Configuring GHC Failed

### ISSUE THREAD

**Issue by zoujieJason** [penrose/penrose#440]
jay@JacBook-Pro examples % stack install alex happy      
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                
configure: error: in `/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
Received ExitFailure 77 when running
Raw command: /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/configure --prefix=/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
Run from: /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/

                   
Error: Error encountered while configuring GHC with
         /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/configure --prefix=/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
         run in /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/
       
       The following directories may now contain files, but won't be used by stack:
         - /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/
         - /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
       
       For more information consider rerunning with --verbose flag
       
Configuring GHC ...

**Comment by zoujieJason** [comment]
I do not know how to fix this problem.

**Comment by hypotext** [comment]
Hello! Please try running `stack clean` first, and rerunning it. If that doesn't work, please try installing GHC individually, and rerunning that. This appears to be a problem with GHC, which I'm not sure how to help with (maybe ask on the `stack` issues page?).

**Comment by zoujieJason** [comment]
> Hello! Please try running `stack clean` first, and rerunning it. If that doesn't work, please try installing GHC individually, and rerunning that. This appears to be a problem with GHC, which I'm not sure how to help with (maybe ask on the `stack` issues page?).
It doesn's work, but thanks still.

**Comment by zoujieJason** [comment]
> Hello! Please try running `stack clean` first, and rerunning it. If that doesn't work, please try installing GHC individually, and rerunning that. This appears to be a problem with GHC, which I'm not sure how to help with (maybe ask on the `stack` issues page?).

It doesn's work, but thanks still.
