### ISSUE TITLE
namespace var not parsed into StyVar

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#442]
Repro: look at the AST for `const` namespace in `penrose-web/src/compiler/asts/linear-algebra-paper-simple.ast.json` on `style-compiler-port`

Expected: Namespace contents are a `StyVar`

Got: 

```
            "header": {
                "start": {
                    "line": 1,
                    "col": 0
                },
                "end": {
                    "line": 1,
                    "col": 5
                },
                "tag": "Namespace",
                "contents": {
                    "start": {
                        "line": 1,
                        "col": 0
                    },
                    "end": {
                        "line": 1,
                        "col": 5
                    },
                    "tag": "Identifier",
                    "value": "const",
                    "type": "identifier"
                }
            },
```

Suggested fix:

* `header.contents` should conform to `StyVar` schema
* Delete `namespace?` field on `Selector` in `types.d.ts`

**Comment by wodeni** [comment]
I'm not sure what your suggestions mean. `namespace` is for the `as` syntax, so we shouldn't remove it. I changed the parser to conform to the `Namespace` schema in 7b39f52.
