### ISSUE TITLE
hackage.haskell.org doesn't have 1.0.1

### ISSUE THREAD

**Issue by yurivict** [penrose/penrose#452]
The last version listed on https://hackage.haskell.org/package/penrose is 0.1.1.1 which isn't listed here on GitHub.

**Comment by hypotext** [comment]
Thanks for the reminder! We are currently porting to typescript--look out for an `npm` published package hopefully soon.

**Comment by impetus1** [comment]
If you're in need of BSD developers I am kind of helpful!
