### ISSUE TITLE
Substance parser mis-parses a nested predicate as a function

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#453]
**Describe the bug**
There is a test program for which Substance parses a nested predicate as a function. This causes the Style compiler to not be able to match properly.

**To Reproduce**

In `style-compiler-port`'s most recent commit, the Substance parser is run on `TestDebug.ts` (which is a minimal test program). The Substance line that is misparsed is: `Not(Intersecting(B, C)) `

Here is the JSON from the parser: https://gist.github.com/hypotext/0dc429948c09b93e6e121a82559f980b

Notice that in the JSON, `Not` is an `ApplyPredicate` but `Intersecting` is a `Func`.

You can see then that the Style compiler doesn't match correctly with the third selector, which contains a nested predicate.

**Expected behavior**

`Intersecting` is parsed as an `ApplyPredicate` (and this works for nested predicates in general).

**Comment by hypotext** [comment]
Otherwise I've been pleasantly surprised by the lack of bugs in the Domain/Substance toolchain so far!

**Comment by wodeni** [comment]
Testing does help 😏. Anyway, this is expected behavior, as the parser allows any SubExpr as an argument to a predicate. The semantic checker doesn’t produce a more refined AST unfortunately. Therefore, a simple equality check is probably insufficient. As a workaround, you could type check the selector first, and write a comparison function to actually check equality.

**Comment by hypotext** [comment]
Not sure I understand what you mean by "expected behavior" -- for this particular program triple, `Intersecting` is defined as a predicate in the Domain program, so it should be unambiguously parsed as a predicate, not a function, right? So I would still believe that this is something the parser should be able to do (i.e. should not be handled by the compiler). (And there are no other functions called `Intersecting` in the Domain program, so there's no clash.)

Relevant line from Domain in `TestDebug.ts`: `predicate Intersecting : Set s1 * Set s2`

**Comment by wodeni** [comment]
> Not sure I understand what you mean by "expected behavior" -- for this particular program triple, `Intersecting` is defined as a predicate in the Domain program, so it should be unambiguously parsed as a predicate, not a function, right? 

No, different from the Haskell version, the Substance parser is independent from the Domain context. Therefore, given that the grammar is ambiguous, it can only parse the arguments into a generic Func.

My reasoning for independent parsers: they not only fit better with nearley’s design, and are also useful for language services such as semantic highlighting.

**Comment by wodeni** [comment]
By the way, it should be easy to write a small function that traverses the AST and replaces the tag of every single Func node by its appropriate tag. This can be done either pre or post checking I believe. You can take advantage of the `children` key in all AST nodes for free traversal.

**Comment by hypotext** [comment]
Sure, I can preprocess the Substance AST after it is checked and before the Style compiler uses it. Is there any other parse ambiguity I should be aware of? Or is that the only one? 

I remember there was something about value constructors... if you can make a complete list of them that would be very helpful.

**Comment by wodeni** [comment]
In the Substance parser, the Func type is the only ambiguous one. It appears not just as arguments of predicates, but also anywhere a SubExpr is allowed.

**Comment by wodeni** [comment]
Seem like there's no action needed on the parser's end. Closing the issue for now.
