### ISSUE TITLE
changing the program triple doesn't auto-update the image in the renderer

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#456]
**Describe the bug**
If one program triple was already running in the frontend via `roger watch` and then the program triple is changed, the frontend doesn't auto-refresh and display the new inputs, instead requiring a manual refresh in the browser.

**To Reproduce**
Happens on `style-compiler-port` latest commit. This is probably because we didn't do anything special to implement this behavior yet. But I don't know if the fix would be in CLI or in App or both.

**Expected behavior**
Expect to see the initial state of the diagram of the new program triple

**Comment by wodeni** [comment]
I think you’ll need to refresh the page if roger updates, as the front end doesn’t continuously listen to file changes from roger. @maxkrieger rigjt?

**Comment by maxkrieger** [comment]
Correct. Easy fix tho - just have to add a reconnect-on-error event to the frontend websocket object.

**Comment by maxkrieger** [comment]
Donezo (in `style-compiler-port` - forgot to ref the issue in the commit message). Thanks for the assignment nudge @wodeni 😛 . Did the feature according to Will's suggestion in #462

![Kapture 2021-02-02 at 1 20 12](https://user-images.githubusercontent.com/2660634/106560338-df889480-64f4-11eb-8b93-889c865d9101.gif)

**Comment by maxkrieger** [comment]
If button pressing is too much of a pain I can have an auto-reconnect loop on a 3 second or so interval. It'll flood the console like before but means less clicking. Lemme know.

**Comment by wodeni** [comment]
Works beautifully. Thanks @maxkrieger! I think the button works well for me. Closing the issue for now.

**Comment by hypotext** [comment]
Thanks! If roger changes, what manual steps (if any) are needed to rebuild it? Can this be documented somewhere?

**Comment by maxkrieger** [comment]
@hypotext thanks to npm link, it somehow just works without any build steps. when/if we distribute Roger, obviously that'll change
