### ISSUE TITLE
add declare-and-bind back to Substance syntax

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#457]
**Is your feature request related to a problem? Please describe.**
Having the ability to write `T x := e` instead of `T x \n x := e` would make life a lot easier for reading and writing Substance. (see e.g. `pythagorean-theorem-sugared.sub`). Also, as currently implemented in Haskell, I believe it is done specially in a parse stage, and is not even part of the syntactic sugar mechanism (since it should be available to all domains). Shouldn't be too much work.

I would like this to be available to users in the upcoming web port since we don't have a clear timeline for the syntactic sugar.

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
None

(Unless this is already implemented and is a bug? When I try to use it, the parser says

```
Unhandled Rejection (Error): Syntax error at line 3 col 14:

  Triangle ABC :=
               ^
Unexpected def token: ":=". Instead, I was expecting to see one of the following:
```

Can give more info if needed)

**Comment by wodeni** [comment]
Just added `decl_bind` to the parser in c6760e0. Closing now.

**Comment by hypotext** [comment]
Thanks!!
