### ISSUE TITLE
Style parser parses some strings into JS strings that include quote delimiters, causing frontend crash

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#458]
**Describe the bug**

See title.

**To Reproduce**

Here is the line in `venn-3d.sty`: `path : "shading.svg"`
Here is the AST snippet: 

```
 "tag": "StringLit",
 "contents": "\"shadow.svg\""
```

This causes a frontend crash in `scp` latest commit, when running `set-theory-domain/tree.sub set-theory-domain/venn-3d.sty set-theory-domain/setTheory.dsl`, as it tries to lookup an image path that doesn't exist with the extra quote marks.

**Expected behavior**
I would expect strings to be parsed into JS strings without the quote delimiters.

**Comment by hypotext** [comment]
This appears to be a bug for string parsing in general. It is also affecting `continuousmap.sty` and `hyperbolic.sty` as they both use strings to set the stroke of a shape, e.g. `override `V`.icon.strokeStyle = "dashed"`.

**Comment by wodeni** [comment]
Thanks for catching this. Just fixed it and added a test case for it :D.
