### ISSUE TITLE
Option to manually connect to backend/backend auto-recompilation on file change

### ISSUE THREAD

**Issue by Dsm0** [penrose/penrose#462]
The development server continuously tries to connect to the haskell backend, but it floods the console with WebSocket error messages, which is irritating if you want to recompile a given diagram multiple times.

![Screenshot from 2021-02-01 21-43-06](https://user-images.githubusercontent.com/45471522/106545512-7fcfc080-64d7-11eb-97e6-cf39cbaac4c8.png)

There could be an option in the frontend to toggle manual/automatic connections to the backend, with manual connections triggered by a button.
Another solution would be to simply add a backend command line option to attempt a recompilation every time a loaded file has changed. However, there would still be a flood of error messages while you're trying to fix some bug preventing the diagram from compiling, so the issue wouldn't fully be resolved.

Ultimately, this is just a minor irritation, but it wouldn't be too hard to add.

**Comment by maxkrieger** [comment]
thanks for this suggestion Will! Katherine also suggested this in #456 so I just made a tweak in our working branch where it tracks the connection state and does not reconnect until a button is pressed.

The `ERR_CONNECTION_REFUSED` is unfortunately not suppressible according to this https://stackoverflow.com/a/31003057/10833799 so it remains a good question of what the reconnect workflow will be. Maybe the new CLI will have an option to switch the currently loaded file while it's running.
