### ISSUE TITLE
Build error with stack

### ISSUE THREAD

**Issue by miatang13** [penrose/penrose#463]
**Describe the bug**
When downloading backend following the guideline [Building and running](https://github.com/penrose/penrose/wiki/Building-and-running) step 5, the process exits because it can't load framework Accelerate at [16 of 21]. 

**To Reproduce**
1. step 1-4 of Building and running installing backend.
2. Run `stack clean`
3. Run `stack install`
4. Process exits due to error. 

**Expected behavior**
A successful build.

**Screenshots**
![image](https://user-images.githubusercontent.com/58094634/106798488-e3123d80-6612-11eb-90d7-5b1b6cd40ef2.png)

**Desktop (please complete the following information):**
- Mac OS

**Additional context**
None.

**Comment by maxkrieger** [comment]
Closing due to deprecation of stack on `master` 😄
