### ISSUE TITLE
pRNG is no longer p

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#466]
**Describe the bug**

The same seed(?) (if page is refreshed) no longer generates the same diagram. Not sure if duplicate or TODO.

**Comment by maxkrieger** [comment]
#352 related?

**Comment by hypotext** [comment]
Oops, this got lost amid the large pile of issue cleanup. Yes, it's no longer pseudorandom, and it is a TODO to make it pseudorandom. The Style compiler in fact just calls @wodeni's code for shape resampling and property/field initialization (which was already not pseudorandom). :)

**Comment by wodeni** [comment]
@hypotext i think the shape sampler can be pseudorandom, just not done purely :). Might be an issue of setting a seed explicitly.

**Comment by wodeni** [comment]
Just did it by setting the global seed in #472. Closing.

**Comment by hypotext** [comment]
Thanks for fixing this!
