### ISSUE TITLE
better automation for improving error/warning reports

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#476]
**Is your feature request related to a problem? Please describe.**
Currently it takes some effort to open an issue, and report all the info, when the system crashes and there's an odd error or warning. 

**Describe the solution you'd like**
It would be much easier for folks if we had a built-in bug report mechanism that dumped the program triple, crash trace, error message, etc. and auto-opened an issue.

Team members could also describe what error they expected to get.

**Comment by maxkrieger** [comment]
Yeah this is a good idea. We can generate a link that auto-opens a GitHub issue with relevant content.
