### ISSUE TITLE
Arrowhead markers not rendered

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#481]
**Describe the bug**
There seems to be a regression on `Arrow` rendering. Not sure if the example changed or the renderer differed from the original version. 

**To Reproduce**
1. Run `roger watch twoVectorsPerp-unsugared.sub linear-algebra-paper-simple.sty linear-algebra.dsl`
2. Check the output diagram:
![image](https://user-images.githubusercontent.com/11740102/108080632-18208600-703e-11eb-8bd8-bb36c2d00122.png)

**Expected behavior**
Expected result:
![image](https://user-images.githubusercontent.com/11740102/108081207-adbc1580-703e-11eb-937b-7c558bf70f9b.png)

**Comment by maxkrieger** [comment]
possibly related, but hopefully not (unresolved) https://stackoverflow.com/questions/58166286/svgmarker-arrowhead-not-always-displayed

**Comment by maxkrieger** [comment]
Semi-minimal reproduction https://codesandbox.io/s/blissful-franklin-1sxr1
