### ISSUE TITLE
show errors more visibly to users in the frontend

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#486]
**Is your feature request related to a problem? Please describe.**
Currently, when there are fatal errors, the frontend displays a blank screen with no indication that things have gone wrong. Errors are only logged in the console in `App.tsx`'s `connectToSocket`, and are buried among other random internal warnings/errors. That seems like it would be unintuitive to most users. 

**Describe the solution you'd like**
Can we display the error string in the diagram display area in the frontend? That would greatly improve the user experience. (Not sure about the preferred way to do this, which is why I'm filing an issue, cc @wodeni @maxkrieger)

**Describe alternatives you've considered**
Errors could be reported inline in an IDE as they are made, but we currently don't have IDE/language services.

**Additional context**
Below is what it looks like when a Style error is thrown (about GPI properties).

![image](https://user-images.githubusercontent.com/2762356/108432498-78682100-7212-11eb-876c-ae5b1940458b.png)

**Comment by maxkrieger** [comment]
Yes I shall add an inspector pane now

**Comment by hypotext** [comment]
Cool. Can we make sure to display the error as visibly as possible (rather than hidden in a pane)?

**Comment by maxkrieger** [comment]
Sure. We should keep thinking about warnings hmmm

**Comment by maxkrieger** [comment]
![image](https://user-images.githubusercontent.com/2660634/108456903-6badf200-723f-11eb-84d9-449e5b5a6439.png)

**Comment by hypotext** [comment]
The screenshot looks good to me! I can test out the PR tomorrow.
