### ISSUE TITLE
throw error on invalid labels

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#492]
**Describe the bug**
If a label is invalid, no error is thrown in the console or reported in the inspector. Instead, the desired label simply does not render. The rest of the labels (if valid) show up fine.

**To Reproduce**
For any Substance program with labels, write an invalid label, e.g. `Label e1 $\frac{1]{e^x$` (note nonterminated curly brace).

**Expected behavior**
The diagram does not render, and an error is thrown, and reported in the inspector, that indicates the incorrect label string, and perhaps the location that was incorrect (as reported by MathJax).

**Additional context**
Happens on latest `main`

**Comment by samestep** [comment]
As an example (for noobs like me):
```sh
yarn start
```
```sh
cd examples/set-theory-domain
npx roger watch continuousmap.sub continuousmap.sty setTheory.dsl
```
Then delete one of the curly braces in `continuousmap.sub` and observe what happens.
