### ISSUE TITLE
write tests to check correctness of derivatives for discontinuous/boolean operations

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#496]
Not super clear whether the generated gradient code properly differentiates through boolean and control flow statements:

* `ifCond` -- presumably the derivative branches and is either the derivative of left or right
* `min`, `max` -- presumably the derivative branches and is either the derivative of left or right
* `and`, `or`, `gt`, `lt`, `eq` -- presumably no derivative?

So far though, not a lot of code uses `ifCond` (which I believe had the wrong derivative earlier).

**Comment by wodeni** [comment]
Bump: is this still relevant after #907?

**Comment by samestep** [comment]
According to a conversation I just had with @keenancrane, the way we're currently doing this (including the new stuff I did in #906) is correct.
