### ISSUE TITLE
Optimization error when running `nested.sub`

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#498]
**Describe the bug**
Strange autodiff/opt error when running `nested.sub`. This example works on `v1.01.alpha.10` (e94c0627ed9c594fa6b452120b0fe4fca1ae509a) but is broken on `v1.01.alpha.13`.

**To Reproduce**
1. `roger watch nested.sub venn.sty setTheory.dsl`

**Screenshots**
![image](https://user-images.githubusercontent.com/11740102/109217119-65f66600-7783-11eb-999e-1c8d71e72314.png)

**Comment by hypotext** [comment]
FYI the NaN seems to actually appear on 9fbe49f27cd90500f27e20bdb1010692795d171a (the multiline commit), not the one before it (style fixes). 

Maybe something to do with label dimensions? I did a quick check and the labels appear to render correctly with dimensions that make sense, and `nested.sub` doesn't have complicated labels. So it's not obvious to me what would cause this. Happy to look into it more next week.

**Comment by wodeni** [comment]
> FYI the NaN seems to actually appear on [9fbe49f](https://github.com/penrose/penrose/commit/9fbe49f27cd90500f27e20bdb1010692795d171a) (the multiline commit), not the one before it (style fixes).
> Maybe something to do with label dimensions? I did a quick check and the labels appear to render correctly with dimensions that make sense, and `nested.sub` doesn't have complicated labels. So it's not obvious to me what would cause this. Happy to look into it more next week.

Gotcha. Thanks for looking into this! Let's look into it again next week.

**Comment by joshpoll** [comment]
I did some digging and this issue doesn't seem to be directly related to labels. The NaN appears even if the text labels are replaced with fixed-size rectangles. Moreover, with both text and rectangle labels, stepping manually does not generate NaNs and converges properly.

**Comment by wodeni** [comment]
Resolved by #628.
