### ISSUE TITLE
re-encode working examples as test suite

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#499]
Make sure all of them can run without NaNs. Including the nested example from #498.

Data: https://github.com/penrose/penrose/wiki/Example-diagrams

Required: schema @maxkrieger 

https://github.com/penrose/panels/blob/master/src/dummy-registry.json

**Comment by hypotext** [comment]
In the meantime, should we add to the PR template: "- [ ] All existing Penrose diagrams work"?

**Comment by maxkrieger** [comment]
Hmm is this resolved? I guess the `NaN` checking isn't cc @wodeni

**Comment by wodeni** [comment]
Resolved as we have `overall.test` now.
