### ISSUE TITLE
fix findExpr cases

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#503]
This line is not strictly correct:
 https://github.com/penrose/penrose/blob/ffeb55be7df0323e52e312edf17c0fb29b68517d/packages/core/src/engine/EngineUtils.ts#L861)
https://github.com/penrose/penrose/blob/ffeb55be7df0323e52e312edf17c0fb29b68517d/packages/core/src/engine/EngineUtils.ts#L862

...but `findExpr` is not used for values, so it's fine for how. Need to think more about what result this is supposed to return.

**Comment by samestep** [comment]
I believe this should be closed since #984 deleted the `findExpr` function.
