### ISSUE TITLE
Polygon/Polyline optimizing points

### ISSUE THREAD

**Issue by Dsm0** [penrose/penrose#513]
There's an issue with the optimization of point values for polygons and polylines.
The issue can be examined on the polygon branch, with the `shape-spec` example.

The optimization for number-literal values behaves as it should, (although it cannot be dragged).
```
forall Polygon j {
	j.icon = Polygon { 
        points: ((-80.0, 0.0), (100.0, 0.0), (10.0, 50.0))
        strokeWidth: 200
	}
}
```

When point values are declared with question-marks, the style compiler crashes.
```
forall Polygon j {
	j.icon = Polygon { 
        points: ((?, ?), (100.0, 0.0), (10.0, 50.0))
        strokeWidth: 200
        pathLength :2000
	}
}
```

However, when point values are declared with variables, and those variables are question marks, the style compiles, but there's some strange dragging behavior.

```
forall Polygon j {
    x1 = ?
    y1 = ?
    x2 = ?
    y2 = ?
    x3 = ?
    y3 = ?
	j.icon = Polygon { 
        points: ((x1,y1), (x2,y2), (x3,y3))
        strokeWidth: 200
	}
}
```

**Comment by hypotext** [comment]
Hey @Dsm0 I'm happy to look into this. The issue is probably that we never tested polygon optimization.

Can you include a minimal program triple (or commit on a branch) that I can run to reproduce the problem? Can you also include the full Style errors you are getting, as well as more info about the dragging behavior? Thanks!

**Comment by hypotext** [comment]
Ah, I missed your information here: 

> The issue can be examined on the polygon branch, with the shape-spec example.

Will investigate when I get a chance -- polygon optimization doesn't currently seem super high-priority, but let me know if this becomes a blocker for you.

**Comment by wodeni** [comment]
Cannot repro this anymore. Tried the following and it seems to be just fine:

```
canvas {
    width = 100
    height = 100
}

global {
    Polygon {
        points: [(0, 0), (?, ?), (20, 20)]
    }
}
```
