### ISSUE TITLE
Improve Style error messages even more

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#514]
So far:

* For infinite circular references, report the offending path and line number. e.g.

```
U.text = Text {
    string: U.text // Crashes with bad error
}
```

* Report line numbers everywhere.

**Comment by samestep** [comment]
@wodeni Does this relate to #894?

**Comment by wodeni** [comment]
Bumping this because I think we are pretty close to having line numbers everywhere, especially after @liangyiliang's recent PRs.
