### ISSUE TITLE
deal with aliasing in translation

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#521]
Currently some operations don't work WRT path aliasing. For example, something like this doesn't work:

```
o.v1 = (?, 2.)
o.shape = Line {
start: o.v1
}
override o.shape.start[0] = 0.
```

Presumably, you want then to look up the reference `o.v1` and set its first element to 0.

**Comment by samestep** [comment]
I think this should be closed as of #984, because we no longer support `override` on access paths.
