### ISSUE TITLE
Show energies in inspector

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#528]
thanks to #527

Debug mode

@hypotext requests:

- [ ] Sort by current energy
- [ ] Over time - optimizer log
  - [ ]  callback api?

- in-situ energy by highlighting
- clique of objects

related: #281 etcetc

- some term thats gotten out of hand
- sort energy terms by size - horserace diagram - @keenancrane 
   - not necessarily the magnitude of the energy
   - stiffness of the energy - dE/dt - sort by magnitude of energy gradient
   - inner product descent direction with un-preconditioned gradient

- unrelated: iterate without re-allocating matrices - maybe abstract matrix allocation into another fn
- keenan audit of optimizer - put everything in 1 matrix?

**Comment by maxkrieger** [comment]
- [ ] autostep+numsteps per display step localstorage

**Comment by hypotext** [comment]
Maybe don't auto-close as we still have a number of requested features? Or consolidate w/ related issues #25 #281

**Comment by wodeni** [comment]
Closing in favor of #281
