### ISSUE TITLE
Labels disappear on drag or inspector frame selection

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#535]
Possibly due to ID conflicts throughout the DOM among MathJax refs.

**Comment by joshpoll** [comment]
This also seems to happen when downloading the SVG.

**Comment by wodeni** [comment]
Update: bizarre case of disappearing labels when multiple diagrams are shown on the same page:
![image](https://user-images.githubusercontent.com/11740102/141319951-77bc5831-451b-414c-91e1-65be2f2ffbce.png)
Deleting `memoize` in `collectLabels` fixed it, although I wasn't sure about the effect on performance. Also, even with `memoize` gone, the other phenomena in this issue still persisted.

**Comment by wodeni** [comment]
Another example likely for the same reasons: in `synthesizer-ui`, exporting the diagrams cause the labels to disappear on the page.
