### ISSUE TITLE
No 1.1.0 tag on hackage

### ISSUE THREAD

**Issue by yurivict** [penrose/penrose#546]
**Describe the bug**
1.1.0 is missing here: https://hackage.haskell.org/package/penrose

**Comment by wodeni** [comment]
Thanks for the catch, @yurivict! Penrose is now ported to TypeScript. Our latest release of the `core` package is [available on NPM](https://www.npmjs.com/package/@penrose/core).  To install the new version of Penrose, feel free to check out the [wiki page](https://github.com/penrose/penrose/wiki/Getting-started) for more details.
