### ISSUE TITLE
Line numbers in error messages related to constraints, objectives, and computations

### ISSUE THREAD

**Issue by joshsunshine** [penrose/penrose#548]
**Is your feature request related to a problem? Please describe.**
When a user encounters an error message related to a constraint, objective, or computation the error message does not refer back to the line number in the style program that generated the constraint, objective, or computation.

**Describe the solution you'd like**
When a constraint/objective/computation is generated by the system it should have a pointer to the AST node that generated it.
For example, if the code that defines a constraint tries to access a shape property that does not exist then the related error message should be able to refer to the constraint definition in the style program.

**Comment by wodeni** [comment]
Addressed by #1352
