### ISSUE TITLE
Set node engine requirement

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#552]
We aren't really compatible with node ≤ 14 anymore due to some es6+ features. To prevent build debug headaches, we can auto enforce a minimum node version by setting the corresponding "engine" package.json keys

**Comment by wodeni** [comment]
Bumping this issue because of #565. In that issue, the fix was actually __downgrading to Node v12__, and somehow estrella works just fine with Node v12. 

So, it's still a bit unclear to me what version of Node we are requiring...

**Comment by samestep** [comment]
Note: this issue doesn't seem to occur using Node v17.0.1 on macOS.

**Comment by wodeni** [comment]
Node v12 is no good now because:

```
error @docusaurus/core@2.0.0-beta.20: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"
```

Updating the wiki to require Node v14+. Do we still want to set `engine` now that it's clear?

**Comment by wodeni** [comment]
Discussed with @samestep and decided the best way to test this is actually running our code in a matrix of node versions/os environments, instead of setting `engines`
