### ISSUE TITLE
PathString should convert to screen space?

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#560]
Quick note on comparing `Path` and `PathString` shapes: shouldn't latter convert its inputs to screen space as `Path` does using `toScreen`? I would think the Style user would expect the path string inputs to be in the same coordinate space as all the other GPIs. Admittedly, it is annoying to do this for `PathString` as you would have to parse and tokenize the string. What do you think @maxkrieger?

**Comment by hypotext** [comment]
Shouldn't `Polygon` and `FreeformPolygon` do this too?

**Comment by wodeni** [comment]
All good points. Somehow I missed that when reviewing both #539 and #549. It's a fairly minor fix. If you need it in #556, please feel free to ship the fix there. If not, we can get to it later.

**Comment by hypotext** [comment]
Cool. Let's squash this during next eng meeting @wodeni @maxkrieger

**Comment by samestep** [comment]
Closing this because we removed `PathString` in #743.
