### ISSUE TITLE
fix JSONification of parameters esp. as they appear in the opt inspector pane

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#562]
As reported by P1 of domain expert study:
> It would be helpful if the constraints with long JSON objects were compressed so it's easier to scroll to the other columns

Should be an easy fix.

+ Suggested by P3 in domain expert study on 6/11/21

**Comment by joshpoll** [comment]
This is partially addressed by #611, which adds some more pretty printing to the Opt tab.

**Comment by wodeni** [comment]
Although long names are still an issue in that UI, closing this one as JSON objects aren't the issue now.
