### ISSUE TITLE
Windows line endings don't work at panes.penrose.ink

### ISSUE THREAD

**Issue by JonathanAldrich** [penrose/penrose#563]
**Describe the bug**

I can't use panes.penrose.ink on Windows because when I put a line ending into any of the files, Penrose gives me a lexer error.  Here's the complete error message:

```
Error: invalid syntax at line 1 col 11:

  type Type1
            ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

A ws token based on:
    _$ebnf$1 → _$ebnf$1 ● %ws
    _ →  ● _$ebnf$1
    type$ebnf$1$subexpression$1 →  ● _ "(" _ type_params _ ")"
    type$ebnf$1 →  ● type$ebnf$1$subexpression$1
    type → "type" __ identifier ● type$ebnf$1
    statement →  ● type
    statements → _ ● statement _c_ "\n" statements
    input →  ● statements
A "<:" based on:
    subtype → type _ ● "<:" _ type
    statement →  ● subtype
    statements → _ ● statement _c_ "\n" statements
    input →  ● statements
A "(" based on:
    type$ebnf$1$subexpression$1 → _ ● "(" _ type_params _ ")"
    type$ebnf$1 →  ● type$ebnf$1$subexpression$1
    type → "type" __ identifier ● type$ebnf$1
    statement →  ● type
    statements → _ ● statement _c_ "\n" statements
    input →  ● statements
A "\n" based on:
    statements → _ statement _c_ ● "\n" statements
    input →  ● statements
A ws token based on:
    _c_$ebnf$1$subexpression$1 →  ● %ws
    _c_$ebnf$1 → _c_$ebnf$1 ● _c_$ebnf$1$subexpression$1
    _c_ →  ● _c_$ebnf$1
    statements → _ statement ● _c_
    input →  ● statements
A comment token based on:
    comment →  ● %comment
    _c_$ebnf$1$subexpression$1 →  ● comment
    _c_$ebnf$1 → _c_$ebnf$1 ● _c_$ebnf$1$subexpression$1
    _c_ →  ● _c_$ebnf$1
    statements → _ statement ● _c_
    input →  ● statements
A multiline_comment token based on:
    comment →  ● %multiline_comment
    _c_$ebnf$1$subexpression$1 →  ● comment
    _c_$ebnf$1 → _c_$ebnf$1 ● _c_$ebnf$1$subexpression$1
    _c_ →  ● _c_$ebnf$1
    statements → _ statement ● _c_
    input →  ● statements
```

**To Reproduce**

Go to panes.penrose.ink using Chrome in Windows 10.  Open the DSL tab.  Enter the following in the DSL tab:

```
type Type1
type Type2
```

Press compile.  You'll get the error message listed above.

**Expected behavior**

I expect it to compile without error.  I tested the same thing on Ubuntu Linux with Firefox and got no error.

**Screenshots**

![windows-line-ending-error](https://user-images.githubusercontent.com/2341533/119271401-55615a80-bbcf-11eb-8bc2-01419a66350a.png)

**Desktop (please complete the following information if applicable):**
Chrome on Windows 10

**Comment by wodeni** [comment]
Is the same issue happening when you are running Penrose locally @JonathanAldrich? I remember fixing it in the parsers (https://github.com/penrose/penrose/pull/500), but the monaco might be doing something to the source string (cc @maxkrieger).

**Comment by JonathanAldrich** [comment]
I don't know.  Getting Penrose to build locally is so difficult I didn't try it again.  If you think it's important for fixing this bug, or if it's useful for me to test the Windows/Cygwin build again, I can do so.

**Comment by wodeni** [comment]
Window support seems to be working now. Closing for now.
