### ISSUE TITLE
Style selector matching doesn't scale; freezes app

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#566]
**Describe the bug**

Style selectors with many variables to match, in a large-ish Substance program, seem to take a long time.

Domain expert 1 reported: 

> Even without Zoom, Penrose hangs when I uncomment all the disjointness selectors. But I think this only adds one additional disjoint constraint to the problem relative to what we were looking at, so my uninformed guess is that it's freezing up while doing the pattern matching.

I believe this is the case. It is a known problem from past versions of the system. Indeed, it may be because I didn't port this optimization: 

https://github.com/penrose/penrose/blob/main/packages/core/src/compiler/Style.ts#L601

**To Reproduce**

https://github.com/srossd/penrose/commits/monoidal-category (waiting for latest changes to be pushed) — or any selector with a lot of distinct variables

**Expected behavior**

Style pattern matches don't take exponential time

**Comment by keenancrane** [comment]
I'm also bumping up against this issue.  Here's a minimal version of what I'm trying to do:

```
-- minimal.dsl
type S
type T
constructor f( T t1, T t2, T t3, T t4, T t5, T t6, T t7, T t8 ) -> S
```

```
-- minimal.sty
canvas {
   width = 240
   height = 180
}

forall S s; T t1; T t2; T t3; T t4; T t5; T t6; T t7; T t8
where s := f( t1, t2, t3, t4, t5, t6, t7, t8 ) {
   s.shape = Circle {
      center: (0,0)
      r: 10.0
   }
}
```

```
-- minimal.sub
T t1, t2, t3, t4, t5, t6, t7, t8
S s := f( t1, t2, t3, t4, t5, t6, t7, t8 )
```

The browser just hangs (and I'd guess it craps out even before we get to eight arguments).

**Comment by liangyiliang** [comment]
I'm closing this since _faster matching_ has been implemented.
