### ISSUE TITLE
improve wiki docs to clarify audience and FAQ

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#573]
- Clarify who each page is for
- Answer some FAQs ("how to make a label in Sub/Sty/DSL" "why isn't my shape showing up on canvas" etc)
- Document use of inspector
- Make sure GitHub search results are clean

Reported by P3 domain expert on 5/21/21

**Comment by samestep** [comment]
As @maxkrieger mentioned in https://github.com/penrose/penrose/pull/771#issuecomment-1008518452, we should migrate everything off the wiki and onto our docsaurus site.

**Comment by maxkrieger** [comment]
For the record I'm still in favor of throwing everything on the central docs site (most repos do this) - I don't remember us having a reversal

**Comment by wodeni** [comment]
Closing since this issue is out-of-date
