### ISSUE TITLE
Supporting LaTeX labels and `Label` statements

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#59]
# Proposed solution

* Allow LaTeX strings to be rendered in labels, e.g. `Label X $\sum_i^n\frac{x^2}{10}$
![image](https://user-images.githubusercontent.com/11740102/41427712-c4836992-6fd5-11e8-8f46-caa84c1d37e6.png)
* A labeling language, so Substance variables can be named in ASCII and given TeX labels, e.g.
```
Set A, B
f: A -> B
AutoLabel A, B
Label f $\sum_i^n \frac{x^2}{10}$
```
* We support three kinds of statements in our labeling DSL: 
  * `Nolabel xs`: forbids Substance objects from having labels. `xs` is a comma separated list of Substance identifiers.
  * `Label x s`: normal declaration of labels. Gives a Substance object with identifier `x` a label, where the content of the label is specified by `s`. `s` is a TeX expression in math environment (`"$f$"`) (TODO: do we want to have labels that are outside of math env as well, say `"hello world"`?)
  * `Autolabel xs`: automatically generates labels for all identifiers in `xs`. By default, a Substance id `a` will be translated into TeX math environment as `$a$`. 
    * Special keyword `All` can replace `xs`, which just refers to all Substance ids. 
* The semantics of label statements are determined by the ordering of them in the source file. 
  * If we have the following, `A` will end up not having any label. 
  ```
  Label A "AA"
  AutoLabel A
  NoLabel A
  ```
  
* In the system, we would add the two kinds of label declarations (manual vs. auto labeling) to the options of Substance statements.
```haskell
data SubStmt = {- all other Substance stmts -} | LabelDecl String String | AutoLabel [String]
```
*  __As a result, label statements can be interleaved with other Substance statements__. Thus, the following style is also supported:
```
Set A, B
AutoLabel A, B

f: A -> B
Label f $\sum_i^n \frac{x^2}{10}$
```
* In Style, a labeled Substance object, `X`,  will have a Graphical Primitive Instance (GPI) `X.text`, which is of type `Text`. If more than one shape is related to `X` and we want to assign labels to these objects, we can do:
```
Set A {
  component_1 = Circle {
      text = concat(A.text, "_1")
  }
  component_2 = Square {
      text = concat(A.text, "_2")
  }
}
```
* Do we want to have labels that are outside of math env as well, say `"hello world"`? If everything is by default in math env, then the following will be rendered as the label:
![image](https://user-images.githubusercontent.com/11740102/41426666-556f8d86-6fd2-11e8-8b27-9195fbcf71f2.png)
  * @hypotext: all label texts are double-quoted, in which TeX expressions are enclosed by dollar signs (`Label A "hello $f$"`). --> __Currently this is NOT supported and label text has to be enclosed by either quotes or dollar signs. The two cannot be mixed__ 
  * Current solution: `\textrm` works in MathJax!
* Can label statements be interleaved with other Substance statements?
  * @hypotext : YES

# Open questions: from TODOs

* In Style, how to design a mechanism for “don’t make a labeling objective in Style if A does not have a label”? Below are possible solutions:
  * `if x.labeled`, where `labeled` is a built-in field in a Substance object
  ```
  Set A {
    if A.labeled: labelFn = encourage -- some objective
  }
  ```
  * A built-in unary predicate `Labeled` in the core Substance language, so that we can write selectors for them:
  ```
  Set A 
  where Labeled(A) {    labelFn = encourage -- some objective }
  ```

**Comment by wodeni** [comment]
A package called [mathjax-node](https://www.npmjs.com/package/mathjax-node) does it with one function call. 
- The bounding box of the result is inaccurate though, as stated in the [source code](https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L313)

**Comment by hypotext** [comment]
Great!

To get the bounding box of an SVG, can we use a different library's method? ([Relevant SO](https://stackoverflow.com/questions/16377186/get-bounding-box-for-svg-path-using-jquery))

Also, does the library support using a more natural TeX syntax than `"\\[f: X \\to Y\\]"`? Ideally we'd write `$f : X \to Y$`.

**Comment by wodeni** [comment]
Current problems:

- `mathjax-node` and many other npm packages do it in a function call, but our JS frontend is all clientside JS code. Should we browserify the packages?
- If not, we will need to write something like the code snippet in the last comment. In that case, how does this code fit into our current module? 
- More generally, the JS file, `client.js` is getting too big to maintain and needs to be modularized. Maybe this is a good place to start dong so.

**Comment by wodeni** [comment]
I rewrote the JS frontend using [the module pattern](http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html), which is more readable and maintainable. 

During that process, I found the added code for new shapes to be non-readable. I have not tested the following shapes yet:
- [ ] Angle Marks  (significant refactoring needed)
- [ ] Parallelogram (significant refactoring needed)
- [ ] Ellipses

One other thing is I noticed that we are dealing with SVG path string more. I don't think string concatenation is the best way to handle them. Therefore, we need to use a library like [paths.js](https://github.com/andreaferretti/paths-js) to compose these SVG strings.

**Comment by hypotext** [comment]
Thanks for refactoring the front-end code! I agree that we should use a library like paths.js to compose SVG strings. d3 can do it too.

Can you coordinate with @dormaayan to refactor and test the new shapes?

**Comment by wodeni** [comment]
A quick teaser of __Penrose with \LaTeX__, coming soon:
![latex](https://user-images.githubusercontent.com/11740102/41574074-e38f41d2-734d-11e8-9848-e4bcb0fbc6ae.gif)

**Comment by hypotext** [comment]
Awesome. Makes the diagram look a lot nicer!

**Comment by keenancrane** [comment]
Incredible.  Is this being done with MathJax?

--
http://keenan.is/here

**Comment by wodeni** [comment]
Yes! I used MathJax to process all labels on startup 😄

**Comment by hypotext** [comment]
Suggestions from GC:
* set diagram font size as `global { global.fontSize = CANVAS * scaleFactor }` and let individual selectors use different font sizes locally e.g. `X.shape.text.fontSize = global.fontSize + 10` 
* what unit are we using for font size? em, px?
* let people optimize labels, e.g. size and angle
* allow label rotation
* in future, leave labels unrendered on top so people can render with their fonts of choice, instead of MathJax's default

**Comment by wodeni** [comment]
Closing the issue for now since PR has been merged. We'll come back to the abovementioned features in later stages of the implementation
