### ISSUE TITLE
Fix no-error crash

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#592]
When there is an error in the console, sometimes nothing shows up. The frontend should at least crash or show an error.

1. Repro no-error crash
2. Figure out how and where to report error

Context: "undescriptive console errors when a Style selector predicate is called with empty arguments when there should be arguments — typechecker failure to report error." This arose in domain expert study with P3 on 6/11/21.

**Comment by joshpoll** [comment]
Seems like this may be possible to implement using `window.onerror`
- https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror
- https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by wodeni** [comment]
Closing in favor of more concrete issues.
