### ISSUE TITLE
certain file triples take several seconds to optimize

### ISSUE THREAD

**Issue by hsharriman** [penrose/penrose#607]
**Describe the bug**
The optimization time for some file triples is on the order of 5-10 seconds per resample, and 3-5 seconds with a couple of `repel` constraints removed. After optimization, several of the constraints remain unsatisfied (see screenshot below)

**To Reproduce**
The branch: `main` of Penrose.  
domain: https://github.com/penrose/penrose/blob/main/packages/synthesizer/__tests__/geometry.dsl
substance: https://github.com/penrose/penrose/blob/main/packages/synthesizer/__tests__/congruent.sub
style: https://github.com/penrose/penrose/blob/main/packages/synthesizer/__tests__/euclidean.sty

Noticed that commenting out lines [144-145](https://github.com/penrose/penrose/blob/fec0dd9c7b6e93c64307f676409abb65bf1828ef/packages/synthesizer/__tests__/euclidean.sty#L144) in `euclidean.sty` dropped the optimization time from 5-10 seconds to 3-5 seconds

Steps to reproduce the behavior (from latest version of `main`):
1. `yarn start` from Penrose root
2. Run from Penrose root: 
```
npx roger watch packages/synthesizer/__tests__/congruent.sub packages/synthesizer/__tests__/euclidean.sty  packages/synthesizer/__tests__/geometry.dsl
```
5. Open `localhost:3000` and hit resample or reload the page

**Screenshots**
![Screenshot from 2021-06-21 17-39-19](https://user-images.githubusercontent.com/31522997/123337060-8baa3680-d4fb-11eb-9666-cdf33e1d87f9.png)

**Comment by hypotext** [comment]
Instead of repelling a label from a segment, you could try using a constraint that ensures that a label has some minimum distance from a segment, e.g. by calculating the closest point to the label as a point. (This function already exists as `closestPt_PtSeg`; you'd just need to write a wrapper around it to make it a constraint.) 

My intuition is that this will be faster since the closest point calculation doesn't subsample a segment. But it may also be more numerically unstable since the closest point may "jitter" around as the label is moved during optimization. 

Let me know what happens!

**Comment by joshpoll** [comment]
It looks like the diagram may be getting stuck in a local minimum where triangle CDE is nearly degenerate. Adding some constraints to prevent this might help. For example, encouraging angles to be less than 180 degrees.

<img width="285" alt="Screen Shot 2021-06-25 at 11 44 49 AM" src="https://user-images.githubusercontent.com/21694516/123450525-d59e2580-d5aa-11eb-8dc1-1c972538e915.png">

**Comment by joshpoll** [comment]
err I guess really encouraging angles to avoid 0 or 180

**Comment by joshpoll** [comment]
Adding this objective with this line in InteriorAngle `encourage nonDegenerateAngle(p.icon, q.icon, r.icon)` seems to help somewhat, but it's still slow. Also might be nice to add some cutoff so the repelling force doesn't apply for "nice" angles that aren't close to degenerate.

```
/**
   * Repel the angle between the p1-p0 and p1-p2 away from 0 and 180 degrees.
   */
   nonDegenerateAngle: (
    [, p0]: [string, any],
    [, p1]: [string, any],
    [, p2]: [string, any],
    strength = 20.,
  ) => {
    if (every([p0, p1, p2].map((props) => props["center"]))) {
      const c0 = fns.center(p0);
      const c1 = fns.center(p1);
      const c2 = fns.center(p2);

      const l1 = ops.vsub(c0, c1);
      const l2 = ops.vsub(c2, c1);

      const force = mul(constOfIf(strength), div(squared(ops.vdot(l1, l2)), mul(ops.vnormsq(l1), ops.vnormsq(l2))));

      return force;
    } else {
      throw new Error("collinear: all input shapes need to have centers");
    }
  },
```

**Comment by joshpoll** [comment]
(also the error message is wrong)

**Comment by hsharriman** [comment]
Implemented @hypotext suggested changes and the resample time is now down to 2-6 seconds. Adding @joshpoll changes doesn't really impact optimization time but the triangles definitely look nicer :+1:

**Comment by samestep** [comment]
Given @hsharriman's most recent comment here, should this issue be closed?
