### ISSUE TITLE
provide non-minified js

### ISSUE THREAD

**Issue by nschloe** [penrose/penrose#620]
[@penrose/core](https://www.npmjs.com/package/@penrose/core) provides
```
@penrose/core/build/dist/penrose.min.js
```
It's useful for developers to provide an unminified version as well.

**Comment by nschloe** [comment]
Perhaps related are some `eval()`s in the minified script. https://github.com/webpack/webpack/issues/4899

**Comment by samestep** [comment]
@wodeni Does this relate to #964?

**Comment by samestep** [comment]
Resolved by #1170.
