### ISSUE TITLE
Add "perpendicular mark" and "angle mark" as shapes

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#64]
[Intro task for Dor]

In several of our diagram styles, we use the perpendicular mark, but we haven't added it to the system yet. We'd like to add it to already-working diagrams (e.g. diagrams in the Cartesian style) as well as upcoming diagrams (e.g. diagrams in linear algebra that have perpendicular axes and perpendicular vector projections).

Can you add this shape to our system, as well as the past diagrams that use it? The steps to do this are outlined in the wiki [here](https://github.com/penrose/penrose/wiki/Extending-the-system).

Also, in general, we're going to need the "angle mark." This is usually denoted as an arc or a pie wedge, which you can see in the complex numbers blog post and in my raytracing diagrams. Can you add this as well?

**Comment by dormaayan** [comment]
## Checklist for Adding a New Shape
* In Shapes
  - [ ]  add `data Shape = …` along with its typeclass instances (e.g. `Named`, `JSON`)
  - [ ]  add a case to `data Obj = … | S Shape`
  - [ ]  add cases for that shape `S` in all of the derived Obj typeclass instances (`Located`, etc. if possible; some instances might not be possible)
  - [ ]  add a polymorphic version of that shape `data Shape' a = …` along with its typeclass instances (e.g. `Named`, `JSON`)
  - [ ]  add a case to `data Obj a = … | S’ (Shape’ a)`
  - [ ]  add typeclass instances for `Shape’`
  - [ ]  add typeclass instances for `Obj’`
  - [ ]  add property getters in `get` function
  - [ ]  add property setters in `set` function
* In Runtime
  - [ ]  add a case in `unpackObj`
  - [ ]  add a case and function in `pack’`, making sure the parameter order and number matches that in `unpackObj`
  - [ ]  add a case and function `initShape` in `getShape` to initialize it using `defaultShape`
  - [ ]  add a default shape definition `defShape`
  - [ ]  add a wrapper function `defaultShape`
  - [ ]  add a way to randomly sample the shape in `sampleCoord` (optional)
  - [ ]  add case for `addGrad` (adding gradients, converting to polymorphic floats)
  - [ ]  add case for `zeroGrad` (removing gradients, converting to `Float` type)
* In Style
  - [ ]  add a case to `StyType` (avoiding name clashes)
  - [ ]  add the name of the type as a reserved word in the `styObj` parser
* In Functions
  - [ ]  add cases to objective functions and constraints, e.g. `centerMap`
* In Computation
  - [ ]  update or add any computations that use the new shape
* In `client.js`
  - [ ]  add case for object rendering in `switch(record.tag)` (don’t forget the final `break` statement!)
  - [ ]  we currently only support snap as a renderer. Other renderers coming soon.

**Comment by dormaayan** [comment]
## Checklist for Adding a Angle Mark
* In Shapes
  - [ ]  add `data Shape = …` along with its typeclass instances (e.g. `Named`, `JSON`)
  - [ ]  add a case to `data Obj = … | S Shape`
  - [ ]  add cases for that shape `S` in all of the derived Obj typeclass instances (`Located`, etc. if possible; some instances might not be possible)
  - [ ]  add a polymorphic version of that shape `data Shape' a = …` along with its typeclass instances (e.g. `Named`, `JSON`)
  - [ ]  add a case to `data Obj a = … | S’ (Shape’ a)`
  - [ ]  add typeclass instances for `Shape’`
  - [ ]  add typeclass instances for `Obj’`
  - [ ]  add property getters in `get` function
  - [ ]  add property setters in `set` function
* In Style
  - [ ]  add a case to `StyType` (avoiding name clashes)
  - [ ]  add the name of the type as a reserved word in the `styObj` parser
* In Runtime
  - [ ]  add a case in `unpackObj`
  - [ ]  add a case and function in `pack’`, making sure the parameter order and number matches that in `unpackObj`
  - [ ]  add a case and function `initShape` in `getShape` to initialize it using `defaultShape`
  - [ ]  add a default shape definition `defShape`
  - [ ]  add a wrapper function `defaultShape`
  - [ ]  add a way to randomly sample the shape in `sampleCoord` (optional)
  - [ ]  add case for `addGrad` (adding gradients, converting to polymorphic floats)
  - [ ]  add case for `zeroGrad` (removing gradients, converting to `Float` type)
* In Functions
  - [ ]  add cases to objective functions and constraints, e.g. `centerMap`
* In Computation
  - [ ]  update or add any computations that use the new shape
* In `client.js`
  - [ ]  add case for object rendering in `switch(record.tag)` (don’t forget the final `break` statement!)
  - [ ]  we currently only support snap as a renderer. Other renderers coming soon.

**Comment by hypotext** [comment]
To understand the purpose of `pack` and `unpack`, it might help to read the [objective function synthesis doc](https://docs.google.com/document/d/1q8Zi2kdBBGQAwqm7AwXVSOnzeLlI-8PXIg5mSVSD8hk/edit) (if you haven't already done so). 

Also, the checklist should really include "write minimal Style programs that use the new shapes and new objectives. Test that they work by themselves and with existing shapes/objectives."

**Comment by dormaayan** [comment]
@hypotext , @wodeni : Is there currently any way to associate 2 shapes to an object in Style?
I don't want to add to Substance perpendicular and angle marks but for that I need to add those shape to already existing elements in my Style

**Comment by wodeni** [comment]
Yes. Please take a look at my [earlier doc](https://github.com/penrose/penrose/wiki/Parser-documentation#multiple-shapes-associated-with-the-same-object) for details. If that's not exactly you want, we can talk more about developing some other strategy to do so.

**Comment by hypotext** [comment]
Unifying the shapes sounds good. Once you have it working, please post screenshots of the angle marks in action.

**Comment by dormaayan** [comment]
Merged and done, small fits will be done while working on the LA visualization
