### ISSUE TITLE
Circle CI runs out of memory when building the system

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#651]
**Describe the bug**
Circle CI often fails with memory-related errors such as (see example [here](https://app.circleci.com/pipelines/github/penrose/penrose/2755/workflows/9e580cd6-1103-48cc-9597-5e6540ebee7f/jobs/5687)).

```
@penrose/browser-ui: The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
```

My guess is that lerna is not parallelizing the build processes (?), but haven't looked into how to improve it. @samestep proposed to move to GitHub Actions.

**Comment by cmumatt** [comment]
Is it worth removing the --stream parameter from the build command in package.json and observing for a change in the ratio of successful vs. unsuccessful builds in CI?  

Local tests indicate the OOM hunch is probably right: the current Docker instance provisions minimal RAM and we are at  that limit given the current streamed / interleaved build + Docker overhead.  Another option is to provision a larger Docker instance in CI by specifying a larger resource class in .circleci/config.yml.  

Either may clear the block and save time if we don't want to invest time re-platforming.

**Comment by wodeni** [comment]
> Is it worth removing the --stream parameter from the build command in package.json and observing for a change in the ratio of successful vs. unsuccessful builds in CI?

Yeah, `--stream` is just for streaming the stdout of child processes, but setting `--concurrency` to a lower number might be a good way. @cmumatt maybe we can experiment with `--concurrency 1` or `2`?  

> Local tests indicate the OOM hunch is probably right: the current Docker instance provisions minimal RAM and we are at that limit given the current streamed / interleaved build + Docker overhead. Another option is to provision a larger Docker instance in CI by specifying a larger resource class in .circleci/config.yml.

I thought I had this in `config.yml`, but yes we should add that too.

> Either may clear the block and save time if we don't want to invest time re-platforming.

Agreed.
