### ISSUE TITLE
browser-ui and panes should be made of the same material

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#659]
Maybe browser ui depends on a common set of UI components as panes. This lets inspector be used in panes etc.

- Let us embed substance editor

**Comment by wodeni** [comment]
> Maybe browser-ui should _be_ panes? Panes should definitely be in monorepo. @wodeni

Penrose devs do need a frontend for debugging. In the short run, moving panes to the monorepo sounds good to me. Perhaps integrating `browser-ui` into panes as "developer mode" is good too.

**Comment by maxkrieger** [comment]
Probably going to use https://nomcopter.github.io/react-mosaic/ and its companion https://blueprintjs.com/

**Comment by samestep** [comment]
@maxkrieger @wodeni Should this be closed as of #1000?
