### ISSUE TITLE
Add Linear Algebra Shapes

### ISSUE THREAD

**Issue by dormaayan** [penrose/penrose#66]
Add the following shapes to the system in order to support the Linear Algebra domain:

- [x] Parallelogram (for determinants)

- [x] Curly Brace or a sort of LengthMark (for norms)

- [x] Curved arrow (for linear map)

Write Substance and Style programs for testing the new shapes

**Comment by dormaayan** [comment]
Curved Arrow, this is simply an extension of regular arrow, simply by specifying "curved" as the style. The default is "straight":
<img width="738" alt="image" src="https://user-images.githubusercontent.com/19957447/39630707-28c5302a-4f7e-11e8-8dd9-373b6bc58a1d.png">

**Comment by wodeni** [comment]
@dormaayan What type of curve did you use in Snap? Looks like a polyline interpolated by Catmull-Rom? 
An elliptical curve looks way better for this purpose. In SVG path syntax, it's defined using the command string `A` (see [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) for further info).

**Comment by hypotext** [comment]
I believe all of Keenan's curved arrows are generated by taking an arc of a circle.

**Comment by dormaayan** [comment]
Parallelogram:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/19957447/39682236-c5cfa526-517c-11e8-90e7-4230feaead5e.png">

**Comment by dormaayan** [comment]
Length Vector or Norms:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/19957447/39706351-26b5b5bc-51df-11e8-8ed2-f3d779925cab.png">

**Comment by hypotext** [comment]
I'll wait to review this PR until after we have the linear algebra DSL implemented, so we can use the shapes together.

**Comment by dormaayan** [comment]
@hypotext , Yes all the shapes are implemented now on a separate branch, we will merge everything when will need to use them, I move it to the next milestone of linear algebra domain

**Comment by hypotext** [comment]
Sounds good!

**Comment by dormaayan** [comment]
This is done and now integrated with the linear algebra domain branch, I don't think this works needs a code review for now.

Close the issue
