### ISSUE TITLE
observable broken

### ISSUE THREAD

**Issue by xrmx** [penrose/penrose#670]
Hello, 

the following observable https://observablehq.com/@tophtucker/hello-penrose linked from https://github.com/penrose/penrose/wiki is broken with `penrose = TypeError: qy is undefined` in Firefox, Chromium prints `penrose = TypeError: Cannot read properties of undefined (reading 'MathtoolsMethods')`. 

My browser logs in the console:

```
Uncaught ReferenceError: module is not defined
    <anonymous> Lodash
index.js:377:1
    <anonymous> Lodash
```

**Comment by wodeni** [comment]
Updated the wiki page to link to the fork for now. Will change it back if the original author decides to update it. Thanks again for catching this @xrmx!
