### ISSUE TITLE
install-cli script does not exist

### ISSUE THREAD

**Issue by carlotm** [penrose/penrose#673]
On this page: https://penrose.github.io/penrose/typedoc/ 

The suggested command to add `roger` to the PATH does not exist (anymore?)

```
> npm run install-cli
npm ERR! missing script: install-cli

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carloratm/.npm/_logs/2021-11-02T13_55_24_813Z-debug.log
```

**Comment by wodeni** [comment]
Thanks for catching this. The README for `core` is outdated. Working on updating the docs! Following the [building and running wiki page](https://github.com/penrose/penrose/wiki/Building-and-running) should take care of everything. If you want to globally install `@penrose roger`, try `npm i -g @penrose/roger`.

**Comment by carlotm** [comment]
@wodeni Nice, thank you! Working fine.
