### ISSUE TITLE
Example of Multiple shapes associated with the same object fails

### ISSUE THREAD

**Issue by dormaayan** [penrose/penrose#69]
while running (on `Master`) the example for @wodeni doc: 
`.\runpenrose snap sub/twosets-subset.sub sty/arrow.sty`
Receive the following error:
`runpenrose: cannot access label of non-shape:
BinOp Access (Id "x") (Id "label")
CallStack (from HasCallStack):
  error, called at src/Style.hs:506:62 in main:Style`

**Comment by wodeni** [comment]
@dormaayan  the parser tests simply go through every single file in `sub/` and `sty/` and attempt to parse them all. Therefore, any local files that are __not__ tracked by git can also be included. Also, the test suite does output the error messages. You can also try to look at them. If any of those doesn't make sense, feel free to let me know and we can work on them together 😄
