### ISSUE TITLE
Include source-maps in ui/ide webpack

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#697]
**Is your feature request related to a problem? Please describe.**
Engineers presently find it difficult to client-side debug Penrose due to lack of sourcemaps in the webpack.

**Describe the solution you'd like**
Configure webpack to output source maps during the build process.

**Describe alternatives you've considered**
In-place solutions increase friction during debugging activities; enabling source maps will improve engineering productivity.

**Additional context**
Expected to modestly increase build times.

**Comment by wodeni** [comment]
@cmumatt thanks for catching this. I noticed source maps could be inconsistent depending on the context. Are you using rollup or ESBuild? Both are configured to generate source maps. Can you say more about your setup? For instance, live-reloading `core` and `browser-ui` (bundle produced by ESBuild) or importing the production bundle of `core` in a different client (i.e. downloading the bundle from NPM, which is bundled by rollup)?

**Comment by maxkrieger** [comment]
Wonder if we'll wanna eject again, or switch to vitejs

**Comment by wodeni** [comment]
Closing because we switched to vite and generate source maps for all packages in dev mode.
