### ISSUE TITLE
Polygon center does not get used

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#709]
Currently, if a `Polygon` is defined with a `scale` and a `center`, the `scale` gets used as expected, but the `center` gets translated into `cx` and `cy` attributes on the SVG object, which do not change the visual shape at all.

In order to fix this, we'd first need to decide which happens first (scaling vs translation).

**Comment by samestep** [comment]
The same thing appears to happen with `Polyline`.

**Comment by keenancrane** [comment]
Nothing good can come of giving a `Polygon` a `scale` and `center` field.  A polygon is just a sequence of points in the plane.

As you mention in #713, all transformations should be handled via a generic mechanism, such as transformation matrices.  Note also that SVG does not have `scale` or `center` attributes for [\<polygon\>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon).
