### ISSUE TITLE
Make anonymous shapes legal

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#720]
**Is your feature request related to a problem? Please describe.**
It doesn't make much sense to give every shape a name, since most shapes will never be referenced again.  For instance, right now you have to write things like
```
forall Point x; Point y
where Connected(x,y) {
   shape myLine = Line {
      ...
   }
}
```
even if `myLine` will never be referenced.  (Seems you can also drop the type name `shape`, but you still have to pick a name for the shape.)

Forcing shapes to be names effectively pollutes the namespace with a bunch of throwaway names that will not be used, which makes code harder to read/understand.  ("Will I need to remember this name for later?")

**Describe the solution you'd like**
Would be great to allow anonymous shapes, e.g.,
```
forall Point x; Point y
where Connected(x,y) {
   shape Line {
      ...
   }
}
```
or perhaps just
```
forall Point x; Point y
where Connected(x,y) {
   Line {
      ...
   }
}
```
In this scenario, **Style programmers would still have the _option_ to give a shape a name**; they simply wouldn't be _required_ to.

**Describe alternatives you've considered**
Not clear there are currently any good alternatives, other than cooking up names for each shape.

**Additional context**
It seems like it shouldn't be too hard to implement at the parser level, without doing any sort of deep analysis/lookahead/etc.:
Suppose the parser sees the pattern
`shape <token> {`
then it can simply pretend that this line said
`shape <generated_name> = <token> {`
where `generated_name` is some automatically-generated name.  For instance, `anonymous_shape_NNN` where `NNN` is an integer that gets incremented each time an anonymous shape is encountered.  This way, there is still a (somewhat) meaningful name available for the inspector/debugger to display.

**Comment by samestep** [comment]
@wodeni mentioned in Slack that this relates to #623.

**Comment by samestep** [comment]
@wodeni also mentioned that we'd need to have some way to give unique identifiers to these shapes; I'm still familiarizing myself with the Style compiler, but it looks like we'll probably be able to reuse our existing infrastructure for "anonymous statements":

https://github.com/penrose/penrose/blob/3f223f4afe3cd083962e07a804e3222851c56494/packages/core/src/compiler/Style.ts#L1454-L1504

**Comment by keenancrane** [comment]
@samestep Yes indeed.  I'd imagine you can just increment a counter every time you encounter an anonymous shape, and use this number to generate a name.

Would be good to document somewhere (e.g., at the Wiki level) what these generated names look like.  Even if you use `__PENROSE_ANONYMOUS_SHAPE_00XX`, who knows, someone might try using that as the name of a shape. 😓
