### ISSUE TITLE
Polygon points are relative to top-left of canvas, not origin

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#724]
While working on https://github.com/penrose/penrose/pull/698#issuecomment-1002015939, I realized that our current bounding boxes for `Polygon`, `FreeformPolygon`, and `Polyline` are very incorrect.

<img width="1134" alt="Screen Shot 2021-12-28 at 8 38 01 AM" src="https://user-images.githubusercontent.com/8246041/147572050-4d737bb6-5a34-4e04-876b-c0ae06d771c8.png">

This is because, for some reason, the `points` and `scale` properties for those shapes are relative to the top-left corner of the canvas, not the origin `(0, 0)`.

Related:

- #709
- #713

**Comment by keenancrane** [comment]
I also just hit this bug.  The polygon is given the same vertices as the three black dots i, j, k:

![image](https://user-images.githubusercontent.com/3604525/148081357-0e5060b9-458d-4bee-bee7-0f44e1843adb.png)
