### ISSUE TITLE
Access bounding box from Style

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#727]
**Is your feature request related to a problem? Please describe.**
Bounding boxes are now defined for every shape (see #698) but cannot be accessed via Style.  Bounding box dimensions are essential for constructing common shapes, e.g., a box around a piece of text, or a box around a collection of objects (by taking the `max`/`min` of individual boxes).

**Describe the solution you'd like**
A reasonable interface might be to give every shape an implicit `bbox` field, which has attributes `w`, `h`, and `center`.  For instance, in Style one might write
```
forall T x {
   x.text = Text {
      string : x.label
      center : (?,?)
   }

   x.background = Rectangle {
      w : x.text.bbox.w
      h : x.text.bbox.h
      center : x.text.bbox.center
   }
```

**Describe alternatives you've considered**
Currently there is no way to access this information from Style; even the example images in #698 are generated by manually extracting bounding box dimensions from an optimized diagram.

**Comment by wodeni** [comment]
#1411 added `bboxPts`, which allows Style writers to access bboxes of shapes.
