### ISSUE TITLE
Provide random seed

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#731]
**Is your feature request related to a problem? Please describe.**
Running `resample` generates a diagram using a new random seed, but currently this seed cannot be specified programmatically.  Often it's quite useful to get more deterministic behavior, e.g., to reproduce the same diagram in a different style.  This kind of determinism is also useful for debugging (especially in cases where not all diagram instances reproduce the bug).

**Describe the solution you'd like**
There are several possible places to specify the random seed:

- **In a `.sub` program.**  For instance, in the same place where you assign labels, you might also write `Variation seed` where `seed` is an integer corresponding to the seed for the random number generator.
- **In a `.sty` program.** For instance, anywhere in the program (say, at the top of the file, or inside the `canvas` block) you might similarly write `variation = seed`.
- **On the command line.**  E.g., via `roger my.sub my.sty my.dsl --variation=seed`.

Among these options, specifying the seed in the `.sty` file seems the least natural, since different Substance programs may wish to use different seeds.  Likewise, different `.sub`/`.sty` pairs may wish to use different seeds.  However, command-line usage may not always be possible, and doing it _only_ on the command line can cause the desired seed to get "orphaned" from the program (i.e., where do you store it/how do you keep track of it)?  These questions come back to the question of whether we need a small "diagram" file that ties together exactly one `.sub`, `.sty`, and `.dsl` to specify a final diagram (along with metadata such as a seed).

I'll also advocate for a term like `variation` or `variant` rather than `seed`, because `seed` is programmer jargon that may be opaque to many users.

**Describe alternatives you've considered**
The only real alternative is to specify a deterministic initialization scheme for all variables generated by the Style program.  E.g., you could imagine syntax like
```
scalar x = 1.23?
```
which says that x is optimized, but initially takes the value `1.23`.  While this mechanism is probably quite useful as its own feature (!), the burden on the programmer of specifying initial values for _all_ optimized variables is too high—especially since many of these variables/attributes are implicit, and don't appear in most Style programs.

**Additional context**
Unfortunately, JavaScript does not allow you to set the seed for `Math.random()`.  However, there are lots of alternative solutions, including some extremely short and sweet pseudorandom number generators that can be used as alternatives to `Math.random()` (especially since we don't need our numbers to be cryptographically secure!): https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript

**Comment by samestep** [comment]
@maxkrieger Perhaps instead of specifying this in the `.sub` or `.sty` or as a CLI arg, it could be a setting alongside `autoStepSize`?

https://github.com/penrose/penrose/blob/d8337db55657014e9e17966e1f85c4b966a092cf/packages/browser-ui/src/inspector/views/Settings.tsx#L15-L23

**Comment by samestep** [comment]
I'd like to use a splittable random number generator because they're nice. I looked on npm just now to see if there are any existing libraries for these, and I found three:

- [@susisu/tf-random](https://www.npmjs.com/package/@susisu/tf-random) last updated 2020-10-24
- [lcg](https://www.npmjs.com/package/lcg) last updated 2016-07-25
- [splitmix](https://www.npmjs.com/package/splitmix) last updated 2019-08-25

None of these seem actively maintained; should we use one of them or make our own?

**Comment by samestep** [comment]
Actually, now that I think about it a bit more, I should probably just use a standard mutable random number generator. 😅

**Comment by maxkrieger** [comment]
Agree it shouldn't be a parameter of .sty, though .sub is plausible, and a runtime parameter like step size does seem best.
