### ISSUE TITLE
`AutoLabel None` should define an empty label

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#752]
Currently, writing

```
AutoLabel None
```

in a Substance program results in the `.label` field not being created for any instance that does not receive an explicit `Label` invocation.  This behavior makes `AutoLabel None` fairly useless, because any Style block that tries to access `x.label` will fail, with an error message
```
Error looking up path 'x.label' in translation. Field 'label' does not exist.
```

A more reasonable behavior would be that `AutoLabel None` sets all label strings to the empty string, i.e., `x.label =""`.  This way, the label can still be accessed without error for instances that have been labeled.

**Comment by wodeni** [comment]
Fixed by #754
