### ISSUE TITLE
Line attribute `style: "dashed"` no longer works without explicitly setting `strokeDashArray`

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#761]
The GPI declaration
```
shape x.line = Line {
   ...
   stroke: "dashed"
}
```
no longer draws a dashed line, even though something like
```
shape x.line = Line {
   ...
   stroke: "dashed"
   strokeDashArray: "4,4"
}
```
still works.  Inspecting the implementation, it's not immediately clear why this happens since there still seems to be a default dash array defined.  Just needs a more careful look.

**Comment by cmumatt** [comment]
Property renaming replaced the aforementioned `stroke : "dashed"` with `strokeStyle : "dashed"`

Presently this feature is demonstrated in this example:`examples/hyperbolic-domain/PointcareDisk.sty`
