### ISSUE TITLE
Invalid characters permitted in style identifier names

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#767]
**Describe the bug**
Characters such as [,],\,`, and ^ are ostensibly defined as allowed as the first character of a style identifier.  

This is due to an error in the identifier name regex: the first character of an identifier is specified as [A-z_], which includes characters resident between Z and a on the codepage (i.e., [,],`,^,\).

This is not as big a deal as it might initially appear: all but \ are defined as tokens elsewhere.  Trying to use them as the first character of a style identifier generates a different error.  The only one that is actually usable is \.

**To Reproduce**
Define and assign to a style identifier that begins with \.  

**Expected behavior**
[,],`,^, and \ are disallowed in the first character of a style identifier.

**Comment by wodeni** [comment]
Ahh nice catch @cmumatt! Should use `[a-zA-Z]` instead
