### ISSUE TITLE
Use style selectors to define collections (set builder notation)

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#769]
via @keenancrane:

> in chemistry you have many related molecules experiencing various processes, those processes have to get labeled and stuffed into a box of a certain size and so forth. 
> Right now this is a bit tricky because constructs for grouping/gathering various elements are a bit under-developed.

Points to the subproblem of proper graph layout:

> *"How can we define graphs in Style, without users having to think of them as 'graphs' in Substance?"*

> I think actually we can build on the existing Style syntax, and lean on the way things get defined in math

![image](https://user-images.githubusercontent.com/2660634/148456111-a257075a-6aa0-458f-b3c3-bc59c51e601b.png)

> I.e., you'd define the set of vertices and edges as a set of things that meet a certain set of conditions f and g.

```
G = Graph{
   vertices : Type x where VertexPredicate(x)
   edges: Type x; Type y where EdgePredicate(x,y)
}
```

> the pattern matching syntax already gives you a way to select a subset of elements from the Substance program that will become the vertices and edges of an abstract graph.

> A `Graph` object can then be passed off to the layout engine, which can run whatever layout algorithm you want.

> This kind of thinking also, btw, provides a way to collect a list of things.  E.g.,

```
L = List {
   elements : MyType x where MyPredicate(x)
}
```

> Probably want some way of including elements that match more than one regex.  Maybe something like

```
L = List {
       elements : Type1 x where Predicate1(x), Type2 x where Predicate2(x), ...
    }
```

> Lots of discussions to be had about syntax, too.  For a `Graph` it makes sense to have `vertices`: and `edges:` but for a list this feels unnecessary.   (And lots of bickering to be done about the distinction between a `List` and a `Set`… my examples above are really more like a set.)

Related design concern: #766

**Comment by wodeni** [comment]
Kind of addressed by #1390.
