### ISSUE TITLE
Improve color sampling, maybe using/importing palettes

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#78]
Right now our diagram colors are randomly sampled, so they don't look amazing. Add the ability to sample and optimize colors more nicely, as well as use or import palettes.

e.g. do color space optimization (things that are nearby should have different colors)

**Comment by hypotext** [comment]
Slack discussion: 

Max Krieger [2:58 PM]
I discovered this nice library for color generation, https://randomcolor.lllllllllllllllll.com/. It samples from a visually pleasing color space. There's a haskell implementation here http://hackage.haskell.org/package/palette-0.3/docs/Data-Colour-Palette-RandomColor.html

nimoni [7:56 PM]
Seems like they have a couple of harmonies built-in to be chosen from: `[ monochrome, complement, triad, tetrad, analogic, accentAnalogic]`, defined here http://hackage.haskell.org/package/palette-0.3/docs/src/Data.Colour.Palette.Harmony.html (edited)

keenan [2:57 AM]
Neat.  We haven’t talked much about color in Penrose, but one thing that’s quite interesting is that we can use Penrose itself to optimize the colors, in a way that can be more intelligent than just picking a static color palette.  In particular, we can set up an objective that encourages colors of nearby objects to be, say, similar or dissimilar.  This is something I might also do in practice by hand: try to make a clear distinction between (spatially) nearby objects by ensuring their colors are very different.  I would guess that we can either already do this in Style: just set up some global constants like `arrowColor`, `dotColor`, `labelColor`, etc., and then write an objective that penalizes the difference between these colors, weighted according to (say) the closest distance of any two objects that carry these colors.

**Comment by maxkrieger** [comment]
The "ColorBrewer" system seems to be popular. It's commonly used for coloring map visualizations (chloropleths) https://en.wikipedia.org/wiki/Cynthia_Brewer#ColorBrewer http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.361.6082&rep=rep1&type=pdf. It seems to be popular, and used to be part of the d3 core https://beta.observablehq.com/@mbostock/d3-color-schemes http://bl.ocks.org/mhkeller/10504471

**Comment by wodeni** [comment]
Closing in favor of @heleaf's PR #604. We can open up more concrete discussions from there.
