### ISSUE TITLE
Expose match index and total number of matches per rule in Style

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#785]
## Problem

Many diagrams are most naturally expressed in terms of ordinal and/or cardinal numbers.

_Ordinal._ For instance, in this diagram we would like to use an enumeration of marked angles to determine the number of tick marks:

<img src="https://user-images.githubusercontent.com/3604525/148614549-ab0acfd5-92e2-4f46-a5d7-51817c3532eb.png" width="300px">

_Cardinal._ In this diagram, we would like to use the total number of tick marks to determine the spacing between ticks:

<img src="https://user-images.githubusercontent.com/3604525/148614693-2fcfd4fe-f1aa-4c50-b659-bb5285163c86.png" width="400px">

However, the current design of Style makes it hard to specify these kinds of diagrams: even though a given rule may get invoked several times, there is currently no way to determine
- the ordinal for the current match, nor
- the total number of matches for that rule.

## Proposed solution

The proposal is to provide access to the ordinal and match count for each Style rule.  In particular, within a rule block we will allow the programmer to access the integer constants

- `match_id` — gives the (1-based) ordinal of the current match, among all matches for the current block.
- `match_count` — gives the total number of matches for this rule.

For instance, consider the Substance program

```
Point i, j, k
```

and the Style program

```
forall Point p {
   shape p.labelText = Text {
      string: toString(match_id) + "/" + toString(match_count)
      center: (?,?)
      -- ...more attributes...
   }
   shape p.labelWidget = Circle {
      center: p.labelText.center
      -- ...more attributes...
   }
}
```

(Note: I'm aware we don't have string conversion or concatenation syntax... this is just for demonstration purposes. :-))

Together, these programs would produce a drawing like this one:
<img src="https://user-images.githubusercontent.com/3604525/148615962-152c8911-39d3-4f57-92ff-df0affea456a.png" width="300px">

It seems reasonable that attempting to override these values, e.g.,

```
override match_id = 5
```

should produce an error.

### Implementation

According to @wodeni we already keep track of similar information internally, i.e., an ID for each match, and the total number of matches.  Sounds like it may need to be broken down per-rule though.

**Comment by liangyiliang** [comment]
This sounds really interesting and reasonable! Informations such as `match_count` and `match_id` are what we can attach to our `Subst[]` object and individual `Subst` objects.

I think it would be reasonable to have a list of "reserved variable names" which would include things like `match_id` and `match_count`. Whenever we access a variable within the Style block, we first check if they are reserved. If so, we prohibit writing.

**Comment by samestep** [comment]
#1074 resolved this.
