### ISSUE TITLE
Penrose tests (unit, assertion, property-based)

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#8]
I've started documenting the test infrastructure and the working and not-working program pair examples in the [Penrose wiki](https://github.com/penrose/penrose/wiki/Testing).

Would be nice to have code coverage stats. `stack test --coverage` doesn't yet work.

TODO:
- [ ] account for label size set in Snap
- [ ] add rest of examples as regression/unit tests
- [ ] remove gloss dependency
- [ ] test the optimization and computation more thoroughly

Eventually:
- [ ] figure out how to test js files

**Comment by hypotext** [comment]
@wodeni I've set up the testing infrastructure. See the main comment in this issue for more information. You're welcome to start writing tests for the parsers! I haven't written any for the Substance, Style, or Server modules yet, and indeed adding tests for them would be a very useful form of documentation.

**Comment by hypotext** [comment]
@wodeni Also, regarding the revised parser, two of the examples [here](https://github.com/penrose/penrose/wiki/Examples) seem to be failing due to parser issues.

**Comment by hypotext** [comment]
@wodeni Do you know if I can get the label sizes (and any other object info sent by snap) without running the server? As of now, in `mainRetFinal`, since the optimization doesn't interact with snap, the label sizes are zero, which makes the regression tests inconsistent with what shows up in the browser.

**Comment by wodeni** [comment]
The label size is dependent on the font and font size used in `client.js`. Remember initially we assumed the letters to be monospaced but right now they are not due to the current font (palatino). Any chance to let the server run at least once?

**Comment by hypotext** [comment]
I would be fine with running the server during the tests. Can we write a version of the server that terminates and returns a result (or several results, if we want to run multiple tests)?

**Comment by wodeni** [comment]
I was trying to get Travis CI working with our repo and found that the tests now do not compile. The reason might be the changes in Substance module (?). In any case, there are some tests to could add to the test suite:

* DSLL parsing
* Substance Core language
* Substance type checking
* (future) Style type checking

**Comment by wodeni** [comment]
Closing now that we have a working test suite in TS.
