### ISSUE TITLE
SVG to screen transformation issue on Firefox 

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#81]
As @jennalwise reported earlier, on Firefox on Ubuntu, the coordinate system seems to be off and the main geometries are all shifted by some amount outside of the canvas.

**Comment by wodeni** [comment]
Turns out to be a Firefox bug on two specific attributes of `<svg>`: `clientWidth` and `clientHeight`. The browser would erroneously return `0` somehow. See https://github.com/adobe-webplatform/Snap.svg/issues/473 for details.

**Comment by wodeni** [comment]
The issue is solved. @hypotext @dormaayan Let me know if you guys prefer opening a PR and merge vs. just committing to master.

**Comment by dormaayan** [comment]
If it is a small change that will not cause any conflict I’m fine with pushing to the master

**Comment by wodeni** [comment]
Just did that. Closing the issue now.

**Comment by hypotext** [comment]
Thanks for fixing this!
