### ISSUE TITLE
Links to constrDict, objDict and compDict are broken

### ISSUE THREAD

**Issue by christianp** [penrose/penrose#826]
I'm trying to work out which bits of documentation are current, and which are obsolete. The [Function library](https://github.com/penrose/penrose/wiki/Function-library) page in the wiki links to pages listing constraints, objects and computations, but those links all return 404 at the moment. 
For reference, constrDict links to `https://penrose.github.io/penrose/modules/_contrib_constraints_.html#constrdict`.

penrose.github.io/penrose looks like it contains an unmodified Storybook template, so I guess you're in the process of rewriting it.

For now, I'm looking at the `Constraints.ts` source file to work out what the constraints are and how to use them, but I'd appreciate some explanatory text to go with it!

**Comment by keenancrane** [comment]
Apologies.  This page has now been updated (and renamed):

[Style function library](https://github.com/penrose/penrose/wiki/Style-function-library)

Still a long way to go in terms of providing more user-friendly explanations; the comments in the source are unfortunately all we have right now for individual constraint descriptions.  (We have been doing a major overhaul in just the past week of how the whole shape and constraint system works...).

You may also find it helpful to look at some examples of how/where these constraints are used.  Here are two that are reasonably well-commented:

* [exterior-algebra.sty](https://github.com/penrose/penrose/blob/main/examples/exterior-algebra/exterior-algebra.sty)
* [triangle-mesh-2d.sty](https://github.com/penrose/penrose/blob/main/examples/triangle-mesh-2d/triangle-mesh-2d.sty)

Thanks for your feedback, and let us know where else you're bumping into trouble.  We very much need all the help we can get!
