### ISSUE TITLE
Broken links on the wiki

### ISSUE THREAD

**Issue by christianp** [penrose/penrose#828]
You asked for feedback on the documentation, so here's some! I'll update this as I find more broken links, if that's OK.

On the [Getting Started](https://github.com/penrose/penrose/wiki/Getting-started) page there's supposed to be a link to the SIGGRAPH video, on the text "here" at the end of a line, but the URL is missing the `.html` suffix.

**Comment by keenancrane** [comment]
Fixed link to SIGGRAPH video and paper.  Thanks!

**Comment by christianp** [comment]
The same link on the "Home" page is broken, in the same way.

**Comment by keenancrane** [comment]
Fixed—thank you!
