### ISSUE TITLE
IDE Shapes tab currently broken

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#837]
**Describe the bug**
Clicking on the shapes tab either produces a "something went wrong" message or crashes the IDE.

**To Reproduce**
```
yarn start
cd examples/fancy-text
sh run
```
Click Shapes tab

**Expected behavior**
Tab should show the list of shapes.

- OS: OS X 11.6.2
- Browser FF 95.0.2, Chrome 97

**Additional context**
Note: History was removed recently to address high memory usage.

**Comment by wodeni** [comment]
`shapes` is deprecated in `editor`. Closing now.
