### ISSUE TITLE
Bring and keep the changelog up to date

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#854]
We have a [changelog](https://github.com/penrose/penrose/blob/main/CHANGELOG.md) but we've stopped updating it since v1.3.0. We need to bring it up to date with the changes we've made since then, and make a habit of keeping it up to date as we make more changes.

**Comment by wodeni** [comment]
Yep, I think it's time to bump to v1.4.0. Would be good to discuss general rules for releases/roadmap in general.

**Comment by samestep** [comment]
@wodeni Oh I didn't necessarily mean we need to bump to v1.4.0 (although that doesn't seem like a bad idea); rather, I meant that we should be updating the changelog as we go, rather than waiting until a release to update it all at once.

**Comment by samestep** [comment]
Resolved by #1233.
