### ISSUE TITLE
Change web client to output debug/failure messages 

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#9]
Currently only the gloss frontend outputs debug messages.

**Comment by wodeni** [comment]
bb30aad solves the problem by copying `runServer` implementation directly from the [`websockets` package](https://github.com/jaspervdj/websockets) and modifying the source code. Specifically, it was a `bracket` call that prevents the debug messages from appearing, forcing the server to close the socket and ignore debug messages.

**Comment by wodeni** [comment]
d27fc83 solves the problem by copying `runServer` implementation directly from the [`websockets` package](https://github.com/jaspervdj/websockets) and modifying the source code. Specifically, it was a `bracket` call that prevents the debug messages from appearing, forcing the server to close the socket and ignore debug messages.

**Comment by wodeni** [comment]
Snap now displays debug messages. Closing the issue.
