### ISSUE TITLE
Add property access support for Style

### ISSUE THREAD

**Issue by dormaayan** [penrose/penrose#91]
Currently, style does not allow nested access to properties of shapes, for example, the following program will not work:
`Neg v {
        shape = Arrow {
        start = v.shape.start
    }
}` will not work

the desired syntax, as already discussed, is:
`<object>.<shape-name>.<property>`

**Comment by wodeni** [comment]
This change will involve `Runtime`, `Server`, and `Style`. We outline the changes needed here:

- [ ] Generalize `ObjFn` type to take in a list of `TypeIn`
  - Should we also keep the list of float `[a]`?
- [ ] In `Style`, there are several places where property access can happen
  - Objective function/constraint arguments
  - Computation arguments
  - Inside of constructors
- [ ] Runtime gets
- [ ] TODO: how about labels? `A.shape.label.text` vs `A.label.text`

**Comment by dormaayan** [comment]
@wodeni: Great, Thanks! I'll merge it to my plugin branch

**Comment by hypotext** [comment]
I can review the changes today. Do you mind waiting for a review before
merging?

**Comment by dormaayan** [comment]
@hypotext : I already merged and resolved conflicts...

**Comment by hypotext** [comment]
Ok, @wodeni could you open a PR with your branch first? I’ll review there.

@dormaayan if Nimo or I need to make any changes, I guess we can push to
Nimo’s branch and you can pull onto yours when done.

In general, for larger system refactors, I’d wait for at least one person
to review code before merging it :)

**Comment by dormaayan** [comment]
@hypotext : Sounds good to me
