### ISSUE TITLE
Automate Style function documentation extraction

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#927]
**Describe the bug**
The process to update the function documentation on the Docusaurus site is semi-manual due to TypeDoc's present limited support for markdown documentation for function dictionaries.  The workaround is to temporarily transform the function dictionaries into classes, generate the documentation using `yarn docs:md` in `core`, remove any bad links, copy the md output into `/docs-site/docs/style/functions.mdx`, and revert back to the function dictionary 

The goal is to generate this documentation automatically at build time so it is always up-to-date.  The current manual steps are an obstacle to that goal.  At one point we briefly discussed the possibility of permanently converting the function dictionaries into classes; looking into that and any ramifications may be a good initial step to resolving this issue.

**Comment by wodeni** [comment]
Closing as this was resolved by #1427.
