### ISSUE TITLE
Enable strict TS checks in Automator

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#948]
**Describe the bug**
Currently the TypeScript `strict` option is enabled everywhere but Automator.  

The minimal TypeScript checks in Automator make bugs in this module harder to find.  Consequently, we should enable these additional checks and address the issues with the existing code these checks identify.  

PR #947 previously enabled many options, but not `strict`.

**Comment by samestep** [comment]
I really wish we could share TypeScript options across our packages...

**Comment by cmumatt** [comment]
Thanks, @samestep !  That's a great way to keep these more consistent across the monorepo.
