### ISSUE TITLE
Folder re-organization for IDE deployment stopped working

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#951]
**Describe the bug**

#916 introduced a script that moves the `@penrose/panels` site into `docs-site`. The script doesn't work on the latest commit on `main`, and probably never worked. 

For example, the Cloudflare deployment for https://github.com/penrose/penrose/runs/6309129812 actually failed silently:

```
11:29:33.748 | @penrose/docs-site: cp: target './static/try/' is not a directory
-- | --
11:29:36.536 | @penrose/docs-site: [INFO] [en] Creating an optimized production build...
11:29:37.982 | @penrose/docs-site: ℹ Compiling Client
11:29:38.011 | @penrose/docs-site: ℹ Compiling Server
11:31:58.648 | @penrose/docs-site: ✔ Client: Compiled successfully in 2.34m
11:32:02.999 | @penrose/docs-site: ✔ Server: Compiled successfully in 2.42m
```

In general, I think this script is quite fragile and probably not the most sustainable option. Until Cloudflare supports monorepos, we should think about possible workarounds such as [this](https://community.cloudflare.com/t/cloudflare-pages-monorepo-with-github-actions/378934/2)

**Comment by cmumatt** [comment]
Closing: working in production and preview.
