### ISSUE TITLE
Labels are not displayed on Safari

### ISSUE THREAD

**Issue by dormaayan** [penrose/penrose#96]
After adding latex support, labels are not displayed at all while running penrose from Safari (Version 11.1)

To recreate, run `penrose sub/tree.sub sty/venn.sty dsll/setTheory.dsl`.

**Comment by wodeni** [comment]
The current speculation is that the ES6 features we used are not well supported in Safari (`async` and Promises)

**Comment by wodeni** [comment]
Turns out that the `<path>` element for the glyph does exist in the DOM tree just as in Chrome. Somehow Safari cannot render the `<use>` tag in the Snap canvas properly. Look into it later.

**Comment by hypotext** [comment]
Closed since we no longer use snap.
