### ISSUE TITLE
Implementation of the new Style language

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#97]
Implement a new design of the Style language, which has language features such as a new selector grammar and redesigned Style semantics.

## High-level Steps

- "Service" language grammar
- Full Style parser
- Selector statics 
- Matching dynamics
- Translation dynamics
- Block statics
- Selector specificity
- Computational graph building, checking, and inference
- Tests for the new features
- Better error messages similar to that of the DSLL
- Substance - Style interface refactoring

## Canonical names for commonly used variables
- <img width =20 src="https://user-images.githubusercontent.com/11740102/41912416-b1b2b240-791d-11e8-85fa-6a7f7f5d0d27.png"/>: `Env`, typing context
-  <img width =20 src="https://user-images.githubusercontent.com/11740102/41912465-e03e773e-791d-11e8-9c77-14cf904c7f9c.png"/>: local/selector environment
- <img width =20 src="https://user-images.githubusercontent.com/11740102/41912645-01f9e25a-791e-11e8-932e-4cd2a7d08edb.png"/>: Substance bindings
- <img width =20 src="https://user-images.githubusercontent.com/11740102/41912782-14b0e1d2-791e-11e8-930c-a56f75d25693.png"/>: Subtitution
- <img width=20 src="https://user-images.githubusercontent.com/11740102/41913652-e6dab782-791e-11e8-9630-018908471ffd.png"/>: Translation

**Comment by hypotext** [comment]
First draft of new Style compiler was finished in August 2018. Will open new issues for new language features if needed.
