### ISSUE TITLE
Make it possible to run Penrose from local directory

### ISSUE THREAD

**Issue by GeometryCollective** [penrose/penrose#980]
A common usage pattern for using Penrose would be to, e.g., write programs in the directory for a paper, and run Penrose from that directory.  Right now, it seems, we can only run from the Penrose tree (i.e., we have to run on examples within that tree).  Not sure what's needed to fix…

**Comment by wodeni** [comment]
Closing because `roger` can now run anywhere! 

Actual example from @keenancrane :D https://github.com/GeometryCollective/wost-simple/tree/main
